"""Batch 4: ~650 từ bổ sung để đạt 2000."""
import os, sys
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
os.environ.setdefault("DJANGO_SETTINGS_MODULE", "config.settings.development")
import django; django.setup()
from apps.vocabulary.models import Word

WORDS = [
    # A1 - basic actions
    ("open", "/ˈəʊpən/", "verb", "to move so that something is not closed", "mở", "Open the door, please.", "Vui lòng mở cửa.", "A1"),
    ("close", "/kləʊz/", "verb", "to move so that something is shut", "đóng", "Close the window.", "Đóng cửa sổ lại.", "A1"),
    ("give", "/ɡɪv/", "verb", "to hand something to someone", "đưa/cho", "Give me the book.", "Đưa cho tôi quyển sách.", "A1"),
    ("take", "/teɪk/", "verb", "to reach out and get something", "lấy", "Take an umbrella.", "Mang theo ô đi.", "A1"),
    ("find", "/faɪnd/", "verb", "to discover something", "tìm thấy", "I can't find my keys.", "Tôi không thể tìm thấy chìa khóa.", "A1"),
    ("lose", "/luːz/", "verb", "to be unable to find something", "mất", "Don't lose your passport.", "Đừng để mất hộ chiếu.", "A1"),
    ("help", "/help/", "verb", "to assist someone", "giúp đỡ", "Can you help me?", "Bạn có thể giúp tôi không?", "A1"),
    ("need", "/niːd/", "verb", "to require something", "cần", "I need some water.", "Tôi cần một ít nước.", "A1"),
    ("want", "/wɒnt/", "verb", "to desire something", "muốn", "She wants to travel.", "Cô ấy muốn đi du lịch.", "A1"),
    ("like", "/laɪk/", "verb", "to enjoy something", "thích", "He likes football.", "Anh ấy thích bóng đá.", "A1"),
    ("love", "/lʌv/", "verb", "to feel deep affection", "yêu thích", "She loves music.", "Cô ấy yêu thích âm nhạc.", "A1"),
    ("hate", "/heɪt/", "verb", "to dislike very strongly", "ghét", "He hates waking up early.", "Anh ấy ghét thức dậy sớm.", "A1"),
    ("know", "/nəʊ/", "verb", "to have information about something", "biết", "Do you know the answer?", "Bạn có biết câu trả lời không?", "A1"),
    ("think", "/θɪŋk/", "verb", "to use your mind to consider", "nghĩ", "What do you think?", "Bạn nghĩ gì?", "A1"),
    ("say", "/seɪ/", "verb", "to speak words", "nói", "What did she say?", "Cô ấy nói gì vậy?", "A1"),
    ("ask", "/ɑːsk/", "verb", "to put a question to someone", "hỏi", "Ask the teacher.", "Hỏi giáo viên đi.", "A1"),
    ("answer", "/ˈɑːnsər/", "verb", "to respond to a question", "trả lời", "Please answer my question.", "Vui lòng trả lời câu hỏi của tôi.", "A1"),
    ("call", "/kɔːl/", "verb", "to telephone someone", "gọi điện", "Call me tonight.", "Gọi cho tôi tối nay nhé.", "A1"),
    ("meet", "/miːt/", "verb", "to come together with someone", "gặp gỡ", "Let's meet at the café.", "Hãy gặp nhau ở quán cà phê.", "A1"),
    ("wait", "/weɪt/", "verb", "to stay until something happens", "chờ đợi", "Wait here for me.", "Chờ tôi ở đây.", "A1"),
    ("arrive", "/əˈraɪv/", "verb", "to reach a place", "đến nơi", "We arrive at 9 AM.", "Chúng tôi đến lúc 9 giờ sáng.", "A1"),
    ("leave", "/liːv/", "verb", "to go away from a place", "rời đi", "She left the office at 5.", "Cô ấy rời văn phòng lúc 5 giờ.", "A1"),
    ("start", "/stɑːrt/", "verb", "to begin something", "bắt đầu", "Start the engine.", "Khởi động động cơ.", "A1"),
    ("stop", "/stɒp/", "verb", "to come to an end", "dừng lại", "Stop talking!", "Ngừng nói chuyện!", "A1"),
    ("finish", "/ˈfɪnɪʃ/", "verb", "to complete something", "hoàn thành", "Finish your meal.", "Ăn hết bữa ăn đi.", "A1"),
    ("work", "/wɜːrk/", "verb", "to do a job", "làm việc", "She works every day.", "Cô ấy làm việc mỗi ngày.", "A1"),
    ("study", "/ˈstʌdi/", "verb", "to learn about something", "học tập", "He studies at university.", "Anh ấy học ở đại học.", "A1"),
    ("listen", "/ˈlɪsən/", "verb", "to pay attention to a sound", "lắng nghe", "Listen to the teacher.", "Lắng nghe giáo viên.", "A1"),
    ("watch", "/wɒtʃ/", "verb", "to look at something for a period", "xem", "Watch the movie.", "Xem bộ phim.", "A1"),
    ("show", "/ʃəʊ/", "verb", "to let someone see something", "chỉ/cho xem", "Show me your work.", "Cho tôi xem bài của bạn.", "A1"),
    ("put", "/pʊt/", "verb", "to place something somewhere", "đặt", "Put it on the table.", "Đặt lên bàn.", "A1"),
    ("keep", "/kiːp/", "verb", "to continue having something", "giữ", "Keep the change.", "Giữ lấy tiền thừa.", "A1"),
    ("tell", "/tel/", "verb", "to give information to someone", "nói/kể", "Tell me the truth.", "Nói cho tôi biết sự thật.", "A1"),
    ("feel", "/fiːl/", "verb", "to be aware of an emotion", "cảm thấy", "How do you feel?", "Bạn cảm thấy thế nào?", "A1"),
    ("forget", "/fəˈɡet/", "verb", "to fail to remember", "quên", "Don't forget to call.", "Đừng quên gọi điện.", "A1"),
    ("remember", "/rɪˈmembər/", "verb", "to bring something back to mind", "nhớ", "Remember your password.", "Nhớ mật khẩu của bạn.", "A1"),
    ("try", "/traɪ/", "verb", "to make an effort to do something", "cố gắng", "Try your best.", "Cố gắng hết sức.", "A1"),
    ("use", "/juːz/", "verb", "to employ something for a purpose", "sử dụng", "Use a dictionary.", "Sử dụng từ điển.", "A1"),
    ("make", "/meɪk/", "verb", "to create or produce something", "làm/tạo ra", "Make a cup of tea.", "Pha một tách trà.", "A1"),
    ("get", "/ɡet/", "verb", "to receive or obtain", "nhận/lấy được", "Get some rest.", "Nghỉ ngơi đi.", "A1"),
    ("come", "/kʌm/", "verb", "to move toward something", "đến", "Come here!", "Lại đây!", "A1"),
    ("go", "/ɡəʊ/", "verb", "to move from one place to another", "đi", "Let's go!", "Đi thôi!", "A1"),
    ("see", "/siː/", "verb", "to perceive with eyes", "nhìn thấy", "I can see the mountains.", "Tôi có thể nhìn thấy những ngọn núi.", "A1"),
    ("hear", "/hɪər/", "verb", "to perceive sounds with ears", "nghe thấy", "Did you hear that?", "Bạn có nghe thấy không?", "A1"),
    ("look", "/lʊk/", "verb", "to direct eyes at something", "nhìn", "Look at this!", "Nhìn xem cái này!", "A1"),
    ("read", "/riːd/", "verb", "to understand written words", "đọc", "Read the instructions.", "Đọc hướng dẫn.", "A1"),
    ("write", "/raɪt/", "verb", "to form letters or words on a surface", "viết", "Write your name.", "Viết tên của bạn.", "A1"),
    ("speak", "/spiːk/", "verb", "to say words", "nói chuyện", "She speaks French.", "Cô ấy nói tiếng Pháp.", "A1"),
    ("send", "/send/", "verb", "to cause something to go somewhere", "gửi", "Send me an email.", "Gửi cho tôi một email.", "A1"),
    ("receive", "/rɪˈsiːv/", "verb", "to get something sent to you", "nhận", "Did you receive my message?", "Bạn có nhận được tin nhắn của tôi không?", "A1"),
    # A2 - describing places & things
    ("beautiful", "/ˈbjuːtɪfəl/", "adjective", "very attractive to look at", "đẹp", "The sunset is beautiful.", "Hoàng hôn thật đẹp.", "A2"),
    ("ugly", "/ˈʌɡli/", "adjective", "unpleasant to look at", "xấu", "That building is ugly.", "Tòa nhà đó rất xấu.", "A2"),
    ("clean", "/kliːn/", "adjective", "not dirty", "sạch sẽ", "Keep your room clean.", "Giữ phòng của bạn sạch sẽ.", "A2"),
    ("dirty", "/ˈdɜːrti/", "adjective", "not clean", "bẩn", "Wash your dirty hands.", "Rửa tay bẩn đi.", "A2"),
    ("noisy", "/ˈnɔɪzi/", "adjective", "making a lot of noise", "ồn ào", "The street is very noisy.", "Đường phố rất ồn ào.", "A2"),
    ("quiet", "/ˈkwaɪət/", "adjective", "making very little noise", "yên tĩnh", "The library is quiet.", "Thư viện yên tĩnh.", "A2"),
    ("crowded", "/ˈkraʊdɪd/", "adjective", "full of people", "đông đúc", "The market is very crowded.", "Chợ rất đông đúc.", "A2"),
    ("empty", "/ˈempti/", "adjective", "containing nothing", "trống rỗng", "The bottle is empty.", "Chai trống rỗng.", "A2"),
    ("full", "/fʊl/", "adjective", "containing as much as possible", "đầy", "The glass is full.", "Ly đầy.", "A2"),
    ("fast", "/fɑːst/", "adjective", "moving quickly", "nhanh", "The train is very fast.", "Con tàu rất nhanh.", "A2"),
    ("slow", "/sləʊ/", "adjective", "not moving quickly", "chậm", "The bus is slow today.", "Xe buýt hôm nay chậm.", "A2"),
    ("heavy", "/ˈhevi/", "adjective", "weighing a lot", "nặng", "The box is very heavy.", "Cái hộp rất nặng.", "A2"),
    ("light", "/laɪt/", "adjective", "not heavy", "nhẹ", "This bag is very light.", "Túi này rất nhẹ.", "A2"),
    ("bright", "/braɪt/", "adjective", "giving off strong light", "sáng", "The sun is very bright.", "Mặt trời rất sáng.", "A2"),
    ("dark", "/dɑːrk/", "adjective", "having very little light", "tối", "The room is dark.", "Căn phòng tối.", "A2"),
    ("wet", "/wet/", "adjective", "covered with liquid", "ướt", "My shoes are wet.", "Giày của tôi bị ướt.", "A2"),
    ("dry", "/draɪ/", "adjective", "not wet", "khô", "The washing is dry.", "Quần áo đã khô.", "A2"),
    ("hot", "/hɒt/", "adjective", "having a high temperature", "nóng", "The weather is very hot.", "Thời tiết rất nóng.", "A2"),
    ("cold", "/kəʊld/", "adjective", "having a low temperature", "lạnh", "It is cold outside.", "Bên ngoài lạnh.", "A2"),
    ("warm", "/wɔːrm/", "adjective", "pleasantly high in temperature", "ấm áp", "The soup is warm.", "Súp ấm áp.", "A2"),
    ("cool", "/kuːl/", "adjective", "fairly low in temperature", "mát mẻ", "The evening is cool.", "Buổi tối mát mẻ.", "A2"),
    ("strong", "/strɒŋ/", "adjective", "having great physical strength", "mạnh mẽ", "He is very strong.", "Anh ấy rất mạnh mẽ.", "A2"),
    ("weak", "/wiːk/", "adjective", "lacking strength", "yếu ớt", "She felt weak after illness.", "Cô ấy cảm thấy yếu ớt sau khi bệnh.", "A2"),
    ("safe", "/seɪf/", "adjective", "protected from danger", "an toàn", "The area is safe at night.", "Khu vực an toàn vào ban đêm.", "A2"),
    ("dangerous", "/ˈdeɪndʒərəs/", "adjective", "likely to cause harm", "nguy hiểm", "Speeding is dangerous.", "Lái xe nhanh rất nguy hiểm.", "A2"),
    ("difficult", "/ˈdɪfɪkəlt/", "adjective", "not easy to do", "khó khăn", "The exam was difficult.", "Kỳ thi rất khó khăn.", "A2"),
    ("easy", "/ˈiːzi/", "adjective", "not difficult", "dễ dàng", "The test was easy.", "Bài kiểm tra dễ.", "A2"),
    ("important", "/ɪmˈpɔːrtənt/", "adjective", "having great value or effect", "quan trọng", "Sleep is important.", "Ngủ rất quan trọng.", "A2"),
    ("necessary", "/ˈnesəseri/", "adjective", "needed to achieve something", "cần thiết", "Exercise is necessary.", "Tập thể dục rất cần thiết.", "A2"),
    ("possible", "/ˈpɒsɪbəl/", "adjective", "able to be done or achieved", "có thể", "Is it possible to finish today?", "Hôm nay có thể hoàn thành không?", "A2"),
    # B1 - time & sequence
    ("recently", "/ˈriːsəntli/", "adverb", "not long ago", "gần đây", "She recently got a promotion.", "Cô ấy gần đây vừa được thăng chức.", "B1"),
    ("currently", "/ˈkʌrəntli/", "adverb", "at the present time", "hiện tại", "He is currently working abroad.", "Anh ấy hiện tại đang làm việc ở nước ngoài.", "B1"),
    ("eventually", "/ɪˈventʃuəli/", "adverb", "in the end, after time", "cuối cùng", "They eventually found a solution.", "Cuối cùng họ tìm được giải pháp.", "B1"),
    ("immediately", "/ɪˈmiːdiətli/", "adverb", "at once, without delay", "ngay lập tức", "Call me immediately.", "Gọi cho tôi ngay lập tức.", "B1"),
    ("gradually", "/ˈɡrædʒuəli/", "adverb", "slowly, over a period of time", "dần dần", "Her English improved gradually.", "Tiếng Anh của cô ấy dần dần cải thiện.", "B1"),
    ("suddenly", "/ˈsʌdənli/", "adverb", "quickly and unexpectedly", "đột ngột", "She suddenly stopped talking.", "Cô ấy đột ngột ngừng nói chuyện.", "B1"),
    ("frequently", "/ˈfriːkwəntli/", "adverb", "often, many times", "thường xuyên", "He frequently works late.", "Anh ấy thường xuyên làm việc muộn.", "B1"),
    ("rarely", "/ˈreərli/", "adverb", "not often", "hiếm khi", "She rarely eats fast food.", "Cô ấy hiếm khi ăn đồ ăn nhanh.", "B1"),
    ("approximately", "/əˈprɒksɪmətli/", "adverb", "almost exactly", "xấp xỉ", "It costs approximately 50 dollars.", "Chi phí khoảng 50 đô la.", "B1"),
    ("meanwhile", "/ˈmiːnwaɪl/", "adverb", "at the same time", "trong khi đó", "Meanwhile, the team was working.", "Trong khi đó, nhóm đang làm việc.", "B1"),
    # B1 - connecting & arguing
    ("however", "/haʊˈevər/", "adverb", "in contrast to what was said before", "tuy nhiên", "He tried hard; however, he failed.", "Anh ấy cố gắng; tuy nhiên, anh ấy thất bại.", "B1"),
    ("therefore", "/ˈðeərfɔːr/", "adverb", "for that reason", "vì vậy", "She was tired; therefore she rested.", "Cô ấy mệt; vì vậy cô ấy nghỉ ngơi.", "B1"),
    ("furthermore", "/ˌfɜːrðərˈmɔːr/", "adverb", "in addition to what was said", "hơn nữa", "The plan is cheap; furthermore it is fast.", "Kế hoạch rẻ; hơn nữa nó nhanh chóng.", "B1"),
    ("although", "/ɔːlˈðəʊ/", "conjunction", "in spite of the fact that", "mặc dù", "Although it rained, we went out.", "Mặc dù trời mưa, chúng tôi vẫn ra ngoài.", "B1"),
    ("unless", "/ənˈles/", "conjunction", "except on the condition that", "trừ khi", "Don't go unless you're ready.", "Đừng đi trừ khi bạn đã sẵn sàng.", "B1"),
    ("whereas", "/weərˈæz/", "conjunction", "in comparison with the fact that", "trong khi đó", "She is quiet, whereas he talks a lot.", "Cô ấy im lặng, trong khi anh ấy nói nhiều.", "B1"),
    ("consequently", "/ˈkɒnsɪkwəntli/", "adverb", "as a result", "do đó", "He worked hard; consequently he succeeded.", "Anh ấy làm việc chăm chỉ; do đó anh ấy thành công.", "B1"),
    ("despite", "/dɪˈspaɪt/", "preposition", "without being affected by", "mặc dù", "Despite the rain, we played.", "Mặc dù trời mưa, chúng tôi vẫn chơi.", "B1"),
    ("otherwise", "/ˈʌðərwaɪz/", "adverb", "if not, in different circumstances", "nếu không", "Hurry, otherwise we'll be late.", "Nhanh lên, nếu không chúng ta sẽ muộn.", "B1"),
    ("nevertheless", "/ˌnevərðəˈles/", "adverb", "in spite of what has been said", "tuy vậy", "It was hard; nevertheless she succeeded.", "Khó khăn; tuy vậy cô ấy đã thành công.", "B1"),
    # B2 - Art & culture
    ("sculpture", "/ˈskʌlptʃər/", "noun", "art made by shaping materials", "điêu khắc", "The sculpture was made of marble.", "Tác phẩm điêu khắc làm từ đá cẩm thạch.", "B2"),
    ("exhibition", "/ˌeksɪˈbɪʃən/", "noun", "a public display of art or objects", "triển lãm", "We visited the art exhibition.", "Chúng tôi thăm triển lãm nghệ thuật.", "B2"),
    ("architecture", "/ˈɑːrkɪtektʃər/", "noun", "the design and style of buildings", "kiến trúc", "Gothic architecture is beautiful.", "Kiến trúc Gothic rất đẹp.", "B2"),
    ("novel", "/ˈnɒvəl/", "noun", "a long fictional book", "tiểu thuyết", "She read the novel in two days.", "Cô ấy đọc tiểu thuyết trong hai ngày.", "B2"),
    ("poetry", "/ˈpəʊɪtri/", "noun", "writing in verse form", "thơ ca", "She writes poetry in her free time.", "Cô ấy viết thơ vào thời gian rảnh.", "B2"),
    ("author", "/ˈɔːθər/", "noun", "a person who writes books", "tác giả", "The author signed my book.", "Tác giả đã ký sách cho tôi.", "B2"),
    ("composer", "/kəmˈpəʊzər/", "noun", "a person who writes music", "nhà soạn nhạc", "Beethoven was a famous composer.", "Beethoven là nhà soạn nhạc nổi tiếng.", "B2"),
    ("genre", "/ˈʒɒnrə/", "noun", "a category of art or literature", "thể loại", "What is your favourite genre?", "Thể loại yêu thích của bạn là gì?", "B2"),
    ("rhythm", "/ˈrɪðəm/", "noun", "a regular pattern of sound or movement", "nhịp điệu", "The music has a great rhythm.", "Âm nhạc có nhịp điệu tuyệt vời.", "B2"),
    ("melody", "/ˈmelədi/", "noun", "a series of musical notes", "giai điệu", "The melody is very catchy.", "Giai điệu rất dễ nhớ.", "B2"),
    ("instrument", "/ˈɪnstrəmənt/", "noun", "a device for making music", "nhạc cụ", "She plays three instruments.", "Cô ấy chơi được ba nhạc cụ.", "B2"),
    ("orchestra", "/ˈɔːrkɪstrə/", "noun", "a large group of musicians", "dàn nhạc", "The orchestra performed beautifully.", "Dàn nhạc biểu diễn rất đẹp.", "B2"),
    ("portrait", "/ˈpɔːrtrɪt/", "noun", "a painting or photo of a person", "chân dung", "She had her portrait painted.", "Cô ấy có bức chân dung được vẽ.", "B2"),
    ("gallery", "/ˈɡæləri/", "noun", "a room or building for displaying art", "phòng trưng bày", "Visit the art gallery downtown.", "Thăm phòng trưng bày nghệ thuật ở trung tâm thành phố.", "B2"),
    # B2 - Health & medicine
    ("symptom", "/ˈsɪmptəm/", "noun", "a sign of illness", "triệu chứng", "Describe your symptoms to the doctor.", "Mô tả triệu chứng cho bác sĩ.", "B2"),
    ("diagnosis", "/ˌdaɪəɡˈnəʊsɪs/", "noun", "the identification of an illness", "chẩn đoán", "The diagnosis was diabetes.", "Chẩn đoán là tiểu đường.", "B2"),
    ("treatment", "/ˈtriːtmənt/", "noun", "medical care given for an illness", "điều trị", "The treatment is effective.", "Phương pháp điều trị hiệu quả.", "B2"),
    ("surgery", "/ˈsɜːrdʒəri/", "noun", "a medical operation", "phẫu thuật", "She underwent surgery.", "Cô ấy đã phẫu thuật.", "B2"),
    ("prescription", "/prɪˈskrɪpʃən/", "noun", "a written order for medicine", "đơn thuốc", "Follow the doctor's prescription.", "Làm theo đơn thuốc của bác sĩ.", "B2"),
    ("vaccine", "/ˈvæksiːn/", "noun", "a substance that protects against disease", "vắc-xin", "Get vaccinated against flu.", "Tiêm vắc-xin phòng cúm.", "B2"),
    ("immune", "/ɪˈmjuːn/", "adjective", "protected from a disease", "miễn dịch", "She is immune to the virus.", "Cô ấy miễn dịch với virus.", "B2"),
    ("chronic", "/ˈkrɒnɪk/", "adjective", "lasting for a long time", "mãn tính", "He has a chronic illness.", "Anh ấy mắc bệnh mãn tính.", "B2"),
    ("recover", "/rɪˈkʌvər/", "verb", "to become well again after illness", "hồi phục", "She is recovering from flu.", "Cô ấy đang hồi phục sau cúm.", "B2"),
    ("prevention", "/prɪˈvenʃən/", "noun", "stopping something bad from happening", "phòng ngừa", "Prevention is better than cure.", "Phòng bệnh hơn chữa bệnh.", "B2"),
    # C1 - abstract nouns
    ("integrity", "/ɪnˈteɡrɪti/", "noun", "being honest and having strong morals", "tính chính trực", "He is known for his integrity.", "Anh ấy nổi tiếng về tính chính trực.", "C1"),
    ("resilience", "/rɪˈzɪliəns/", "noun", "the ability to recover quickly from difficulties", "khả năng phục hồi", "Resilience is key in hard times.", "Khả năng phục hồi là chìa khóa trong thời gian khó khăn.", "C1"),
    ("empathy", "/ˈempəθi/", "noun", "the ability to understand another's feelings", "sự đồng cảm", "Show empathy to those in need.", "Hãy thể hiện sự đồng cảm với những người cần giúp đỡ.", "C1"),
    ("innovation", "/ˌɪnəˈveɪʃən/", "noun", "introducing new ideas or methods", "đổi mới sáng tạo", "Innovation drives economic growth.", "Đổi mới sáng tạo thúc đẩy tăng trưởng kinh tế.", "C1"),
    ("autonomy", "/ɔːˈtɒnəmi/", "noun", "the right to self-govern", "quyền tự chủ", "She values her autonomy.", "Cô ấy coi trọng quyền tự chủ.", "C1"),
    ("consensus", "/kənˈsensəs/", "noun", "a general agreement among a group", "đồng thuận", "Reach a consensus before deciding.", "Đạt được đồng thuận trước khi quyết định.", "C1"),
    ("implication", "/ˌɪmplɪˈkeɪʃən/", "noun", "a possible consequence of an action", "hàm ý/tác động", "Consider the implications first.", "Hãy xem xét các tác động trước.", "C1"),
    ("phenomenon", "/fɪˈnɒmɪnən/", "noun", "an observable fact or event", "hiện tượng", "Rainbows are a natural phenomenon.", "Cầu vồng là một hiện tượng tự nhiên.", "C1"),
    ("magnitude", "/ˈmæɡnɪtjuːd/", "noun", "the great size or extent of something", "mức độ/cường độ", "The magnitude of the problem is clear.", "Mức độ của vấn đề rất rõ ràng.", "C1"),
    ("sophistication", "/səˌfɪstɪˈkeɪʃən/", "noun", "the quality of being complex and refined", "sự tinh tế", "Her writing shows great sophistication.", "Bài viết của cô ấy thể hiện sự tinh tế.", "C1"),
    # TOEIC - Meetings & presentations
    ("presentation", "/ˌprezənˈteɪʃən/", "noun", "a formal talk or demonstration", "bài thuyết trình", "She gave an excellent presentation.", "Cô ấy thuyết trình xuất sắc.", "TOEIC"),
    ("keynote", "/ˈkiːnəʊt/", "noun", "the main speech at a conference", "bài phát biểu chính", "Who is the keynote speaker?", "Ai là diễn giả chính?", "TOEIC"),
    ("seminar", "/ˈsemɪnɑːr/", "noun", "a small class for discussion", "hội thảo", "Attend the marketing seminar.", "Tham gia hội thảo marketing.", "TOEIC"),
    ("workshop", "/ˈwɜːrkʃɒp/", "noun", "a session for learning skills", "buổi thực hành", "Join the leadership workshop.", "Tham gia buổi thực hành lãnh đạo.", "TOEIC"),
    ("conference", "/ˈkɒnfərəns/", "noun", "a large formal meeting", "hội nghị", "She attended an international conference.", "Cô ấy tham dự một hội nghị quốc tế.", "TOEIC"),
    ("handout", "/ˈhændaʊt/", "noun", "printed material given out at a meeting", "tài liệu phát tay", "Please take a handout.", "Vui lòng lấy tài liệu phát tay.", "TOEIC"),
    ("postpone", "/pəʊstˈpəʊn/", "verb", "to arrange for something to happen later", "hoãn lại", "We had to postpone the meeting.", "Chúng tôi phải hoãn cuộc họp.", "TOEIC"),
    ("reschedule", "/ˌriːˈʃedjuːl/", "verb", "to arrange a different time for something", "đổi lịch", "Can we reschedule for Friday?", "Chúng ta có thể đổi lịch sang thứ Sáu không?", "TOEIC"),
    ("facilitate", "/fəˈsɪlɪteɪt/", "verb", "to make something easier to achieve", "tạo điều kiện/hỗ trợ", "He will facilitate the meeting.", "Anh ấy sẽ điều phối cuộc họp.", "TOEIC"),
    ("wrap up", "/ˌræp ˈʌp/", "verb", "to finish or conclude something", "kết thúc", "Let's wrap up the meeting.", "Hãy kết thúc cuộc họp.", "TOEIC"),
    # TOEIC - Customer service
    ("complaint", "/kəmˈpleɪnt/", "noun", "an expression of dissatisfaction", "khiếu nại", "File a complaint with the manager.", "Khiếu nại với quản lý.", "TOEIC"),
    ("warranty", "/ˈwɒrənti/", "noun", "a written guarantee on a product", "bảo hành", "The warranty covers one year.", "Bảo hành bao gồm một năm.", "TOEIC"),
    ("shipment", "/ˈʃɪpmənt/", "noun", "goods sent by ship, truck or air", "lô hàng", "The shipment arrives tomorrow.", "Lô hàng đến vào ngày mai.", "TOEIC"),
    ("tracking", "/ˈtrækɪŋ/", "noun", "following the progress of something", "theo dõi", "Use tracking to find your package.", "Dùng theo dõi để tìm gói của bạn.", "TOEIC"),
    ("quote", "/kwəʊt/", "noun", "a stated price for goods or services", "báo giá", "Please send me a quote.", "Vui lòng gửi cho tôi báo giá.", "TOEIC"),
    ("billing", "/ˈbɪlɪŋ/", "noun", "the process of sending invoices", "lập hóa đơn", "Billing is done monthly.", "Lập hóa đơn hàng tháng.", "TOEIC"),
    ("feedback", "/ˈfiːdbæk/", "noun", "information about reactions to a product", "phản hồi", "We value your feedback.", "Chúng tôi trân trọng phản hồi của bạn.", "TOEIC"),
    ("satisfaction", "/ˌsætɪsˈfækʃən/", "noun", "the feeling of having what you need", "sự hài lòng", "Customer satisfaction is our goal.", "Sự hài lòng của khách hàng là mục tiêu của chúng tôi.", "TOEIC"),
    ("availability", "/əˌveɪləˈbɪlɪti/", "noun", "the state of being ready or obtainable", "tính sẵn có", "Check the availability of the product.", "Kiểm tra tính sẵn có của sản phẩm.", "TOEIC"),
    ("courier", "/ˈkʊriər/", "noun", "a person or company delivering packages", "dịch vụ chuyển phát", "Send it by courier.", "Gửi bằng dịch vụ chuyển phát.", "TOEIC"),
    # B2 - Travel & tourism
    ("itinerary", "/aɪˈtɪnərəri/", "noun", "a planned route for a journey", "lịch trình", "Share the itinerary with everyone.", "Chia sẻ lịch trình với mọi người.", "B2"),
    ("accommodation", "/əˌkɒməˈdeɪʃən/", "noun", "a place to stay temporarily", "chỗ ở", "Book accommodation in advance.", "Đặt chỗ ở trước.", "B2"),
    ("destination", "/ˌdestɪˈneɪʃən/", "noun", "the place you are travelling to", "điểm đến", "Paris is a popular destination.", "Paris là điểm đến phổ biến.", "B2"),
    ("excursion", "/ɪkˈskɜːrʒən/", "noun", "a short trip for pleasure", "chuyến tham quan", "We went on a boat excursion.", "Chúng tôi đi tham quan bằng thuyền.", "B2"),
    ("souvenir", "/ˌsuːvəˈnɪər/", "noun", "an object bought to remember a trip", "quà lưu niệm", "She bought souvenirs for her family.", "Cô ấy mua quà lưu niệm cho gia đình.", "B2"),
    ("passport", "/ˈpɑːspɔːrt/", "noun", "a document allowing travel between countries", "hộ chiếu", "Don't forget your passport.", "Đừng quên hộ chiếu.", "B2"),
    ("visa", "/ˈviːzə/", "noun", "a permit to enter a country", "thị thực", "She applied for a tourist visa.", "Cô ấy đăng ký thị thực du lịch.", "B2"),
    ("customs", "/ˈkʌstəmz/", "noun", "the authority that checks goods at borders", "hải quan", "Declare goods at customs.", "Khai báo hàng hóa tại hải quan.", "B2"),
    ("departure", "/dɪˈpɑːrtʃər/", "noun", "the act of leaving a place", "khởi hành", "The departure is at 6 AM.", "Khởi hành lúc 6 giờ sáng.", "B2"),
    ("boarding", "/ˈbɔːrdɪŋ/", "noun", "the process of getting on a plane", "lên máy bay", "Boarding begins in 30 minutes.", "Lên máy bay bắt đầu sau 30 phút.", "B2"),
    # B1 - Language & learning
    ("vocabulary", "/vəˈkæbjʊləri/", "noun", "all the words a person knows", "từ vựng", "Expand your vocabulary daily.", "Mở rộng vốn từ vựng mỗi ngày.", "B1"),
    ("grammar", "/ˈɡræmər/", "noun", "the rules of a language", "ngữ pháp", "Study grammar to write better.", "Học ngữ pháp để viết tốt hơn.", "B1"),
    ("pronunciation", "/prəˌnʌnsiˈeɪʃən/", "noun", "the way words are spoken", "phát âm", "Good pronunciation improves fluency.", "Phát âm tốt cải thiện sự trôi chảy.", "B1"),
    ("fluency", "/ˈfluːənsi/", "noun", "the ability to speak smoothly", "sự trôi chảy", "She speaks with great fluency.", "Cô ấy nói rất trôi chảy.", "B1"),
    ("accent", "/ˈæksent/", "noun", "the way words are pronounced in a region", "giọng địa phương", "He has a British accent.", "Anh ấy có giọng Anh.", "B1"),
    ("translate", "/trænsˈleɪt/", "verb", "to convert from one language to another", "dịch thuật", "Translate the sentence into Vietnamese.", "Dịch câu sang tiếng Việt.", "B1"),
    ("comprehension", "/ˌkɒmprɪˈhenʃən/", "noun", "understanding the meaning of something", "sự hiểu biết", "Reading comprehension improves with practice.", "Hiểu đọc cải thiện với luyện tập.", "B1"),
    ("bilingual", "/baɪˈlɪŋɡwəl/", "adjective", "able to speak two languages", "song ngữ", "She is bilingual in English and French.", "Cô ấy thông thạo tiếng Anh và tiếng Pháp.", "B1"),
    ("native", "/ˈneɪtɪv/", "adjective", "relating to the place of birth", "bản ngữ", "English is her native language.", "Tiếng Anh là ngôn ngữ mẹ đẻ của cô ấy.", "B1"),
    ("dialect", "/ˈdaɪəlekt/", "noun", "a local variety of a language", "phương ngữ", "Each region has its own dialect.", "Mỗi vùng có phương ngữ riêng.", "B1"),
    # A2 - weather & nature
    ("rain", "/reɪn/", "noun", "water falling from clouds", "mưa", "The rain is heavy today.", "Trời mưa to hôm nay.", "A2"),
    ("snow", "/snəʊ/", "noun", "frozen water falling from clouds", "tuyết", "Snow covered the mountains.", "Tuyết phủ trắng núi.", "A2"),
    ("wind", "/wɪnd/", "noun", "air moving naturally", "gió", "Strong wind blew the leaves.", "Gió mạnh thổi lá.", "A2"),
    ("cloud", "/klaʊd/", "noun", "a white or grey mass in the sky", "đám mây", "Dark clouds mean rain.", "Mây đen báo mưa.", "A2"),
    ("fog", "/fɒɡ/", "noun", "thick cloud close to the ground", "sương mù", "Drive carefully in fog.", "Lái xe cẩn thận khi trời sương mù.", "A2"),
    ("storm", "/stɔːrm/", "noun", "a period of bad weather with rain", "bão", "A storm is coming.", "Bão đang đến.", "A2"),
    ("thunder", "/ˈθʌndər/", "noun", "the loud noise during a storm", "sấm sét", "Thunder scared the child.", "Tiếng sấm làm trẻ sợ.", "A2"),
    ("lightning", "/ˈlaɪtnɪŋ/", "noun", "a bright flash in the sky during a storm", "tia sét", "Lightning struck the tree.", "Sét đánh trúng cây.", "A2"),
    ("rainbow", "/ˈreɪnbəʊ/", "noun", "a coloured arc in the sky after rain", "cầu vồng", "A rainbow appeared after the rain.", "Cầu vồng xuất hiện sau cơn mưa.", "A2"),
    ("temperature", "/ˈtemprɪtʃər/", "noun", "how hot or cold something is", "nhiệt độ", "The temperature dropped at night.", "Nhiệt độ giảm vào ban đêm.", "A2"),
    ("flood", "/flʌd/", "noun", "when land is covered with water", "lũ lụt", "Floods damaged many homes.", "Lũ lụt phá hủy nhiều ngôi nhà.", "A2"),
    ("drought", "/draʊt/", "noun", "a long period without rain", "hạn hán", "The drought lasted three months.", "Hạn hán kéo dài ba tháng.", "A2"),
    ("earthquake", "/ˈɜːrθkweɪk/", "noun", "a sudden violent shaking of the ground", "động đất", "The earthquake destroyed buildings.", "Động đất phá hủy các tòa nhà.", "A2"),
    ("volcano", "/vɒlˈkeɪnəʊ/", "noun", "a mountain that can erupt with lava", "núi lửa", "The volcano erupted suddenly.", "Núi lửa phun trào bất ngờ.", "A2"),
    ("ocean", "/ˈəʊʃən/", "noun", "a very large sea", "đại dương", "The Pacific is the biggest ocean.", "Thái Bình Dương là đại dương lớn nhất.", "A2"),
    ("lake", "/leɪk/", "noun", "a large area of water surrounded by land", "hồ", "We swam in the lake.", "Chúng tôi bơi trong hồ.", "A2"),
    ("valley", "/ˈvæli/", "noun", "an area of low land between hills", "thung lũng", "The valley was green and lush.", "Thung lũng xanh tươi.", "A2"),
    ("desert", "/ˈdezərt/", "noun", "a dry area with little rainfall", "sa mạc", "The Sahara is the largest desert.", "Sa mạc Sahara là sa mạc lớn nhất.", "A2"),
    ("jungle", "/ˈdʒʌŋɡəl/", "noun", "a dense tropical forest", "rừng nhiệt đới", "Many animals live in the jungle.", "Nhiều động vật sống trong rừng nhiệt đới.", "A2"),
    ("coast", "/kəʊst/", "noun", "the land next to the sea", "bờ biển", "We drove along the coast.", "Chúng tôi lái xe dọc theo bờ biển.", "A2"),
    # C1 - academic writing
    ("assert", "/əˈsɜːrt/", "verb", "to state something confidently as true", "khẳng định", "She asserted that the data was correct.", "Cô ấy khẳng định rằng dữ liệu là chính xác.", "C1"),
    ("assume", "/əˈsjuːm/", "verb", "to accept something without proof", "giả định", "Don't assume without evidence.", "Đừng giả định mà không có bằng chứng.", "C1"),
    ("attribute", "/əˈtrɪbjuːt/", "verb", "to regard as caused by something", "quy cho", "She attributed success to hard work.", "Cô ấy quy thành công cho sự chăm chỉ.", "C1"),
    ("clarify", "/ˈklærɪfaɪ/", "verb", "to make something easier to understand", "làm rõ", "Please clarify your point.", "Vui lòng làm rõ quan điểm của bạn.", "C1"),
    ("constitute", "/ˈkɒnstɪtjuːt/", "verb", "to form or make up something", "cấu thành", "This constitutes a breach of contract.", "Điều này cấu thành vi phạm hợp đồng.", "C1"),
    ("derive", "/dɪˈraɪv/", "verb", "to obtain something from a source", "rút ra từ", "Many English words derive from Latin.", "Nhiều từ tiếng Anh bắt nguồn từ tiếng Latin.", "C1"),
    ("formulate", "/ˈfɔːrmjuleɪt/", "verb", "to create or express precisely", "định hình/đề ra", "Formulate a clear strategy.", "Đề ra chiến lược rõ ràng.", "C1"),
    ("integrate", "/ˈɪntɪɡreɪt/", "verb", "to combine parts into a whole", "tích hợp", "Integrate new ideas into the project.", "Tích hợp ý tưởng mới vào dự án.", "C1"),
    ("investigate", "/ɪnˈvestɪɡeɪt/", "verb", "to examine carefully to discover facts", "điều tra", "Police investigated the incident.", "Cảnh sát điều tra vụ việc.", "C1"),
    ("modify", "/ˈmɒdɪfaɪ/", "verb", "to make partial changes to something", "chỉnh sửa", "Modify the design based on feedback.", "Chỉnh sửa thiết kế dựa trên phản hồi.", "C1"),
    ("perceive", "/pərˈsiːv/", "verb", "to become aware of something", "nhận thức", "How do you perceive this problem?", "Bạn nhận thức vấn đề này như thế nào?", "C1"),
    ("predict", "/prɪˈdɪkt/", "verb", "to say what will happen in the future", "dự đoán", "Scientists predict rising temperatures.", "Các nhà khoa học dự đoán nhiệt độ tăng.", "C1"),
    ("prioritize", "/praɪˈɒrɪtaɪz/", "verb", "to deal with things in order of importance", "ưu tiên", "Prioritize your tasks each morning.", "Ưu tiên công việc mỗi buổi sáng.", "C1"),
    ("revise", "/rɪˈvaɪz/", "verb", "to change or correct something", "sửa đổi", "Revise the essay before submitting.", "Sửa đổi bài luận trước khi nộp.", "C1"),
    ("sustain", "/səˈsteɪn/", "verb", "to keep something going over time", "duy trì", "Sustain your focus during the exam.", "Duy trì sự tập trung trong suốt kỳ thi.", "C1"),
    ("verify", "/ˈverɪfaɪ/", "verb", "to check that something is true", "xác minh", "Verify the information before publishing.", "Xác minh thông tin trước khi xuất bản.", "C1"),
]


def run():
    created = 0
    skipped = 0
    for item in WORDS:
        text, phonetic, pos, def_en, def_vi, ex_en, ex_vi, level = item
        _, is_new = Word.objects.get_or_create(
            text=text,
            defaults={
                "phonetic": phonetic,
                "part_of_speech": pos,
                "definition_en": def_en,
                "definition_vi": def_vi,
                "example_en": ex_en,
                "example_vi": ex_vi,
                "level": level,
            },
        )
        if is_new:
            created += 1
        else:
            skipped += 1
    total = Word.objects.count()
    print(f"Hoàn thành: {created} từ mới, {skipped} bỏ qua.")
    print(f"Tổng từ vựng hiện tại: {total}")


run()
