"""Batch 2: thêm ~500 từ vựng mới vào DB."""
import os
import django

os.environ.setdefault("DJANGO_SETTINGS_MODULE", "config.settings.development")

import sys
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
django.setup()

from apps.vocabulary.models import Word

WORDS = [
    # A1 - Basic verbs
    ("swim", "/swɪm/", "verb", "to move through water", "bơi lội", "She swims every morning.", "Cô ấy bơi mỗi sáng.","A1"),
    ("jump", "/dʒʌmp/", "verb", "to push yourself off the ground", "nhảy", "The child jumped over the puddle.", "Đứa trẻ nhảy qua vũng nước.","A1"),
    ("run", "/rʌn/", "verb", "to move quickly on foot", "chạy", "He runs five kilometers a day.", "Anh ấy chạy năm km mỗi ngày.","A1"),
    ("walk", "/wɔːk/", "verb", "to move on foot at normal speed", "đi bộ", "We walked to the park.", "Chúng tôi đi bộ đến công viên.","A1"),
    ("sit", "/sɪt/", "verb", "to rest on a seat", "ngồi", "Please sit down.", "Vui lòng ngồi xuống.","A1"),
    ("stand", "/stænd/", "verb", "to be in an upright position", "đứng", "She stood by the window.", "Cô ấy đứng bên cửa sổ.","A1"),
    ("sleep", "/sliːp/", "verb", "to rest with eyes closed", "ngủ", "The baby is sleeping.", "Em bé đang ngủ.","A1"),
    ("wake", "/weɪk/", "verb", "to stop sleeping", "thức dậy", "I wake up at 6 AM.", "Tôi thức dậy lúc 6 giờ sáng.","A1"),
    ("cry", "/kraɪ/", "verb", "to shed tears", "khóc", "The baby is crying.", "Em bé đang khóc.","A1"),
    ("laugh", "/lɑːf/", "verb", "to make sounds showing amusement", "cười", "They laughed at the joke.", "Họ cười vì câu chuyện cười.","A1"),
    ("smile", "/smaɪl/", "verb", "to curl lips upward showing happiness", "mỉm cười", "She smiled warmly.", "Cô ấy mỉm cười ấm áp.","A1"),
    ("sing", "/sɪŋ/", "verb", "to make music with your voice", "hát", "He sings in the choir.", "Anh ấy hát trong ban hợp xướng.","A1"),
    ("dance", "/dɑːns/", "verb", "to move rhythmically to music", "nhảy múa", "They danced all night.", "Họ nhảy suốt đêm.","A1"),
    ("play", "/pleɪ/", "verb", "to engage in activity for fun", "chơi", "The kids play in the garden.", "Trẻ em chơi trong vườn.","A1"),
    ("cook", "/kʊk/", "verb", "to prepare food by heating", "nấu ăn", "She cooks dinner every evening.", "Cô ấy nấu bữa tối mỗi chiều.","A1"),
    ("eat", "/iːt/", "verb", "to put food in your mouth and swallow", "ăn", "We eat breakfast together.", "Chúng tôi ăn sáng cùng nhau.","A1"),
    ("drink", "/drɪŋk/", "verb", "to swallow liquid", "uống", "Drink plenty of water.", "Uống nhiều nước.","A1"),
    ("buy", "/baɪ/", "verb", "to get something by paying money", "mua", "I need to buy groceries.", "Tôi cần mua đồ tạp hóa.","A1"),
    ("sell", "/sel/", "verb", "to exchange something for money", "bán", "He sells vegetables at the market.", "Anh ấy bán rau ở chợ.","A1"),
    ("pay", "/peɪ/", "verb", "to give money for something", "trả tiền", "Did you pay the bill?", "Bạn đã trả hóa đơn chưa?","A1"),
    # A1 - Numbers & time
    ("morning", "/ˈmɔːrnɪŋ/", "noun", "the early part of the day", "buổi sáng", "Good morning!", "Chào buổi sáng!","A1"),
    ("afternoon", "/ˌɑːftərˈnuːn/", "noun", "the time between noon and evening", "buổi chiều", "See you this afternoon.", "Hẹn gặp chiều nay.","A1"),
    ("evening", "/ˈiːvnɪŋ/", "noun", "the time between afternoon and night", "buổi tối", "We met in the evening.", "Chúng tôi gặp nhau vào buổi tối.","A1"),
    ("night", "/naɪt/", "noun", "the dark time when people sleep", "ban đêm", "Good night!", "Chúc ngủ ngon!","A1"),
    ("today", "/təˈdeɪ/", "adverb", "on this day", "hôm nay", "What are you doing today?", "Hôm nay bạn làm gì?","A1"),
    ("tomorrow", "/təˈmɒrəʊ/", "adverb", "on the next day", "ngày mai", "See you tomorrow.", "Hẹn gặp ngày mai.","A1"),
    ("yesterday", "/ˈjestədeɪ/", "adverb", "on the day before today", "hôm qua", "I saw her yesterday.", "Tôi gặp cô ấy hôm qua.","A1"),
    ("week", "/wiːk/", "noun", "a period of seven days", "tuần", "See you next week.", "Hẹn gặp tuần sau.","A1"),
    ("month", "/mʌnθ/", "noun", "one of twelve parts of a year", "tháng", "She visits every month.", "Cô ấy thăm mỗi tháng.","A1"),
    ("season", "/ˈsiːzən/", "noun", "one of four parts of the year", "mùa", "Summer is my favourite season.", "Mùa hè là mùa yêu thích của tôi.","A1"),
    ("spring", "/sprɪŋ/", "noun", "the season after winter", "mùa xuân", "Flowers bloom in spring.", "Hoa nở vào mùa xuân.","A1"),
    ("summer", "/ˈsʌmər/", "noun", "the warmest season of the year", "mùa hè", "We go to the beach in summer.", "Chúng tôi ra biển vào mùa hè.","A1"),
    ("autumn", "/ˈɔːtəm/", "noun", "the season after summer", "mùa thu", "Leaves fall in autumn.", "Lá rụng vào mùa thu.","A1"),
    ("winter", "/ˈwɪntər/", "noun", "the coldest season of the year", "mùa đông", "It snows in winter.", "Trời tuyết vào mùa đông.","A1"),
    # A1 - Colors & adjectives
    ("white", "/waɪt/", "adjective", "the colour of snow", "trắng", "She wore a white dress.", "Cô ấy mặc váy trắng.","A1"),
    ("black", "/blæk/", "adjective", "the darkest colour", "đen", "He has black hair.", "Anh ấy có tóc đen.","A1"),
    ("red", "/red/", "adjective", "the colour of blood", "đỏ", "The roses are red.", "Những bông hồng màu đỏ.","A1"),
    ("blue", "/bluː/", "adjective", "the colour of the sky", "xanh lam", "The sky is blue.", "Bầu trời màu xanh.","A1"),
    ("yellow", "/ˈjeləʊ/", "adjective", "the colour of lemons", "vàng", "Bananas are yellow.", "Chuối màu vàng.","A1"),
    ("orange", "/ˈɒrɪndʒ/", "adjective", "the colour between red and yellow", "cam", "She wore an orange jacket.", "Cô ấy mặc áo khoác màu cam.","A1"),
    ("purple", "/ˈpɜːrpəl/", "adjective", "a colour between red and blue", "tím", "Lavender is purple.", "Hoa oải hương màu tím.","A1"),
    ("pink", "/pɪŋk/", "adjective", "a light red colour", "hồng", "The flowers are pink.", "Những bông hoa màu hồng.","A1"),
    ("brown", "/braʊn/", "adjective", "the colour of wood or soil", "nâu", "He has brown eyes.", "Anh ấy có mắt màu nâu.","A1"),
    ("grey", "/ɡreɪ/", "adjective", "a colour between black and white", "xám", "The sky looks grey today.", "Bầu trời trông xám hôm nay.","A1"),
    # A1 - Basic nouns
    ("door", "/dɔːr/", "noun", "a movable barrier to enter a room", "cánh cửa", "Please close the door.", "Vui lòng đóng cửa lại.","A1"),
    ("window", "/ˈwɪndəʊ/", "noun", "an opening in a wall with glass", "cửa sổ", "Open the window, please.", "Vui lòng mở cửa sổ.","A1"),
    ("floor", "/flɔːr/", "noun", "the surface you walk on", "sàn nhà", "The floor is clean.", "Sàn nhà sạch sẽ.","A1"),
    ("wall", "/wɔːl/", "noun", "a vertical structure that encloses a space", "bức tường", "Hang the picture on the wall.", "Treo tranh lên tường.","A1"),
    ("roof", "/ruːf/", "noun", "the covering on top of a building", "mái nhà", "The roof is leaking.", "Mái nhà đang bị rò rỉ.","A1"),
    ("bed", "/bed/", "noun", "furniture for sleeping", "giường ngủ", "She made her bed.", "Cô ấy dọn giường.","A1"),
    ("chair", "/tʃeər/", "noun", "a seat with a back for one person", "ghế", "Sit on the chair.", "Hãy ngồi vào ghế.","A1"),
    ("table", "/ˈteɪbəl/", "noun", "a flat surface supported by legs", "bàn", "Put the book on the table.", "Đặt sách lên bàn.","A1"),
    ("lamp", "/læmp/", "noun", "a device that produces light", "đèn", "Turn on the lamp.", "Bật đèn lên.","A1"),
    ("clock", "/klɒk/", "noun", "a device that shows the time", "đồng hồ treo tường", "The clock says 3 o'clock.", "Đồng hồ chỉ 3 giờ.","A1"),
    # A2 - Travel & places
    ("airport", "/ˈeəpɔːrt/", "noun", "a place where aeroplanes land and take off", "sân bay", "We arrived at the airport early.", "Chúng tôi đến sân bay sớm.","A2"),
    ("station", "/ˈsteɪʃən/", "noun", "a place where trains stop", "nhà ga", "The train station is downtown.", "Nhà ga xe lửa ở trung tâm thành phố.","A2"),
    ("hotel", "/həʊˈtel/", "noun", "a place where people pay to stay", "khách sạn", "We booked a hotel room.", "Chúng tôi đặt phòng khách sạn.","A2"),
    ("museum", "/mjuːˈziːəm/", "noun", "a building where historical objects are kept", "bảo tàng", "We visited the national museum.", "Chúng tôi thăm bảo tàng quốc gia.","A2"),
    ("library", "/ˈlaɪbrəri/", "noun", "a place where books are kept for borrowing", "thư viện", "She studies in the library.", "Cô ấy học trong thư viện.","A2"),
    ("restaurant", "/ˈrestərɒnt/", "noun", "a place where meals are served", "nhà hàng", "Let's eat at that restaurant.", "Hãy ăn ở nhà hàng đó.","A2"),
    ("hospital", "/ˈhɒspɪtəl/", "noun", "a place where sick people are treated", "bệnh viện", "He was taken to hospital.", "Anh ấy được đưa đến bệnh viện.","A2"),
    ("pharmacy", "/ˈfɑːrməsi/", "noun", "a shop where medicines are sold", "nhà thuốc", "Buy the medicine at the pharmacy.", "Mua thuốc ở nhà thuốc.","A2"),
    ("bank", "/bæŋk/", "noun", "a place that keeps money safe", "ngân hàng", "I need to go to the bank.", "Tôi cần đến ngân hàng.","A2"),
    ("post office", "/ˈpəʊst ˌɒfɪs/", "noun", "a place that handles mail", "bưu điện", "Send the letter at the post office.", "Gửi thư ở bưu điện.","A2"),
    ("supermarket", "/ˈsuːpərˌmɑːrkɪt/", "noun", "a large shop selling food and goods", "siêu thị", "We shop at the supermarket.", "Chúng tôi mua sắm ở siêu thị.","A2"),
    ("cinema", "/ˈsɪnəmə/", "noun", "a building where films are shown", "rạp chiếu phim", "Let's go to the cinema tonight.", "Tối nay đi xem phim nhé.","A2"),
    ("park", "/pɑːrk/", "noun", "a public green area in a city", "công viên", "Children play in the park.", "Trẻ em chơi trong công viên.","A2"),
    ("beach", "/biːtʃ/", "noun", "an area of sand by the sea", "bãi biển", "We relaxed on the beach.", "Chúng tôi thư giãn trên bãi biển.","A2"),
    ("mountain", "/ˈmaʊntɪn/", "noun", "a very high piece of land", "núi", "We climbed the mountain.", "Chúng tôi leo núi.","A2"),
    ("river", "/ˈrɪvər/", "noun", "a large natural flow of water", "sông", "The river flows through the city.", "Con sông chảy qua thành phố.","A2"),
    ("forest", "/ˈfɒrɪst/", "noun", "a large area covered with trees", "rừng", "Animals live in the forest.", "Động vật sống trong rừng.","A2"),
    ("island", "/ˈaɪlənd/", "noun", "land surrounded by water", "hòn đảo", "They visited a tropical island.", "Họ thăm một hòn đảo nhiệt đới.","A2"),
    ("village", "/ˈvɪlɪdʒ/", "noun", "a small group of houses in the country", "làng quê", "She grew up in a village.", "Cô ấy lớn lên ở làng quê.","A2"),
    ("city", "/ˈsɪti/", "noun", "a large and important town", "thành phố", "New York is a big city.", "New York là một thành phố lớn.","A2"),
    # A2 - Food & drink
    ("rice", "/raɪs/", "noun", "small white grains eaten as food", "cơm/gạo", "We eat rice with every meal.", "Chúng tôi ăn cơm với mỗi bữa ăn.","A2"),
    ("noodle", "/ˈnuːdəl/", "noun", "a thin strip of pasta", "mì/bún", "He ordered noodle soup.", "Anh ấy gọi soup mì.","A2"),
    ("soup", "/suːp/", "noun", "a liquid food made by boiling ingredients", "canh/súp", "She made vegetable soup.", "Cô ấy nấu súp rau củ.","A2"),
    ("salad", "/ˈsæləd/", "noun", "a cold dish of vegetables", "salad", "I had a salad for lunch.", "Tôi ăn salad vào bữa trưa.","A2"),
    ("sandwich", "/ˈsænwɪdʒ/", "noun", "two slices of bread with filling", "bánh mì sandwich", "He made a cheese sandwich.", "Anh ấy làm bánh mì kẹp phô mai.","A2"),
    ("pizza", "/ˈpiːtsə/", "noun", "a flat bread topped with cheese and tomato", "bánh pizza", "We ordered a pizza.", "Chúng tôi gọi một chiếc pizza.","A2"),
    ("burger", "/ˈbɜːrɡər/", "noun", "a round bread roll with meat inside", "hamburger", "He ate a burger for lunch.", "Anh ấy ăn hamburger vào bữa trưa.","A2"),
    ("cake", "/keɪk/", "noun", "a sweet baked food", "bánh ngọt", "She baked a birthday cake.", "Cô ấy nướng bánh sinh nhật.","A2"),
    ("cookie", "/ˈkʊki/", "noun", "a small flat sweet biscuit", "bánh quy", "He ate three cookies.", "Anh ấy ăn ba cái bánh quy.","A2"),
    ("ice cream", "/ˈaɪs kriːm/", "noun", "a frozen sweet dessert", "kem", "She loves chocolate ice cream.", "Cô ấy thích kem sô cô la.","A2"),
    ("juice", "/dʒuːs/", "noun", "liquid from fruit or vegetables", "nước ép", "Orange juice is healthy.", "Nước cam rất tốt cho sức khỏe.","A2"),
    ("coffee", "/ˈkɒfi/", "noun", "a hot drink made from roasted beans", "cà phê", "He drinks coffee every morning.", "Anh ấy uống cà phê mỗi sáng.","A2"),
    ("tea", "/tiː/", "noun", "a hot drink made from dried leaves", "trà", "She prefers green tea.", "Cô ấy thích trà xanh hơn.","A2"),
    ("milk", "/mɪlk/", "noun", "a white liquid produced by cows", "sữa", "Children need to drink milk.", "Trẻ em cần uống sữa.","A2"),
    ("butter", "/ˈbʌtər/", "noun", "a soft yellow fat made from cream", "bơ", "Spread butter on the bread.", "Phết bơ lên bánh mì.","A2"),
    ("cheese", "/tʃiːz/", "noun", "a solid food made from milk", "phô mai", "She added cheese to the pasta.", "Cô ấy cho phô mai vào mì ống.","A2"),
    ("egg", "/eɡ/", "noun", "an oval object laid by a bird", "trứng", "She fried two eggs.", "Cô ấy chiên hai quả trứng.","A2"),
    ("chicken", "/ˈtʃɪkɪn/", "noun", "meat from a hen", "thịt gà", "We had chicken for dinner.", "Chúng tôi ăn gà vào bữa tối.","A2"),
    ("fish", "/fɪʃ/", "noun", "an aquatic animal eaten as food", "cá", "She eats fish twice a week.", "Cô ấy ăn cá hai lần một tuần.","A2"),
    ("beef", "/biːf/", "noun", "meat from a cow", "thịt bò", "He ordered beef steak.", "Anh ấy gọi bít tết bò.","A2"),
    ("pork", "/pɔːrk/", "noun", "meat from a pig", "thịt lợn", "Pork is common in Asian cuisine.", "Thịt lợn phổ biến trong ẩm thực châu Á.","A2"),
    ("vegetable", "/ˈvedʒtəbəl/", "noun", "a plant grown for food", "rau củ", "Eat more vegetables every day.", "Ăn nhiều rau củ mỗi ngày.","A2"),
    ("fruit", "/fruːt/", "noun", "the sweet product of a plant", "trái cây", "Fresh fruit is healthy.", "Trái cây tươi rất tốt cho sức khỏe.","A2"),
    ("apple", "/ˈæpəl/", "noun", "a round fruit that is red or green", "táo", "An apple a day keeps the doctor away.", "Một quả táo mỗi ngày giúp tránh xa bác sĩ.","A2"),
    ("banana", "/bəˈnɑːnə/", "noun", "a yellow curved fruit", "chuối", "Monkeys love bananas.", "Khỉ thích chuối.","A2"),
    ("orange", "/ˈɒrɪndʒ/", "noun", "a round orange citrus fruit", "quả cam", "She squeezed fresh oranges.", "Cô ấy vắt cam tươi.","A2"),
    ("tomato", "/təˈmɑːtəʊ/", "noun", "a red fruit used as a vegetable", "cà chua", "Add tomatoes to the salad.", "Thêm cà chua vào salad.","A2"),
    ("potato", "/pəˈteɪtəʊ/", "noun", "a starchy underground vegetable", "khoai tây", "French fries are made from potatoes.", "Khoai tây chiên được làm từ khoai tây.","A2"),
    ("onion", "/ˈʌnjən/", "noun", "a round vegetable with layers", "hành tây", "She chopped the onion.", "Cô ấy thái hành tây.","A2"),
    ("garlic", "/ˈɡɑːrlɪk/", "noun", "a plant with a strong smell used in cooking", "tỏi", "Add garlic to the sauce.", "Thêm tỏi vào nước sốt.","A2"),
    ("sugar", "/ˈʃʊɡər/", "noun", "a sweet substance used in food", "đường", "Don't add too much sugar.", "Đừng thêm quá nhiều đường.","A2"),
    ("salt", "/sɔːlt/", "noun", "a white substance used to flavour food", "muối", "The soup needs more salt.", "Canh cần thêm muối.","A2"),
    ("oil", "/ɔɪl/", "noun", "a liquid fat used in cooking", "dầu ăn", "Heat the oil in the pan.", "Đun nóng dầu trong chảo.","A2"),
    # B1 - Emotions & personality
    ("anxious", "/ˈæŋkʃəs/", "adjective", "worried and nervous", "lo lắng", "She felt anxious before the exam.", "Cô ấy cảm thấy lo lắng trước kỳ thi.","B1"),
    ("confident", "/ˈkɒnfɪdənt/", "adjective", "feeling sure about yourself", "tự tin", "He was confident in his abilities.", "Anh ấy tự tin vào khả năng của mình.","B1"),
    ("curious", "/ˈkjʊəriəs/", "adjective", "eager to know or learn", "tò mò", "Children are naturally curious.", "Trẻ em vốn tò mò.","B1"),
    ("disappointed", "/ˌdɪsəˈpɔɪntɪd/", "adjective", "sad because something did not happen", "thất vọng", "She was disappointed with her result.", "Cô ấy thất vọng với kết quả của mình.","B1"),
    ("embarrassed", "/ɪmˈbærəst/", "adjective", "feeling ashamed or uncomfortable", "xấu hổ", "He felt embarrassed by his mistake.", "Anh ấy cảm thấy xấu hổ vì lỗi của mình.","B1"),
    ("excited", "/ɪkˈsaɪtɪd/", "adjective", "very happy and enthusiastic", "hào hứng", "She was excited about the trip.", "Cô ấy hào hứng về chuyến đi.","B1"),
    ("frightened", "/ˈfraɪtənd/", "adjective", "afraid or scared", "sợ hãi", "The child was frightened by the storm.", "Đứa trẻ sợ hãi vì bão.","B1"),
    ("jealous", "/ˈdʒeləs/", "adjective", "feeling envious of someone", "ghen tuông", "She felt jealous of her sister's success.", "Cô ấy ghen tuông vì thành công của chị.","B1"),
    ("lonely", "/ˈləʊnli/", "adjective", "unhappy because you are alone", "cô đơn", "He felt lonely in the new city.", "Anh ấy cảm thấy cô đơn ở thành phố mới.","B1"),
    ("proud", "/praʊd/", "adjective", "feeling pleased about an achievement", "tự hào", "She was proud of her children.", "Cô ấy tự hào về những đứa con của mình.","B1"),
    ("relieved", "/rɪˈliːvd/", "adjective", "feeling better after worry", "nhẹ nhõm", "He was relieved to hear the news.", "Anh ấy nhẹ nhõm khi nghe tin.","B1"),
    ("nervous", "/ˈnɜːrvəs/", "adjective", "slightly anxious or afraid", "căng thẳng", "She was nervous before the presentation.", "Cô ấy căng thẳng trước buổi thuyết trình.","B1"),
    ("patient", "/ˈpeɪʃənt/", "adjective", "able to wait calmly", "kiên nhẫn", "A good teacher must be patient.", "Giáo viên giỏi phải kiên nhẫn.","B1"),
    ("generous", "/ˈdʒenərəs/", "adjective", "willing to give more than expected", "rộng lượng", "She is very generous with her time.", "Cô ấy rất rộng lượng với thời gian của mình.","B1"),
    ("honest", "/ˈɒnɪst/", "adjective", "truthful and not deceiving", "thành thật", "He is an honest person.", "Anh ấy là người thành thật.","B1"),
    ("lazy", "/ˈleɪzi/", "adjective", "not willing to work", "lười biếng", "Don't be lazy; get to work.", "Đừng lười biếng; hãy làm việc đi.","B1"),
    ("brave", "/breɪv/", "adjective", "showing no fear", "dũng cảm", "The firefighter was very brave.", "Người lính cứu hỏa rất dũng cảm.","B1"),
    ("shy", "/ʃaɪ/", "adjective", "nervous or embarrassed with people", "nhút nhát", "She is shy around strangers.", "Cô ấy nhút nhát khi ở cạnh người lạ.","B1"),
    ("stubborn", "/ˈstʌbərn/", "adjective", "unwilling to change your mind", "bướng bỉnh", "He was too stubborn to apologize.", "Anh ấy quá bướng bỉnh để xin lỗi.","B1"),
    ("polite", "/pəˈlaɪt/", "adjective", "having good manners", "lịch sự", "Always be polite to guests.", "Luôn lịch sự với khách.","B1"),
    # B1 - Health & body
    ("headache", "/ˈhedeɪk/", "noun", "a pain in the head", "đau đầu", "I have a terrible headache.", "Tôi bị đau đầu khủng khiếp.","B1"),
    ("fever", "/ˈfiːvər/", "noun", "higher than normal body temperature", "sốt", "She has a high fever.", "Cô ấy bị sốt cao.","B1"),
    ("cough", "/kɒf/", "noun", "a sudden noise when air is pushed from lungs", "ho", "He has a bad cough.", "Anh ấy bị ho nặng.","B1"),
    ("cold", "/kəʊld/", "noun", "a mild illness with a runny nose", "cảm lạnh", "She caught a cold.", "Cô ấy bị cảm lạnh.","B1"),
    ("allergy", "/ˈælədʒi/", "noun", "a bad reaction to a substance", "dị ứng", "He has a peanut allergy.", "Anh ấy bị dị ứng với đậu phộng.","B1"),
    ("injury", "/ˈɪndʒəri/", "noun", "damage to your body", "chấn thương", "She suffered a knee injury.", "Cô ấy bị chấn thương đầu gối.","B1"),
    ("medicine", "/ˈmedɪsɪn/", "noun", "a substance used to treat illness", "thuốc", "Take this medicine twice a day.", "Uống thuốc này hai lần mỗi ngày.","B1"),
    ("exercise", "/ˈeksərsaɪz/", "noun", "physical activity to stay healthy", "tập thể dục", "Regular exercise is important.", "Tập thể dục đều đặn rất quan trọng.","B1"),
    ("diet", "/ˈdaɪət/", "noun", "the food you regularly eat", "chế độ ăn uống", "A balanced diet keeps you healthy.", "Chế độ ăn uống cân bằng giúp bạn khỏe mạnh.","B1"),
    ("weight", "/weɪt/", "noun", "how heavy someone or something is", "cân nặng", "She lost weight after exercising.", "Cô ấy giảm cân sau khi tập thể dục.","B1"),
    ("blood", "/blʌd/", "noun", "the red liquid in your body", "máu", "Blood carries oxygen around the body.", "Máu mang oxy đi khắp cơ thể.","B1"),
    ("bone", "/bəʊn/", "noun", "a hard white structure in your body", "xương", "He broke a bone in his arm.", "Anh ấy bị gãy xương ở cánh tay.","B1"),
    ("muscle", "/ˈmʌsəl/", "noun", "tissue in your body that helps you move", "cơ bắp", "Strong muscles protect your joints.", "Cơ bắp mạnh bảo vệ khớp của bạn.","B1"),
    ("skin", "/skɪn/", "noun", "the outer layer of a person's body", "da", "Protect your skin from the sun.", "Bảo vệ da khỏi nắng.","B1"),
    ("heart", "/hɑːrt/", "noun", "the organ that pumps blood", "tim", "Exercise strengthens the heart.", "Tập thể dục tăng cường sức mạnh cho tim.","B1"),
    # B1 - Work & career
    ("apply", "/əˈplaɪ/", "verb", "to formally request a job", "nộp đơn ứng tuyển", "She applied for the manager position.", "Cô ấy nộp đơn ứng tuyển vị trí quản lý.","B1"),
    ("interview", "/ˈɪntərvjuː/", "noun", "a formal meeting to assess someone", "phỏng vấn", "He has a job interview tomorrow.", "Anh ấy có buổi phỏng vấn việc làm ngày mai.","B1"),
    ("salary", "/ˈsæləri/", "noun", "regular payment for work", "lương", "Her salary increased this year.", "Lương của cô ấy tăng năm nay.","B1"),
    ("promotion", "/prəˈməʊʃən/", "noun", "moving to a higher job position", "thăng chức", "He received a promotion.", "Anh ấy được thăng chức.","B1"),
    ("resign", "/rɪˈzaɪn/", "verb", "to voluntarily leave a job", "từ chức", "She resigned from her position.", "Cô ấy từ chức.","B1"),
    ("retire", "/rɪˈtaɪər/", "verb", "to stop working at the end of career", "về hưu", "He plans to retire at 60.", "Anh ấy dự định về hưu năm 60 tuổi.","B1"),
    ("colleague", "/ˈkɒliːɡ/", "noun", "someone you work with", "đồng nghiệp", "She gets along well with her colleagues.", "Cô ấy hòa thuận tốt với đồng nghiệp.","B1"),
    ("deadline", "/ˈdedlaɪn/", "noun", "a time by which you must finish something", "hạn chót", "We must meet the deadline.", "Chúng tôi phải hoàn thành trước hạn chót.","B1"),
    ("overtime", "/ˈəʊvərtaɪm/", "noun", "time worked beyond normal hours", "làm thêm giờ", "He worked overtime to finish the project.", "Anh ấy làm thêm giờ để hoàn thành dự án.","B1"),
    ("meeting", "/ˈmiːtɪŋ/", "noun", "a gathering to discuss something", "cuộc họp", "We have a team meeting at 9.", "Chúng tôi có cuộc họp nhóm lúc 9 giờ.","B1"),
    # B2 - Academic & education
    ("analyze", "/ˈænəlaɪz/", "verb", "to examine something carefully", "phân tích", "She analyzed the data thoroughly.", "Cô ấy phân tích dữ liệu một cách kỹ lưỡng.","B2"),
    ("evaluate", "/ɪˈvæljueɪt/", "verb", "to judge the value or quality of something", "đánh giá", "We need to evaluate the results.", "Chúng ta cần đánh giá kết quả.","B2"),
    ("hypothesis", "/haɪˈpɒθɪsɪs/", "noun", "a proposed explanation to be tested", "giả thuyết", "The scientist tested his hypothesis.", "Nhà khoa học kiểm tra giả thuyết của mình.","B2"),
    ("conclude", "/kənˈkluːd/", "verb", "to reach a decision or opinion", "kết luận", "He concluded that the theory was correct.", "Anh ấy kết luận rằng lý thuyết là đúng.","B2"),
    ("evidence", "/ˈevɪdəns/", "noun", "facts that prove something is true", "bằng chứng", "There is strong evidence for this.", "Có bằng chứng mạnh mẽ cho điều này.","B2"),
    ("argument", "/ˈɑːrɡjumənt/", "noun", "a reason given to support a view", "lập luận", "Her argument was very convincing.", "Lập luận của cô ấy rất thuyết phục.","B2"),
    ("perspective", "/pərˈspektɪv/", "noun", "a particular way of viewing things", "quan điểm", "Try to see things from a different perspective.", "Hãy thử nhìn mọi thứ từ một quan điểm khác.","B2"),
    ("interpret", "/ɪnˈtɜːrprɪt/", "verb", "to explain the meaning of something", "diễn giải", "It is hard to interpret the data.", "Khó để diễn giải dữ liệu.","B2"),
    ("theory", "/ˈθɪəri/", "noun", "a set of ideas to explain something", "lý thuyết", "Darwin's theory changed science.", "Lý thuyết của Darwin đã thay đổi khoa học.","B2"),
    ("concept", "/ˈkɒnsept/", "noun", "an abstract idea", "khái niệm", "The concept is easy to understand.", "Khái niệm này dễ hiểu.","B2"),
    ("principle", "/ˈprɪnsɪpəl/", "noun", "a basic rule or belief", "nguyên tắc", "Follow the basic principles.", "Hãy tuân theo các nguyên tắc cơ bản.","B2"),
    ("significant", "/sɪɡˈnɪfɪkənt/", "adjective", "important or large enough to notice", "đáng kể", "There was a significant improvement.", "Có sự cải thiện đáng kể.","B2"),
    ("methodology", "/ˌmeθəˈdɒlədʒi/", "noun", "a system of methods used in a field", "phương pháp luận", "The research methodology was sound.", "Phương pháp nghiên cứu rất vững chắc.","B2"),
    ("criteria", "/kraɪˈtɪəriə/", "noun", "standards used for judging something", "tiêu chí", "Meet all the selection criteria.", "Đáp ứng tất cả các tiêu chí lựa chọn.","B2"),
    ("outcome", "/ˈaʊtkʌm/", "noun", "the result of an action", "kết quả", "The outcome was better than expected.", "Kết quả tốt hơn dự kiến.","B2"),
    # B2 - Technology
    ("software", "/ˈsɒftweər/", "noun", "programs used by a computer", "phần mềm", "They updated the software.", "Họ cập nhật phần mềm.","B2"),
    ("hardware", "/ˈhɑːrdweər/", "noun", "the physical parts of a computer", "phần cứng", "Check the hardware components.", "Kiểm tra các thành phần phần cứng.","B2"),
    ("database", "/ˈdeɪtəbeɪs/", "noun", "a structured collection of data", "cơ sở dữ liệu", "The database stores all records.", "Cơ sở dữ liệu lưu trữ tất cả hồ sơ.","B2"),
    ("network", "/ˈnetwɜːrk/", "noun", "a system of connected computers", "mạng lưới", "The office network is down.", "Mạng văn phòng bị ngừng hoạt động.","B2"),
    ("encryption", "/ɪnˈkrɪpʃən/", "noun", "converting data to a coded form", "mã hóa", "Use encryption to protect data.", "Sử dụng mã hóa để bảo vệ dữ liệu.","B2"),
    ("algorithm", "/ˈælɡərɪðəm/", "noun", "a step-by-step problem-solving process", "thuật toán", "The algorithm finds the shortest path.", "Thuật toán tìm đường đi ngắn nhất.","B2"),
    ("interface", "/ˈɪntərfeɪs/", "noun", "a point where two systems meet", "giao diện", "The user interface is intuitive.", "Giao diện người dùng rất trực quan.","B2"),
    ("bandwidth", "/ˈbændwɪdθ/", "noun", "the capacity of a network connection", "băng thông", "We need more bandwidth.", "Chúng ta cần nhiều băng thông hơn.","B2"),
    ("server", "/ˈsɜːrvər/", "noun", "a computer that provides services to others", "máy chủ", "The server crashed during peak hours.", "Máy chủ bị sập trong giờ cao điểm.","B2"),
    ("cloud", "/klaʊd/", "noun", "remote servers accessed via the internet", "điện toán đám mây", "Data is stored in the cloud.", "Dữ liệu được lưu trữ trên đám mây.","B2"),
    # C1 - Advanced vocabulary
    ("ambiguous", "/æmˈbɪɡjuəs/", "adjective", "having more than one possible meaning", "mơ hồ", "His answer was deliberately ambiguous.", "Câu trả lời của anh ấy cố tình mơ hồ.","C1"),
    ("contemplate", "/ˈkɒntəmpleɪt/", "verb", "to think deeply about something", "suy ngẫm", "She contemplated the difficult decision.", "Cô ấy suy ngẫm về quyết định khó khăn.","C1"),
    ("elaborate", "/ɪˈlæbərət/", "adjective", "complex and detailed", "tỉ mỉ", "She gave an elaborate explanation.", "Cô ấy giải thích tỉ mỉ.","C1"),
    ("facilitate", "/fəˈsɪlɪteɪt/", "verb", "to make something easier to do", "tạo điều kiện", "Technology facilitates communication.", "Công nghệ tạo điều kiện cho giao tiếp.","C1"),
    ("fundamental", "/ˌfʌndəˈmentəl/", "adjective", "forming a necessary base", "cơ bản", "Respect is fundamental to relationships.", "Tôn trọng là điều cơ bản trong các mối quan hệ.","C1"),
    ("inevitable", "/ɪnˈevɪtəbəl/", "adjective", "certain to happen and cannot be avoided", "không thể tránh khỏi", "Change is inevitable.", "Sự thay đổi là không thể tránh khỏi.","C1"),
    ("justify", "/ˈdʒʌstɪfaɪ/", "verb", "to give reasons to prove something right", "biện minh", "Can you justify your decision?", "Bạn có thể biện minh cho quyết định của mình không?","C1"),
    ("manipulate", "/məˈnɪpjuleɪt/", "verb", "to control in a clever or dishonest way", "thao túng", "He tried to manipulate the situation.", "Anh ấy cố gắng thao túng tình huống.","C1"),
    ("obscure", "/əbˈskjʊər/", "adjective", "not well known or hard to understand", "tối nghĩa", "The poet used obscure references.", "Nhà thơ sử dụng những ám chỉ tối nghĩa.","C1"),
    ("paradox", "/ˈpærədɒks/", "noun", "a statement that seems contradictory but is true", "nghịch lý", "It's a paradox that the more you learn, the less you know.", "Đây là nghịch lý: càng học nhiều càng thấy mình biết ít.","C1"),
    ("profound", "/prəˈfaʊnd/", "adjective", "very deep and showing great understanding", "sâu sắc", "She had a profound insight.", "Cô ấy có cái nhìn sâu sắc.","C1"),
    ("reluctant", "/rɪˈlʌktənt/", "adjective", "unwilling to do something", "miễn cưỡng", "He was reluctant to admit his mistake.", "Anh ấy miễn cưỡng thừa nhận lỗi của mình.","C1"),
    ("substantial", "/səbˈstænʃəl/", "adjective", "large in size, value or importance", "đáng kể", "There was a substantial improvement.", "Có sự cải thiện đáng kể.","C1"),
    ("transparent", "/trænsˈpærənt/", "adjective", "easy to see through or understand", "minh bạch", "The process should be transparent.", "Quy trình nên minh bạch.","C1"),
    ("vulnerability", "/ˌvʌlnərəˈbɪlɪti/", "noun", "being open to harm or attack", "tính dễ bị tổn thương", "The system's vulnerability was exposed.", "Lỗ hổng của hệ thống bị phát hiện.","C1"),
    # TOEIC - Business & professional
    ("invoice", "/ˈɪnvɔɪs/", "noun", "a bill listing goods or services", "hóa đơn", "Please send the invoice by email.", "Vui lòng gửi hóa đơn qua email.","TOEIC"),
    ("receipt", "/rɪˈsiːt/", "noun", "a document showing payment was made", "biên lai", "Keep your receipt for returns.", "Giữ biên lai để đổi trả hàng.","TOEIC"),
    ("budget", "/ˈbʌdʒɪt/", "noun", "an estimate of income and spending", "ngân sách", "We need to stay within budget.", "Chúng ta cần ở trong ngân sách.","TOEIC"),
    ("expenditure", "/ɪkˈspendɪtʃər/", "noun", "the total amount of money spent", "chi phí", "Reduce unnecessary expenditure.", "Giảm chi phí không cần thiết.","TOEIC"),
    ("revenue", "/ˈrevɪnjuː/", "noun", "income generated by a business", "doanh thu", "Revenue increased by 20%.", "Doanh thu tăng 20%.","TOEIC"),
    ("profit", "/ˈprɒfɪt/", "noun", "money gained after costs are deducted", "lợi nhuận", "The company made a huge profit.", "Công ty đạt lợi nhuận lớn.","TOEIC"),
    ("loss", "/lɒs/", "noun", "money spent more than earned", "thua lỗ", "The company reported a loss.", "Công ty báo cáo thua lỗ.","TOEIC"),
    ("asset", "/ˈæset/", "noun", "something of value owned by a company", "tài sản", "List all your assets.", "Liệt kê tất cả tài sản của bạn.","TOEIC"),
    ("liability", "/ˌlaɪəˈbɪlɪti/", "noun", "money owed by a company", "nợ phải trả", "Reduce your financial liabilities.", "Giảm nợ tài chính của bạn.","TOEIC"),
    ("shareholder", "/ˈʃeərˌhəʊldər/", "noun", "a person who owns shares in a company", "cổ đông", "Shareholders voted at the meeting.", "Các cổ đông đã bỏ phiếu tại cuộc họp.","TOEIC"),
    ("merger", "/ˈmɜːrdʒər/", "noun", "combining two companies into one", "sáp nhập", "The merger created a new giant.", "Vụ sáp nhập tạo ra một tập đoàn mới.","TOEIC"),
    ("acquisition", "/ˌækwɪˈzɪʃən/", "noun", "buying another company", "mua lại", "The acquisition boosted their market share.", "Việc mua lại đã tăng thị phần của họ.","TOEIC"),
    ("franchise", "/ˈfræntʃaɪz/", "noun", "a licence to sell a company's products", "nhượng quyền", "She owns a restaurant franchise.", "Cô ấy sở hữu nhượng quyền nhà hàng.","TOEIC"),
    ("contract", "/ˈkɒntrækt/", "noun", "a formal legal agreement", "hợp đồng", "Sign the contract before starting.", "Ký hợp đồng trước khi bắt đầu.","TOEIC"),
    ("negotiation", "/nɪˌɡəʊʃiˈeɪʃən/", "noun", "discussion to reach an agreement", "đàm phán", "Negotiations are still ongoing.", "Các cuộc đàm phán vẫn đang diễn ra.","TOEIC"),
    ("proposal", "/prəˈpəʊzəl/", "noun", "a formal suggestion", "đề xuất", "Submit your proposal by Friday.", "Nộp đề xuất của bạn trước thứ Sáu.","TOEIC"),
    ("agenda", "/əˈdʒendə/", "noun", "a list of items to be discussed", "chương trình nghị sự", "What is on today's agenda?", "Hôm nay có gì trong chương trình?","TOEIC"),
    ("minutes", "/ˈmɪnɪts/", "noun", "the official written record of a meeting", "biên bản họp", "Who will take the minutes?", "Ai sẽ ghi biên bản họp?","TOEIC"),
    ("headquarters", "/ˈhedˌkwɔːrtərz/", "noun", "the main office of a company", "trụ sở chính", "The HQ is in Singapore.", "Trụ sở chính ở Singapore.","TOEIC"),
    ("subsidiary", "/səbˈsɪdiəri/", "noun", "a company owned by a larger company", "công ty con", "They opened a new subsidiary.", "Họ mở một công ty con mới.","TOEIC"),
    ("supply chain", "/ˈsʌplaɪ tʃeɪn/", "noun", "the network of suppliers and producers", "chuỗi cung ứng", "Disruptions affected the supply chain.", "Sự gián đoạn ảnh hưởng đến chuỗi cung ứng.","TOEIC"),
    ("logistics", "/ləˈdʒɪstɪks/", "noun", "the planning of moving goods", "hậu cần", "Good logistics reduces costs.", "Hậu cần tốt giúp giảm chi phí.","TOEIC"),
    ("inventory", "/ˈɪnvəntri/", "noun", "a complete list of goods in stock", "hàng tồn kho", "Check the inventory levels.", "Kiểm tra mức hàng tồn kho.","TOEIC"),
    ("wholesale", "/ˈhəʊlseɪl/", "noun", "selling goods in large quantities", "bán sỉ", "They sell at wholesale prices.", "Họ bán theo giá sỉ.","TOEIC"),
    ("retail", "/ˈriːteɪl/", "noun", "selling goods to consumers directly", "bán lẻ", "The retail sector is growing.", "Lĩnh vực bán lẻ đang phát triển.","TOEIC"),
    ("consumer", "/kənˈsjuːmər/", "noun", "a person who buys goods or services", "người tiêu dùng", "Consumers demand better quality.", "Người tiêu dùng đòi hỏi chất lượng tốt hơn.","TOEIC"),
    ("demand", "/dɪˈmɑːnd/", "noun", "desire for a product or service", "nhu cầu", "Demand for electric cars is rising.", "Nhu cầu về xe điện đang tăng.","TOEIC"),
    ("supply", "/səˈplaɪ/", "noun", "the amount of goods available", "nguồn cung", "Supply cannot meet demand.", "Nguồn cung không đáp ứng được nhu cầu.","TOEIC"),
    ("competition", "/ˌkɒmpɪˈtɪʃən/", "noun", "rivalry between businesses", "cạnh tranh", "Competition keeps prices low.", "Cạnh tranh giữ giá thấp.","TOEIC"),
    ("market share", "/ˈmɑːrkɪt ʃeər/", "noun", "percentage of sales in a market", "thị phần", "They increased their market share.", "Họ đã tăng thị phần.","TOEIC"),
    ("launch", "/lɔːntʃ/", "verb", "to introduce a new product to market", "ra mắt", "They launched the product in Asia.", "Họ ra mắt sản phẩm ở châu Á.","TOEIC"),
    ("strategy", "/ˈstrætədʒi/", "noun", "a plan to achieve a goal", "chiến lược", "We need a new marketing strategy.", "Chúng ta cần chiến lược marketing mới.","TOEIC"),
    ("benchmark", "/ˈbentʃmɑːrk/", "noun", "a standard to measure against", "tiêu chuẩn đối chiếu", "Set a benchmark for performance.", "Đặt tiêu chuẩn đối chiếu cho hiệu suất.","TOEIC"),
    ("forecast", "/ˈfɔːrkɑːst/", "noun", "a prediction about future events", "dự báo", "The sales forecast looks positive.", "Dự báo doanh số có vẻ tích cực.","TOEIC"),
    # B2 - Environment
    ("pollution", "/pəˈluːʃən/", "noun", "contamination of the environment", "ô nhiễm", "Air pollution is a global problem.", "Ô nhiễm không khí là vấn đề toàn cầu.","B2"),
    ("climate", "/ˈklaɪmɪt/", "noun", "the long-term weather of a region", "khí hậu", "Climate change affects everyone.", "Biến đổi khí hậu ảnh hưởng đến mọi người.","B2"),
    ("sustainable", "/səˈsteɪnəbəl/", "adjective", "able to be maintained without harming the environment", "bền vững", "We need sustainable development.", "Chúng ta cần phát triển bền vững.","B2"),
    ("renewable", "/rɪˈnjuːəbəl/", "adjective", "able to be replenished naturally", "có thể tái tạo", "Solar is a renewable energy source.", "Năng lượng mặt trời là nguồn năng lượng tái tạo.","B2"),
    ("emission", "/ɪˈmɪʃən/", "noun", "gases released into the atmosphere", "khí thải", "Reduce carbon emissions.", "Giảm khí thải carbon.","B2"),
    ("biodiversity", "/ˌbaɪəʊdaɪˈvɜːrsɪti/", "noun", "variety of life in an area", "đa dạng sinh học", "Protect biodiversity in rainforests.", "Bảo vệ đa dạng sinh học trong rừng nhiệt đới.","B2"),
    ("ecosystem", "/ˈiːkəʊˌsɪstəm/", "noun", "all organisms living in an area together", "hệ sinh thái", "Plastic harms the ocean ecosystem.", "Nhựa gây hại cho hệ sinh thái đại dương.","B2"),
    ("deforestation", "/ˌdiːˌfɒrɪˈsteɪʃən/", "noun", "clearing forests on a large scale", "phá rừng", "Deforestation destroys habitats.", "Phá rừng phá hủy môi trường sống.","B2"),
    ("conservation", "/ˌkɒnsəˈveɪʃən/", "noun", "protecting nature from harm", "bảo tồn", "Wildlife conservation is important.", "Bảo tồn động vật hoang dã rất quan trọng.","B2"),
    ("greenhouse", "/ˈɡriːnhaʊs/", "noun", "a structure for growing plants", "nhà kính", "Greenhouse gases trap heat.", "Khí nhà kính giữ nhiệt.","B2"),
    # B1 - Sports & hobbies
    ("tournament", "/ˈtʊərn əmənt/", "noun", "a competition with many matches", "giải đấu", "He won the tennis tournament.", "Anh ấy thắng giải đấu tennis.","B1"),
    ("champion", "/ˈtʃæmpiən/", "noun", "the winner of a competition", "vô địch", "She became the national champion.", "Cô ấy trở thành nhà vô địch quốc gia.","B1"),
    ("coach", "/kəʊtʃ/", "noun", "someone who trains a sports team", "huấn luyện viên", "The coach motivated the team.", "Huấn luyện viên khích lệ đội.","B1"),
    ("referee", "/ˌrefəˈriː/", "noun", "the official who enforces rules in sports", "trọng tài", "The referee blew the whistle.", "Trọng tài thổi còi.","B1"),
    ("stadium", "/ˈsteɪdiəm/", "noun", "a large sports ground with seats", "sân vận động", "The stadium holds 80,000 fans.", "Sân vận động chứa 80.000 người hâm mộ.","B1"),
    ("athlete", "/ˈæθliːt/", "noun", "a person who trains in sports", "vận động viên", "Olympic athletes train hard daily.", "Các vận động viên Olympic tập luyện chăm chỉ mỗi ngày.","B1"),
    ("medal", "/ˈmedəl/", "noun", "an award given for winning", "huy chương", "She won a gold medal.", "Cô ấy giành huy chương vàng.","B1"),
    ("score", "/skɔːr/", "noun", "the number of points in a game", "tỷ số", "What is the final score?", "Tỷ số cuối cùng là bao nhiêu?","B1"),
    ("defeat", "/dɪˈfiːt/", "verb", "to beat someone in a competition", "đánh bại", "They defeated the rival team.", "Họ đánh bại đội đối thủ.","B1"),
    ("victory", "/ˈvɪktəri/", "noun", "a win in a competition", "chiến thắng", "The victory was celebrated.", "Chiến thắng được ăn mừng.","B1"),
]


def run():
    created = 0
    skipped = 0
    for item in WORDS:
        text, phonetic, pos, def_en, def_vi, ex_en, ex_vi, level = item
        _, is_new = Word.objects.get_or_create(
            text=text,
            defaults={
                "phonetic": phonetic,
                "part_of_speech": pos,
                "definition_en": def_en,
                "definition_vi": def_vi,
                "example_en": ex_en,
                "example_vi": ex_vi,
                "level": level,
            },
        )
        if is_new:
            created += 1
        else:
            skipped += 1
    total = Word.objects.count()
    print(f"Hoàn thành: {created} từ mới, {skipped} bỏ qua (đã tồn tại).")
    print(f"Tổng từ vựng hiện tại: {total}")


run()
