"""Batch 5: ~550 từ để đạt 2000."""
import os, sys
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
os.environ.setdefault("DJANGO_SETTINGS_MODULE", "config.settings.development")
import django; django.setup()
from apps.vocabulary.models import Word

WORDS = [
    # A2 - body parts
    ("head", "/hed/", "noun", "the top part of your body", "đầu", "She nodded her head.", "Cô ấy gật đầu.", "A2"),
    ("face", "/feɪs/", "noun", "the front part of the head", "khuôn mặt", "He washed his face.", "Anh ấy rửa mặt.", "A2"),
    ("eye", "/aɪ/", "noun", "the organ for seeing", "mắt", "She has blue eyes.", "Cô ấy có đôi mắt xanh.", "A2"),
    ("ear", "/ɪər/", "noun", "the organ for hearing", "tai", "The music is loud in my ears.", "Âm nhạc to trong tai tôi.", "A2"),
    ("nose", "/nəʊz/", "noun", "the part of the face for breathing and smelling", "mũi", "She has a runny nose.", "Cô ấy bị sổ mũi.", "A2"),
    ("mouth", "/maʊθ/", "noun", "the opening for eating and speaking", "miệng", "Open your mouth wide.", "Há miệng ra.", "A2"),
    ("lip", "/lɪp/", "noun", "one of the two edges of the mouth", "môi", "She bit her lip nervously.", "Cô ấy cắn môi lo lắng.", "A2"),
    ("tooth", "/tuːθ/", "noun", "a hard white structure in the mouth", "răng", "Brush your teeth twice a day.", "Đánh răng hai lần mỗi ngày.", "A2"),
    ("tongue", "/tʌŋ/", "noun", "the muscle in the mouth", "lưỡi", "She burnt her tongue.", "Cô ấy bị bỏng lưỡi.", "A2"),
    ("neck", "/nek/", "noun", "the part connecting head and body", "cổ", "She wore a scarf around her neck.", "Cô ấy quàng khăn quanh cổ.", "A2"),
    ("shoulder", "/ˈʃəʊldər/", "noun", "the joint between the arm and the body", "vai", "He shrugged his shoulders.", "Anh ấy nhún vai.", "A2"),
    ("arm", "/ɑːrm/", "noun", "the limb from shoulder to wrist", "cánh tay", "She broke her arm.", "Cô ấy gãy tay.", "A2"),
    ("elbow", "/ˈelbəʊ/", "noun", "the joint in the middle of the arm", "khuỷu tay", "He leaned on his elbow.", "Anh ấy tựa khuỷu tay.", "A2"),
    ("wrist", "/rɪst/", "noun", "the joint between the arm and hand", "cổ tay", "She wore a bracelet on her wrist.", "Cô ấy đeo vòng ở cổ tay.", "A2"),
    ("hand", "/hænd/", "noun", "the part at the end of the arm", "bàn tay", "Shake hands with someone.", "Bắt tay với ai đó.", "A2"),
    ("finger", "/ˈfɪŋɡər/", "noun", "one of the five digits on the hand", "ngón tay", "She cut her finger.", "Cô ấy đứt ngón tay.", "A2"),
    ("thumb", "/θʌm/", "noun", "the short thick digit on the hand", "ngón cái", "Give a thumbs up.", "Giơ ngón cái lên.", "A2"),
    ("chest", "/tʃest/", "noun", "the front part of the upper body", "ngực", "He has chest pain.", "Anh ấy bị đau ngực.", "A2"),
    ("stomach", "/ˈstʌmək/", "noun", "the organ that digests food", "dạ dày/bụng", "My stomach hurts.", "Dạ dày tôi đau.", "A2"),
    ("back", "/bæk/", "noun", "the rear part of the body", "lưng", "He has back pain.", "Anh ấy bị đau lưng.", "A2"),
    ("leg", "/leɡ/", "noun", "the limb for standing and walking", "chân", "She hurt her leg.", "Cô ấy bị thương ở chân.", "A2"),
    ("knee", "/niː/", "noun", "the joint in the middle of the leg", "đầu gối", "He knelt on one knee.", "Anh ấy quỳ một gối.", "A2"),
    ("ankle", "/ˈæŋkəl/", "noun", "the joint between the leg and foot", "mắt cá chân", "She sprained her ankle.", "Cô ấy bị bong gân mắt cá chân.", "A2"),
    ("foot", "/fʊt/", "noun", "the part at the end of the leg", "bàn chân", "She has small feet.", "Cô ấy có đôi chân nhỏ.", "A2"),
    ("toe", "/təʊ/", "noun", "one of the five digits on the foot", "ngón chân", "She stubbed her toe.", "Cô ấy vấp ngón chân.", "A2"),
    # A2 - house rooms & features
    ("bedroom", "/ˈbedrʊm/", "noun", "a room for sleeping", "phòng ngủ", "She tidied her bedroom.", "Cô ấy dọn phòng ngủ.", "A2"),
    ("bathroom", "/ˈbɑːθruːm/", "noun", "a room with a bath or shower", "phòng tắm", "The bathroom is on the left.", "Phòng tắm ở bên trái.", "A2"),
    ("kitchen", "/ˈkɪtʃɪn/", "noun", "a room for cooking", "nhà bếp", "She is cooking in the kitchen.", "Cô ấy đang nấu ăn trong bếp.", "A2"),
    ("living room", "/ˈlɪvɪŋ ruːm/", "noun", "a room for relaxing", "phòng khách", "They watched TV in the living room.", "Họ xem TV trong phòng khách.", "A2"),
    ("dining room", "/ˈdaɪnɪŋ ruːm/", "noun", "a room for eating meals", "phòng ăn", "We eat in the dining room.", "Chúng tôi ăn trong phòng ăn.", "A2"),
    ("garage", "/ˈɡærɑːʒ/", "noun", "a building for keeping cars", "nhà để xe", "Park the car in the garage.", "Đỗ xe trong nhà để xe.", "A2"),
    ("garden", "/ˈɡɑːrdən/", "noun", "a piece of ground for growing plants", "khu vườn", "She grows flowers in the garden.", "Cô ấy trồng hoa trong vườn.", "A2"),
    ("balcony", "/ˈbælkəni/", "noun", "a platform on the outside of a building", "ban công", "They sat on the balcony.", "Họ ngồi trên ban công.", "A2"),
    ("basement", "/ˈbeɪsmənt/", "noun", "a room or area below ground level", "tầng hầm", "The basement is used for storage.", "Tầng hầm dùng để lưu trữ.", "A2"),
    ("staircase", "/ˈsteərkeɪs/", "noun", "a set of stairs inside a building", "cầu thang", "Walk up the staircase.", "Đi lên cầu thang.", "A2"),
    # B1 - Phrasal verbs (common)
    ("bring up", "/brɪŋ ʌp/", "verb", "to mention or raise a topic", "đề cập đến", "She brought up the issue at the meeting.", "Cô ấy đề cập đến vấn đề tại cuộc họp.", "B1"),
    ("carry out", "/ˈkæri aʊt/", "verb", "to perform or complete a task", "thực hiện", "They carried out the plan.", "Họ thực hiện kế hoạch.", "B1"),
    ("come across", "/kʌm əˈkrɒs/", "verb", "to find or meet by chance", "tình cờ gặp", "I came across an old photo.", "Tôi tình cờ gặp một bức ảnh cũ.", "B1"),
    ("deal with", "/diːl wɪð/", "verb", "to handle or manage something", "giải quyết", "He dealt with the problem calmly.", "Anh ấy bình tĩnh giải quyết vấn đề.", "B1"),
    ("figure out", "/ˈfɪɡər aʊt/", "verb", "to understand or solve something", "tìm ra/hiểu ra", "Can you figure out the answer?", "Bạn có thể tìm ra câu trả lời không?", "B1"),
    ("give up", "/ɡɪv ʌp/", "verb", "to stop trying to do something", "từ bỏ", "Never give up your dreams.", "Đừng bao giờ từ bỏ ước mơ.", "B1"),
    ("go ahead", "/ɡəʊ əˈhed/", "verb", "to start or continue doing something", "tiến hành", "Go ahead with the plan.", "Tiến hành kế hoạch đi.", "B1"),
    ("hand in", "/hænd ɪn/", "verb", "to submit something formally", "nộp", "Hand in your assignment.", "Nộp bài tập của bạn.", "B1"),
    ("keep up", "/kiːp ʌp/", "verb", "to continue at the same pace", "theo kịp", "Keep up the good work.", "Tiếp tục công việc tốt.", "B1"),
    ("look after", "/lʊk ˈɑːftər/", "verb", "to take care of someone", "chăm sóc", "She looks after her elderly parents.", "Cô ấy chăm sóc cha mẹ già.", "B1"),
    ("look forward to", "/lʊk ˈfɔːrwərd tə/", "verb", "to feel excited about something coming", "mong chờ", "I look forward to seeing you.", "Tôi mong chờ gặp bạn.", "B1"),
    ("look up", "/lʊk ʌp/", "verb", "to search for information", "tra cứu", "Look up the word in a dictionary.", "Tra từ trong từ điển.", "B1"),
    ("make up", "/meɪk ʌp/", "verb", "to invent or create a story", "bịa đặt/tạo thành", "Don't make up excuses.", "Đừng bịa đặt lý do.", "B1"),
    ("pick up", "/pɪk ʌp/", "verb", "to collect someone or to lift something", "đón/nhặt lên", "Pick me up at 8.", "Đón tôi lúc 8 giờ.", "B1"),
    ("point out", "/pɔɪnt aʊt/", "verb", "to draw attention to something", "chỉ ra", "She pointed out the mistake.", "Cô ấy chỉ ra lỗi sai.", "B1"),
    ("put off", "/pʊt ɒf/", "verb", "to delay or postpone", "trì hoãn", "Don't put off important tasks.", "Đừng trì hoãn công việc quan trọng.", "B1"),
    ("run out of", "/rʌn aʊt əv/", "verb", "to have no more of something", "hết", "We ran out of time.", "Chúng tôi hết thời gian.", "B1"),
    ("set up", "/set ʌp/", "verb", "to arrange or establish something", "thiết lập", "She set up her own business.", "Cô ấy thiết lập doanh nghiệp riêng.", "B1"),
    ("take off", "/teɪk ɒf/", "verb", "for a plane to leave the ground", "cất cánh", "The plane takes off at noon.", "Máy bay cất cánh lúc giữa trưa.", "B1"),
    ("turn down", "/tɜːrn daʊn/", "verb", "to refuse an offer or request", "từ chối", "He turned down the job offer.", "Anh ấy từ chối lời đề nghị công việc.", "B1"),
    ("work out", "/wɜːrk aʊt/", "verb", "to exercise or to solve something", "tập thể dục/giải quyết", "It will work out in the end.", "Cuối cùng sẽ ổn thôi.", "B1"),
    # B2 - Economics & finance
    ("inflation", "/ɪnˈfleɪʃən/", "noun", "the rate at which prices rise", "lạm phát", "High inflation reduces purchasing power.", "Lạm phát cao làm giảm sức mua.", "B2"),
    ("recession", "/rɪˈseʃən/", "noun", "a period of reduced economic activity", "suy thoái kinh tế", "The recession lasted two years.", "Suy thoái kinh tế kéo dài hai năm.", "B2"),
    ("gross domestic product", "/ɡrəʊs dəˈmestɪk ˈprɒdʌkt/", "noun", "total value of a country's output", "tổng sản phẩm quốc nội", "GDP grew by 3% this year.", "GDP tăng trưởng 3% năm nay.", "B2"),
    ("trade", "/treɪd/", "noun", "buying and selling goods between parties", "thương mại", "International trade creates wealth.", "Thương mại quốc tế tạo ra sự thịnh vượng.", "B2"),
    ("tariff", "/ˈtærɪf/", "noun", "a tax on imported goods", "thuế quan", "New tariffs affect imports.", "Thuế quan mới ảnh hưởng đến hàng nhập khẩu.", "B2"),
    ("export", "/ˈekspɔːrt/", "noun", "goods sold to another country", "xuất khẩu", "Vietnam exports a lot of rice.", "Việt Nam xuất khẩu nhiều gạo.", "B2"),
    ("import", "/ˈɪmpɔːrt/", "noun", "goods brought into a country", "nhập khẩu", "Japan imports oil and gas.", "Nhật Bản nhập khẩu dầu và khí đốt.", "B2"),
    ("subsidy", "/ˈsʌbsɪdi/", "noun", "money given by government to support industry", "trợ cấp", "Farm subsidies help small farmers.", "Trợ cấp nông nghiệp giúp nông dân nhỏ.", "B2"),
    ("dividend", "/ˈdɪvɪdend/", "noun", "a payment made to shareholders", "cổ tức", "They paid a dividend this quarter.", "Họ trả cổ tức quý này.", "B2"),
    ("portfolio", "/pɔːrtˈfəʊliəʊ/", "noun", "a collection of investments", "danh mục đầu tư", "Diversify your investment portfolio.", "Đa dạng hóa danh mục đầu tư.", "B2"),
    # B2 - Law & crime
    ("arrest", "/əˈrest/", "verb", "to legally detain someone", "bắt giữ", "Police arrested the suspect.", "Cảnh sát bắt giữ nghi phạm.", "B2"),
    ("trial", "/ˈtraɪəl/", "noun", "a legal process to decide if someone is guilty", "phiên tòa", "The trial lasted three weeks.", "Phiên tòa kéo dài ba tuần.", "B2"),
    ("verdict", "/ˈvɜːrdɪkt/", "noun", "the decision reached by a jury", "phán quyết", "The jury returned a not guilty verdict.", "Bồi thẩm đoàn đưa ra phán quyết vô tội.", "B2"),
    ("sentence", "/ˈsentəns/", "noun", "the punishment given by a court", "bản án", "He received a five-year sentence.", "Anh ấy lãnh án năm năm.", "B2"),
    ("defendant", "/dɪˈfendənt/", "noun", "a person accused in a legal case", "bị cáo", "The defendant denied the charge.", "Bị cáo phủ nhận cáo buộc.", "B2"),
    ("witness", "/ˈwɪtnɪs/", "noun", "someone who saw an event", "nhân chứng", "The witness described what happened.", "Nhân chứng mô tả những gì đã xảy ra.", "B2"),
    ("lawyer", "/ˈlɔɪər/", "noun", "a person qualified to advise on law", "luật sư", "She hired a lawyer.", "Cô ấy thuê luật sư.", "B2"),
    ("evidence", "/ˈevɪdəns/", "noun", "information proving something is true", "bằng chứng", "Forensic evidence solved the case.", "Bằng chứng pháp y giải quyết vụ án.", "B2"),
    ("suspect", "/ˈsʌspekt/", "noun", "a person thought to be guilty", "nghi phạm", "Police questioned three suspects.", "Cảnh sát thẩm vấn ba nghi phạm.", "B2"),
    ("fine", "/faɪn/", "noun", "a payment as punishment", "tiền phạt", "He paid a parking fine.", "Anh ấy nộp phạt đỗ xe.", "B2"),
    # C1 - Academic / IELTS
    ("albeit", "/ɔːlˈbiːɪt/", "conjunction", "even though; although", "mặc dù", "It was a small, albeit important, change.", "Đó là thay đổi nhỏ, mặc dù quan trọng.", "C1"),
    ("commensurate", "/kəˈmenʃərɪt/", "adjective", "corresponding in size or degree", "tương xứng", "Rewards should be commensurate with effort.", "Phần thưởng nên tương xứng với nỗ lực.", "C1"),
    ("contentious", "/kənˈtenʃəs/", "adjective", "causing or likely to cause disagreement", "gây tranh cãi", "The law is highly contentious.", "Bộ luật này rất gây tranh cãi.", "C1"),
    ("delineate", "/dɪˈlɪnieɪt/", "verb", "to describe or indicate precisely", "phác thảo rõ ràng", "Delineate the scope of the project.", "Phác thảo rõ phạm vi dự án.", "C1"),
    ("dichotomy", "/daɪˈkɒtəmi/", "noun", "a division into two opposite parts", "sự phân đôi", "There is a dichotomy between theory and practice.", "Có sự phân đôi giữa lý thuyết và thực hành.", "C1"),
    ("elicit", "/ɪˈlɪsɪt/", "verb", "to draw out a response or reaction", "khơi gợi", "The question elicited many responses.", "Câu hỏi khơi gợi nhiều phản hồi.", "C1"),
    ("endorse", "/ɪnˈdɔːrs/", "verb", "to express support for", "ủng hộ/xác nhận", "He endorsed the new policy.", "Anh ấy ủng hộ chính sách mới.", "C1"),
    ("feasible", "/ˈfiːzɪbəl/", "adjective", "possible and likely to succeed", "khả thi", "Is the plan feasible?", "Kế hoạch có khả thi không?", "C1"),
    ("formidable", "/ˈfɔːrmɪdəbəl/", "adjective", "inspiring fear through impressive strength", "đáng gờm", "She is a formidable competitor.", "Cô ấy là đối thủ đáng gờm.", "C1"),
    ("garner", "/ˈɡɑːrnər/", "verb", "to gather or collect", "thu thập/đạt được", "She garnered widespread support.", "Cô ấy đạt được sự ủng hộ rộng rãi.", "C1"),
    ("hierarchy", "/ˈhaɪərɑːrki/", "noun", "a system ranked from highest to lowest", "hệ thống phân cấp", "The company has a strict hierarchy.", "Công ty có hệ thống phân cấp chặt chẽ.", "C1"),
    ("homogeneous", "/ˌhɒməˈdʒiːniəs/", "adjective", "of the same kind throughout", "đồng nhất", "The group is not homogeneous.", "Nhóm không đồng nhất.", "C1"),
    ("hypothesis", "/haɪˈpɒθɪsɪs/", "noun", "an explanation made for testing", "giả thuyết", "Test the hypothesis with data.", "Kiểm tra giả thuyết bằng dữ liệu.", "C1"),
    ("intangible", "/ɪnˈtændʒɪbəl/", "adjective", "unable to be touched or measured easily", "vô hình", "Trust is an intangible asset.", "Niềm tin là tài sản vô hình.", "C1"),
    ("mitigate", "/ˈmɪtɪɡeɪt/", "verb", "to make something less severe", "giảm thiểu", "Measures were taken to mitigate the risk.", "Các biện pháp được thực hiện để giảm thiểu rủi ro.", "C1"),
    ("notion", "/ˈnəʊʃən/", "noun", "a belief or idea about something", "khái niệm/ý tưởng", "He challenged the notion of success.", "Anh ấy đặt câu hỏi về khái niệm thành công.", "C1"),
    ("nuance", "/ˈnjuːɑːns/", "noun", "a subtle difference in meaning", "sắc thái", "Understand the nuances of language.", "Hiểu sắc thái của ngôn ngữ.", "C1"),
    ("parameter", "/pəˈræmɪtər/", "noun", "a limit or boundary for something", "thông số/phạm vi", "Work within the given parameters.", "Làm việc trong phạm vi đã cho.", "C1"),
    ("pervasive", "/pərˈveɪsɪv/", "adjective", "spreading through everything", "lan rộng", "Technology is pervasive in modern life.", "Công nghệ lan rộng trong cuộc sống hiện đại.", "C1"),
    ("scrutiny", "/ˈskruːtɪni/", "noun", "close and detailed examination", "sự xem xét kỹ lưỡng", "The proposal is under scrutiny.", "Đề xuất đang được xem xét kỹ lưỡng.", "C1"),
    ("inherently", "/ɪnˈhɪərəntli/", "adverb", "in a natural or essential way", "vốn dĩ", "The task is inherently difficult.", "Nhiệm vụ vốn dĩ khó khăn.", "C1"),
    ("stringent", "/ˈstrɪndʒənt/", "adjective", "strict and precise", "nghiêm ngặt", "Follow stringent safety rules.", "Tuân thủ các quy tắc an toàn nghiêm ngặt.", "C1"),
    ("tenacious", "/tɪˈneɪʃəs/", "adjective", "not giving up; persistent", "kiên trì", "She is tenacious in pursuing her goal.", "Cô ấy kiên trì theo đuổi mục tiêu.", "C1"),
    ("threshold", "/ˈθreʃhəʊld/", "noun", "the level at which something begins", "ngưỡng", "The pain threshold varies.", "Ngưỡng đau thay đổi theo người.", "C1"),
    ("ubiquitous", "/juːˈbɪkwɪtəs/", "adjective", "appearing everywhere", "có mặt khắp nơi", "Smartphones are ubiquitous.", "Điện thoại thông minh có mặt khắp nơi.", "C1"),
    ("undermine", "/ˌʌndərˈmaɪn/", "verb", "to weaken or damage gradually", "làm suy yếu", "Don't undermine others' efforts.", "Đừng làm suy yếu nỗ lực của người khác.", "C1"),
    ("unprecedented", "/ʌnˈpresɪdentɪd/", "adjective", "never having happened before", "chưa từng có", "The growth rate was unprecedented.", "Tốc độ tăng trưởng là chưa từng có.", "C1"),
    # TOEIC - Transport & shipping
    ("freight", "/freɪt/", "noun", "goods transported by ship, truck or plane", "hàng hóa vận chuyển", "Freight is handled at the port.", "Hàng hóa được xử lý tại cảng.", "TOEIC"),
    ("cargo", "/ˈkɑːrɡəʊ/", "noun", "goods carried by a ship or aircraft", "hàng hóa (trên tàu/máy bay)", "The cargo was offloaded.", "Hàng hóa được dỡ xuống.", "TOEIC"),
    ("manifest", "/ˈmænɪfest/", "noun", "a list of cargo or passengers", "bản kê khai hàng hóa", "Check the cargo manifest.", "Kiểm tra bản kê khai hàng hóa.", "TOEIC"),
    ("dispatch", "/dɪˈspætʃ/", "verb", "to send goods or people somewhere", "gửi đi/điều phối", "Dispatch the order immediately.", "Gửi đơn hàng ngay lập tức.", "TOEIC"),
    ("consignment", "/kənˈsaɪnmənt/", "noun", "a batch of goods sent to someone", "lô hàng ký gửi", "The consignment arrived on time.", "Lô hàng đến đúng hẹn.", "TOEIC"),
    ("clearance", "/ˈklɪərəns/", "noun", "official approval to proceed", "thông quan", "Get customs clearance first.", "Đầu tiên lấy thông quan hải quan.", "TOEIC"),
    ("transit", "/ˈtrænsɪt/", "noun", "the movement of goods through a place", "trung chuyển", "Goods in transit are insured.", "Hàng hóa đang trung chuyển được bảo hiểm.", "TOEIC"),
    ("vessel", "/ˈvesəl/", "noun", "a large boat or ship", "tàu thuyền", "The vessel docked at the port.", "Con tàu cập bến.", "TOEIC"),
    ("port", "/pɔːrt/", "noun", "a harbour where ships load and unload", "cảng", "The port is busy this season.", "Cảng rất bận vào mùa này.", "TOEIC"),
    ("charter", "/ˈtʃɑːrtər/", "verb", "to hire a vehicle for a special purpose", "thuê (tàu/máy bay)", "They chartered a plane.", "Họ thuê một chiếc máy bay.", "TOEIC"),
    # TOEIC - Property & real estate
    ("lease", "/liːs/", "noun", "a legal agreement to rent property", "hợp đồng thuê", "Sign the lease before moving in.", "Ký hợp đồng thuê trước khi chuyển vào.", "TOEIC"),
    ("tenant", "/ˈtenənt/", "noun", "a person who rents a property", "người thuê nhà", "The tenant paid rent on time.", "Người thuê nhà trả tiền đúng hạn.", "TOEIC"),
    ("landlord", "/ˈlændlɔːrd/", "noun", "the owner of a rented property", "chủ nhà", "Contact the landlord about repairs.", "Liên hệ chủ nhà về sửa chữa.", "TOEIC"),
    ("property", "/ˈprɒpərti/", "noun", "a building and the land it is on", "bất động sản", "Property prices have risen.", "Giá bất động sản đã tăng.", "TOEIC"),
    ("utilities", "/juːˈtɪlɪtiz/", "noun", "services like water, gas, and electricity", "tiện ích (điện, nước, gas)", "Utilities are included in the rent.", "Tiện ích được bao gồm trong tiền thuê.", "TOEIC"),
    ("renovation", "/ˌrenəˈveɪʃən/", "noun", "the process of improving a building", "cải tạo", "The office renovation is complete.", "Việc cải tạo văn phòng đã hoàn thành.", "TOEIC"),
    ("appraise", "/əˈpreɪz/", "verb", "to estimate the value of a property", "định giá", "The house was appraised at one million.", "Ngôi nhà được định giá một triệu.", "TOEIC"),
    ("occupancy", "/ˈɒkjəpənsi/", "noun", "the state of using a building", "tỷ lệ lấp đầy", "Hotel occupancy is high.", "Tỷ lệ lấp đầy khách sạn cao.", "TOEIC"),
    ("premises", "/ˈpremɪsɪz/", "noun", "a building and its grounds", "cơ sở/địa điểm", "No smoking on the premises.", "Không hút thuốc trong cơ sở.", "TOEIC"),
    ("evict", "/ɪˈvɪkt/", "verb", "to force someone to leave a property", "trục xuất", "The landlord evicted the tenant.", "Chủ nhà trục xuất người thuê.", "TOEIC"),
    # B1 - describing people (appearance)
    ("tall", "/tɔːl/", "adjective", "having a greater than average height", "cao", "He is very tall.", "Anh ấy rất cao.", "B1"),
    ("short", "/ʃɔːrt/", "adjective", "having a smaller than average height", "thấp", "She is short but strong.", "Cô ấy thấp nhưng mạnh.", "B1"),
    ("slim", "/slɪm/", "adjective", "thin in an attractive way", "mảnh mai", "She is slim and athletic.", "Cô ấy mảnh mai và năng động.", "B1"),
    ("overweight", "/ˌəʊvərˈweɪt/", "adjective", "heavier than is healthy", "thừa cân", "He is slightly overweight.", "Anh ấy hơi thừa cân.", "B1"),
    ("elderly", "/ˈeldərli/", "adjective", "old in a polite way", "cao tuổi", "She cares for elderly people.", "Cô ấy chăm sóc người cao tuổi.", "B1"),
    ("middle-aged", "/ˌmɪdəl ˈeɪdʒd/", "adjective", "between about 40 and 60 years old", "trung niên", "He is a middle-aged man.", "Anh ấy là người đàn ông trung niên.", "B1"),
    ("curly", "/ˈkɜːrli/", "adjective", "having waves or spirals", "xoăn", "She has curly red hair.", "Cô ấy có tóc đỏ xoăn.", "B1"),
    ("straight", "/streɪt/", "adjective", "not curly or wavy", "thẳng", "She has long straight hair.", "Cô ấy có mái tóc dài thẳng.", "B1"),
    ("bald", "/bɔːld/", "adjective", "having no hair on the head", "hói đầu", "He went bald at 40.", "Anh ấy bị hói đầu lúc 40 tuổi.", "B1"),
    ("freckle", "/ˈfrekəl/", "noun", "a small brown spot on the skin", "tàn nhang", "She has freckles on her nose.", "Cô ấy có tàn nhang trên mũi.", "B1"),
    # A2 - sports & activities
    ("football", "/ˈfʊtbɔːl/", "noun", "a team sport played with a round ball", "bóng đá", "He plays football every weekend.", "Anh ấy chơi bóng đá mỗi cuối tuần.", "A2"),
    ("basketball", "/ˈbɑːskɪtbɔːl/", "noun", "a sport with a ball and hoops", "bóng rổ", "She plays basketball after school.", "Cô ấy chơi bóng rổ sau giờ học.", "A2"),
    ("volleyball", "/ˈvɒlibɔːl/", "noun", "a team sport played over a net", "bóng chuyền", "They played volleyball at the beach.", "Họ chơi bóng chuyền ở bãi biển.", "A2"),
    ("swimming", "/ˈswɪmɪŋ/", "noun", "the sport of moving through water", "bơi lội", "Swimming is good exercise.", "Bơi lội là bài tập tốt.", "A2"),
    ("running", "/ˈrʌnɪŋ/", "noun", "the activity of moving on foot quickly", "chạy bộ", "Running keeps you fit.", "Chạy bộ giúp bạn khỏe mạnh.", "A2"),
    ("cycling", "/ˈsaɪklɪŋ/", "noun", "the activity of riding a bicycle", "đạp xe", "Cycling is eco-friendly.", "Đạp xe thân thiện với môi trường.", "A2"),
    ("tennis", "/ˈtenɪs/", "noun", "a sport played with rackets and a ball", "quần vợt", "She plays tennis twice a week.", "Cô ấy chơi quần vợt hai lần một tuần.", "A2"),
    ("badminton", "/ˈbædmɪntən/", "noun", "a racket sport played with a shuttlecock", "cầu lông", "He plays badminton with friends.", "Anh ấy chơi cầu lông với bạn bè.", "A2"),
    ("yoga", "/ˈjəʊɡə/", "noun", "an exercise combining movement and breathing", "yoga", "She does yoga every morning.", "Cô ấy tập yoga mỗi sáng.", "A2"),
    ("hiking", "/ˈhaɪkɪŋ/", "noun", "walking long distances in the countryside", "leo núi/đi bộ đường dài", "They went hiking in the mountains.", "Họ đi leo núi.", "A2"),
    ("fishing", "/ˈfɪʃɪŋ/", "noun", "catching fish as a hobby", "câu cá", "He enjoys fishing on weekends.", "Anh ấy thích câu cá vào cuối tuần.", "A2"),
    ("camping", "/ˈkæmpɪŋ/", "noun", "sleeping outdoors in a tent", "cắm trại", "They went camping in the forest.", "Họ đi cắm trại trong rừng.", "A2"),
    ("photography", "/fəˈtɒɡrəfi/", "noun", "taking photographs as a hobby", "nhiếp ảnh", "Photography is his passion.", "Nhiếp ảnh là đam mê của anh ấy.", "A2"),
    ("gardening", "/ˈɡɑːrdənɪŋ/", "noun", "growing plants in a garden", "làm vườn", "She enjoys gardening on weekends.", "Cô ấy thích làm vườn vào cuối tuần.", "A2"),
    ("painting", "/ˈpeɪntɪŋ/", "noun", "making pictures with paint", "hội họa/vẽ tranh", "He took up painting last year.", "Anh ấy bắt đầu học vẽ tranh năm ngoái.", "A2"),
    # B2 - digital & social media
    ("algorithm", "/ˈælɡərɪðəm/", "noun", "a set of rules for solving a problem", "thuật toán", "Social media algorithms control what you see.", "Thuật toán mạng xã hội kiểm soát những gì bạn thấy.", "B2"),
    ("viral", "/ˈvaɪrəl/", "adjective", "spreading rapidly online", "lan truyền nhanh", "The video went viral overnight.", "Video lan truyền nhanh chóng qua đêm.", "B2"),
    ("influencer", "/ˈɪnfluənsər/", "noun", "someone with large social media following", "người có ảnh hưởng", "She is a popular influencer.", "Cô ấy là người có ảnh hưởng nổi tiếng.", "B2"),
    ("platform", "/ˈplætfɔːrm/", "noun", "a digital service for sharing content", "nền tảng", "Which platform do you use most?", "Bạn dùng nền tảng nào nhiều nhất?", "B2"),
    ("content", "/ˈkɒntent/", "noun", "digital material shared online", "nội dung", "Create quality content regularly.", "Tạo nội dung chất lượng thường xuyên.", "B2"),
    ("engagement", "/ɪnˈɡeɪdʒmənt/", "noun", "interaction with content online", "mức độ tương tác", "High engagement boosts visibility.", "Tương tác cao tăng khả năng hiển thị.", "B2"),
    ("stream", "/striːm/", "verb", "to broadcast or watch media online", "phát trực tuyến", "She streams music online.", "Cô ấy nghe nhạc trực tuyến.", "B2"),
    ("download", "/ˈdaʊnləʊd/", "verb", "to copy data from the internet to a device", "tải xuống", "Download the app for free.", "Tải ứng dụng miễn phí.", "B2"),
    ("upload", "/ˈʌpləʊd/", "verb", "to copy data from a device to the internet", "tải lên", "Upload the file to the server.", "Tải tệp lên máy chủ.", "B2"),
    ("privacy", "/ˈprɪvəsi/", "noun", "the right to keep personal information secret", "quyền riêng tư", "Protect your online privacy.", "Bảo vệ quyền riêng tư trực tuyến.", "B2"),
    ("cybersecurity", "/ˈsaɪbərsɪˌkjʊərɪti/", "noun", "protection of computer systems from attacks", "an ninh mạng", "Cybersecurity is essential for businesses.", "An ninh mạng rất cần thiết cho doanh nghiệp.", "B2"),
    ("artificial intelligence", "/ˌɑːtɪˈfɪʃəl ɪnˈtelɪdʒəns/", "noun", "machine ability to mimic human intelligence", "trí tuệ nhân tạo", "Artificial intelligence is changing industries.", "Trí tuệ nhân tạo đang thay đổi các ngành công nghiệp.", "B2"),
    ("machine learning", "/məˌʃiːn ˈlɜːrnɪŋ/", "noun", "a type of AI that learns from data", "học máy", "Machine learning improves predictions.", "Học máy cải thiện dự đoán.", "B2"),
    ("automation", "/ˌɔːtəˈmeɪʃən/", "noun", "using machines to do work automatically", "tự động hóa", "Automation reduces human error.", "Tự động hóa giảm lỗi của con người.", "B2"),
    ("innovation", "/ˌɪnəˈveɪʃən/", "noun", "the act of introducing new ideas", "đổi mới", "Innovation drives competitiveness.", "Đổi mới thúc đẩy cạnh tranh.", "B2"),
    # B1 - feelings about study/work
    ("motivated", "/ˈməʊtɪveɪtɪd/", "adjective", "having desire and enthusiasm", "có động lực", "She is highly motivated.", "Cô ấy rất có động lực.", "B1"),
    ("focused", "/ˈfəʊkəst/", "adjective", "giving full attention to one thing", "tập trung", "Stay focused during the exam.", "Giữ tập trung trong kỳ thi.", "B1"),
    ("overwhelmed", "/ˌəʊvərˈwelmd/", "adjective", "having too much to cope with", "choáng ngợp", "She felt overwhelmed by the workload.", "Cô ấy cảm thấy choáng ngợp với khối lượng công việc.", "B1"),
    ("determined", "/dɪˈtɜːrmɪnd/", "adjective", "having made a firm decision", "kiên định", "He is determined to succeed.", "Anh ấy kiên định để thành công.", "B1"),
    ("discouraged", "/dɪsˈkʌrɪdʒd/", "adjective", "having lost confidence", "nản lòng", "Don't get discouraged by failure.", "Đừng nản lòng vì thất bại.", "B1"),
    ("satisfied", "/ˈsætɪsfaɪd/", "adjective", "pleased because needs are met", "hài lòng", "She was satisfied with the result.", "Cô ấy hài lòng với kết quả.", "B1"),
    ("stressed", "/strest/", "adjective", "feeling pressure and worry", "căng thẳng", "He looked very stressed.", "Anh ấy trông rất căng thẳng.", "B1"),
    ("optimistic", "/ˌɒptɪˈmɪstɪk/", "adjective", "expecting good things to happen", "lạc quan", "She is optimistic about the future.", "Cô ấy lạc quan về tương lai.", "B1"),
    ("pessimistic", "/ˌpesɪˈmɪstɪk/", "adjective", "expecting bad things to happen", "bi quan", "He is often pessimistic.", "Anh ấy thường bi quan.", "B1"),
    ("ambitious", "/æmˈbɪʃəs/", "adjective", "having a strong desire to succeed", "tham vọng", "She is ambitious and hardworking.", "Cô ấy tham vọng và chăm chỉ.", "B1"),
]


def run():
    created = 0
    skipped = 0
    for item in WORDS:
        text, phonetic, pos, def_en, def_vi, ex_en, ex_vi, level = item
        _, is_new = Word.objects.get_or_create(
            text=text,
            defaults={
                "phonetic": phonetic,
                "part_of_speech": pos,
                "definition_en": def_en,
                "definition_vi": def_vi,
                "example_en": ex_en,
                "example_vi": ex_vi,
                "level": level,
            },
        )
        if is_new:
            created += 1
        else:
            skipped += 1
    total = Word.objects.count()
    print(f"Hoàn thành: {created} từ mới, {skipped} bỏ qua.")
    print(f"Tổng từ vựng hiện tại: {total}")


run()
