"""Batch 3: ~500 từ vựng bổ sung."""
import os, sys
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
os.environ.setdefault("DJANGO_SETTINGS_MODULE", "config.settings.development")
import django; django.setup()
from apps.vocabulary.models import Word

WORDS = [
    # A1 - Classroom & school
    ("pen", "/pen/", "noun", "a writing tool with ink", "bút mực", "She wrote with a pen.", "Cô ấy viết bằng bút mực.", "A1"),
    ("ruler", "/ˈruːlər/", "noun", "a flat tool for measuring", "thước kẻ", "Use a ruler to draw a straight line.", "Dùng thước kẻ để vẽ đường thẳng.", "A1"),
    ("notebook", "/ˈnəʊtbʊk/", "noun", "a book for writing notes", "vở ghi chú", "Write in your notebook.", "Viết vào vở ghi chú.", "A1"),
    ("blackboard", "/ˈblækbɔːrd/", "noun", "a dark board teachers write on", "bảng đen", "The teacher wrote on the blackboard.", "Giáo viên viết lên bảng đen.", "A1"),
    ("eraser", "/ɪˈreɪzər/", "noun", "a tool used to remove pencil marks", "cục tẩy", "He used an eraser to fix the mistake.", "Anh ấy dùng cục tẩy để sửa lỗi.", "A1"),
    ("dictionary", "/ˈdɪkʃəneri/", "noun", "a book that explains word meanings", "từ điển", "Look it up in the dictionary.", "Tra trong từ điển.", "A1"),
    ("lesson", "/ˈlesən/", "noun", "a period of teaching", "bài học", "The lesson starts at 8 AM.", "Bài học bắt đầu lúc 8 giờ sáng.", "A1"),
    ("class", "/klɑːs/", "noun", "a group of students taught together", "lớp học", "She has 30 students in her class.", "Cô ấy có 30 học sinh trong lớp.", "A1"),
    ("student", "/ˈstjuːdənt/", "noun", "a person who studies", "học sinh", "The student studied hard.", "Học sinh học chăm chỉ.", "A1"),
    ("teacher", "/ˈtiːtʃər/", "noun", "a person who teaches", "giáo viên", "The teacher explained the grammar.", "Giáo viên giải thích ngữ pháp.", "A1"),
    ("homework", "/ˈhəʊmwɜːrk/", "noun", "school work done at home", "bài tập về nhà", "Did you finish your homework?", "Bạn hoàn thành bài tập về nhà chưa?", "A1"),
    ("exam", "/ɪɡˈzæm/", "noun", "a formal test of knowledge", "kỳ thi", "She passed all her exams.", "Cô ấy đậu tất cả các kỳ thi.", "A1"),
    ("grade", "/ɡreɪd/", "noun", "a mark given for school work", "điểm số", "He got a good grade.", "Anh ấy đạt điểm tốt.", "A1"),
    ("subject", "/ˈsʌbdʒɪkt/", "noun", "an area of study", "môn học", "Maths is her favourite subject.", "Toán là môn học yêu thích của cô ấy.", "A1"),
    # A1 - Family & people
    ("mother", "/ˈmʌðər/", "noun", "a female parent", "mẹ", "My mother cooks delicious food.", "Mẹ tôi nấu ăn ngon.", "A1"),
    ("father", "/ˈfɑːðər/", "noun", "a male parent", "bố", "My father works in an office.", "Bố tôi làm việc ở văn phòng.", "A1"),
    ("brother", "/ˈbrʌðər/", "noun", "a male sibling", "anh/em trai", "My brother is older than me.", "Anh trai tôi lớn hơn tôi.", "A1"),
    ("sister", "/ˈsɪstər/", "noun", "a female sibling", "chị/em gái", "My sister is a doctor.", "Chị gái tôi là bác sĩ.", "A1"),
    ("grandfather", "/ˈɡrændˌfɑːðər/", "noun", "the father of one's parent", "ông nội/ngoại", "My grandfather is 80 years old.", "Ông nội tôi 80 tuổi.", "A1"),
    ("grandmother", "/ˈɡrændˌmʌðər/", "noun", "the mother of one's parent", "bà nội/ngoại", "My grandmother tells great stories.", "Bà nội tôi kể chuyện rất hay.", "A1"),
    ("uncle", "/ˈʌŋkəl/", "noun", "the brother of one's parent", "chú/bác", "My uncle lives in the countryside.", "Chú tôi sống ở nông thôn.", "A1"),
    ("aunt", "/ɑːnt/", "noun", "the sister of one's parent", "cô/dì", "My aunt brought me gifts.", "Cô tôi mang quà cho tôi.", "A1"),
    ("cousin", "/ˈkʌzən/", "noun", "the child of one's uncle or aunt", "anh/chị/em họ", "I played with my cousins.", "Tôi chơi với các anh em họ.", "A1"),
    ("husband", "/ˈhʌzbənd/", "noun", "a married man", "chồng", "Her husband is a chef.", "Chồng cô ấy là đầu bếp.", "A1"),
    ("wife", "/waɪf/", "noun", "a married woman", "vợ", "His wife is a nurse.", "Vợ anh ấy là y tá.", "A1"),
    ("child", "/tʃaɪld/", "noun", "a young person", "đứa trẻ", "The child is playing outside.", "Đứa trẻ đang chơi ở ngoài.", "A1"),
    ("baby", "/ˈbeɪbi/", "noun", "a very young child", "em bé", "The baby is sleeping.", "Em bé đang ngủ.", "A1"),
    ("friend", "/frend/", "noun", "a person you like and trust", "bạn bè", "She is my best friend.", "Cô ấy là bạn thân nhất của tôi.", "A1"),
    ("neighbour", "/ˈneɪbər/", "noun", "someone who lives nearby", "hàng xóm", "My neighbour is very friendly.", "Hàng xóm của tôi rất thân thiện.", "A1"),
    # A2 - Transport
    ("bicycle", "/ˈbaɪsɪkəl/", "noun", "a two-wheeled vehicle powered by pedals", "xe đạp", "She rides her bicycle to school.", "Cô ấy đạp xe đến trường.", "A2"),
    ("motorcycle", "/ˈməʊtəˌsaɪkəl/", "noun", "a two-wheeled motor vehicle", "xe máy", "He rides a motorcycle to work.", "Anh ấy đi xe máy đến chỗ làm.", "A2"),
    ("bus", "/bʌs/", "noun", "a large vehicle carrying many passengers", "xe buýt", "Take the bus to the centre.", "Đi xe buýt đến trung tâm.", "A2"),
    ("taxi", "/ˈtæksi/", "noun", "a car hired with a driver", "taxi", "Call a taxi to the airport.", "Gọi taxi đến sân bay.", "A2"),
    ("train", "/treɪn/", "noun", "a vehicle that runs on rails", "tàu hỏa", "The train arrives at 7 PM.", "Tàu hỏa đến lúc 7 giờ tối.", "A2"),
    ("aeroplane", "/ˈeərəpleɪn/", "noun", "a vehicle that flies through the air", "máy bay", "The aeroplane landed safely.", "Máy bay hạ cánh an toàn.", "A2"),
    ("ship", "/ʃɪp/", "noun", "a large boat for sea travel", "tàu thủy", "The ship crossed the ocean.", "Con tàu vượt đại dương.", "A2"),
    ("helicopter", "/ˈhelɪkɒptər/", "noun", "an aircraft with rotating blades", "trực thăng", "A helicopter flew over the city.", "Một chiếc trực thăng bay qua thành phố.", "A2"),
    ("traffic", "/ˈtræfɪk/", "noun", "vehicles moving on a road", "giao thông", "Traffic is heavy during rush hour.", "Giao thông đông vào giờ cao điểm.", "A2"),
    ("road", "/rəʊd/", "noun", "a paved way for vehicles", "đường", "Take the road on the left.", "Đi theo con đường bên trái.", "A2"),
    ("bridge", "/brɪdʒ/", "noun", "a structure over water or a gap", "cây cầu", "The bridge connects the two islands.", "Cây cầu nối hai hòn đảo.", "A2"),
    ("petrol", "/ˈpetrəl/", "noun", "fuel used in vehicles", "xăng", "Fill the car with petrol.", "Đổ xăng vào ô tô.", "A2"),
    ("parking", "/ˈpɑːrkɪŋ/", "noun", "a place to leave a vehicle", "bãi đậu xe", "Parking is free on weekends.", "Đậu xe miễn phí vào cuối tuần.", "A2"),
    # A2 - Clothing
    ("shirt", "/ʃɜːrt/", "noun", "a garment worn on the upper body", "áo sơ mi", "He wore a white shirt.", "Anh ấy mặc áo sơ mi trắng.", "A2"),
    ("trousers", "/ˈtraʊzərz/", "noun", "clothing worn on the lower body", "quần dài", "She ironed her trousers.", "Cô ấy là quần dài.", "A2"),
    ("dress", "/dres/", "noun", "a woman's garment from shoulder to below", "váy đầm", "She wore a beautiful dress.", "Cô ấy mặc một chiếc váy đẹp.", "A2"),
    ("skirt", "/skɜːrt/", "noun", "a garment hanging from the waist", "chân váy", "She wore a short skirt.", "Cô ấy mặc chân váy ngắn.", "A2"),
    ("jacket", "/ˈdʒækɪt/", "noun", "a short coat", "áo khoác", "Put on your jacket, it's cold.", "Mặc áo khoác vào, trời lạnh.", "A2"),
    ("coat", "/kəʊt/", "noun", "a long warm outer garment", "áo khoác dài", "She wore a thick winter coat.", "Cô ấy mặc áo khoác dày mùa đông.", "A2"),
    ("hat", "/hæt/", "noun", "a covering worn on the head", "mũ", "Wear a hat in the sun.", "Đội mũ khi ra nắng.", "A2"),
    ("scarf", "/skɑːrf/", "noun", "a piece of cloth worn around the neck", "khăn quàng cổ", "She wrapped a scarf around her neck.", "Cô ấy quàng khăn quanh cổ.", "A2"),
    ("gloves", "/ɡlʌvz/", "noun", "coverings worn on the hands", "găng tay", "He wore gloves in winter.", "Anh ấy đeo găng tay vào mùa đông.", "A2"),
    ("socks", "/sɒks/", "noun", "clothing worn on the feet", "tất chân", "Put on clean socks.", "Mang tất sạch vào.", "A2"),
    ("shoes", "/ʃuːz/", "noun", "coverings worn on the feet", "giày", "She bought new shoes.", "Cô ấy mua giày mới.", "A2"),
    ("boots", "/buːts/", "noun", "footwear covering the foot and ankle", "ủng/giày bốt", "She wore boots in the rain.", "Cô ấy mang ủng khi trời mưa.", "A2"),
    ("glasses", "/ˈɡlɑːsɪz/", "noun", "lenses in a frame worn to aid sight", "kính mắt", "She wears glasses to read.", "Cô ấy đeo kính để đọc.", "A2"),
    ("uniform", "/ˈjuːnɪfɔːrm/", "noun", "clothing worn by members of a group", "đồng phục", "Students wear a uniform.", "Học sinh mặc đồng phục.", "A2"),
    # B1 - Communication & media
    ("headline", "/ˈhedlaɪn/", "noun", "a title of a newspaper article", "tiêu đề", "Read the headlines every morning.", "Đọc tiêu đề báo mỗi sáng.", "B1"),
    ("broadcast", "/ˈbrɔːdkɑːst/", "verb", "to send out by radio or TV", "phát sóng", "The game was broadcast live.", "Trận đấu được phát sóng trực tiếp.", "B1"),
    ("advertisement", "/ədˈvɜːrtɪsmənt/", "noun", "a notice promoting a product", "quảng cáo", "The advertisement was on TV.", "Quảng cáo được chiếu trên TV.", "B1"),
    ("opinion", "/əˈpɪnjən/", "noun", "a personal view on a topic", "ý kiến", "Everyone has their own opinion.", "Mọi người đều có ý kiến của riêng mình.", "B1"),
    ("debate", "/dɪˈbeɪt/", "noun", "a formal discussion of opposing views", "tranh luận", "They held a debate on the topic.", "Họ tổ chức một buổi tranh luận về chủ đề đó.", "B1"),
    ("influence", "/ˈɪnfluəns/", "noun", "the power to affect someone", "ảnh hưởng", "Social media has a big influence.", "Mạng xã hội có ảnh hưởng lớn.", "B1"),
    ("publish", "/ˈpʌblɪʃ/", "verb", "to make information available to the public", "xuất bản", "She published her first book.", "Cô ấy xuất bản cuốn sách đầu tiên.", "B1"),
    ("subscribe", "/səbˈskraɪb/", "verb", "to pay for regular delivery of something", "đăng ký", "Subscribe to the newsletter.", "Đăng ký nhận bản tin.", "B1"),
    ("review", "/rɪˈvjuː/", "noun", "a critical assessment of something", "đánh giá/nhận xét", "Read the movie review.", "Đọc nhận xét phim.", "B1"),
    ("comment", "/ˈkɒment/", "noun", "a written or spoken remark", "bình luận", "Leave a comment below.", "Để lại bình luận bên dưới.", "B1"),
    # B1 - Money & shopping
    ("discount", "/ˈdɪskaʊnt/", "noun", "a reduction in price", "giảm giá", "There is a 20% discount today.", "Hôm nay có giảm giá 20%.", "B1"),
    ("refund", "/ˈriːfʌnd/", "noun", "money returned after a purchase", "hoàn tiền", "She requested a refund.", "Cô ấy yêu cầu hoàn tiền.", "B1"),
    ("afford", "/əˈfɔːrd/", "verb", "to have enough money to buy something", "đủ khả năng mua", "Can you afford the rent?", "Bạn có đủ tiền trả tiền thuê không?", "B1"),
    ("expensive", "/ɪkˈspensɪv/", "adjective", "costing a lot of money", "đắt tiền", "That watch is very expensive.", "Chiếc đồng hồ đó rất đắt tiền.", "B1"),
    ("cheap", "/tʃiːp/", "adjective", "not expensive", "rẻ", "The market sells cheap vegetables.", "Chợ bán rau củ rẻ.", "B1"),
    ("bargain", "/ˈbɑːrɡɪn/", "noun", "something bought at a low price", "hàng giá rẻ", "I got a great bargain at the sale.", "Tôi mua được hàng giá rẻ trong đợt giảm giá.", "B1"),
    ("currency", "/ˈkʌrənsi/", "noun", "the money used in a country", "tiền tệ", "What is the local currency?", "Tiền tệ địa phương là gì?", "B1"),
    ("exchange", "/ɪksˈtʃeɪndʒ/", "verb", "to swap one thing for another", "đổi", "Where can I exchange money?", "Tôi có thể đổi tiền ở đâu?", "B1"),
    ("savings", "/ˈseɪvɪŋz/", "noun", "money saved for future use", "tiết kiệm", "She has savings in the bank.", "Cô ấy có tiền tiết kiệm trong ngân hàng.", "B1"),
    ("loan", "/ləʊn/", "noun", "money borrowed to be repaid", "khoản vay", "He took out a bank loan.", "Anh ấy vay tiền ngân hàng.", "B1"),
    ("interest", "/ˈɪntrəst/", "noun", "money paid for borrowing money", "lãi suất", "The interest rate is 5%.", "Lãi suất là 5%.", "B1"),
    ("mortgage", "/ˈmɔːrɡɪdʒ/", "noun", "a loan used to buy property", "thế chấp", "They applied for a mortgage.", "Họ đăng ký vay thế chấp.", "B1"),
    ("investment", "/ɪnˈvestmənt/", "noun", "money used to make more money", "đầu tư", "She made a good investment.", "Cô ấy đầu tư tốt.", "B1"),
    # B2 - Society & politics
    ("democracy", "/dɪˈmɒkrəsi/", "noun", "a system where people vote for leaders", "dân chủ", "Democracy protects civil rights.", "Dân chủ bảo vệ quyền dân sự.", "B2"),
    ("government", "/ˈɡʌvənmənt/", "noun", "the group that rules a country", "chính phủ", "The government passed a new law.", "Chính phủ thông qua luật mới.", "B2"),
    ("parliament", "/ˈpɑːrləmənt/", "noun", "the group that makes laws", "nghị viện", "Parliament voted on the bill.", "Nghị viện bỏ phiếu về dự luật.", "B2"),
    ("policy", "/ˈpɒlɪsi/", "noun", "a plan or rule followed by an organization", "chính sách", "The new policy reduces taxes.", "Chính sách mới giảm thuế.", "B2"),
    ("election", "/ɪˈlekʃən/", "noun", "a process of voting to choose leaders", "bầu cử", "The election will be held next month.", "Cuộc bầu cử sẽ được tổ chức tháng tới.", "B2"),
    ("campaign", "/kæmˈpeɪn/", "noun", "an organized effort to achieve a goal", "chiến dịch", "The campaign raised awareness.", "Chiến dịch nâng cao nhận thức.", "B2"),
    ("protest", "/ˈprəʊtest/", "noun", "a public expression of disagreement", "biểu tình", "Thousands joined the protest.", "Hàng ngàn người tham gia biểu tình.", "B2"),
    ("regulation", "/ˌreɡjuˈleɪʃən/", "noun", "an official rule or law", "quy định", "New regulations protect workers.", "Quy định mới bảo vệ người lao động.", "B2"),
    ("legislation", "/ˌledʒɪˈsleɪʃən/", "noun", "laws made by a government", "luật pháp", "New legislation was introduced.", "Luật mới được ban hành.", "B2"),
    ("constitution", "/ˌkɒnstɪˈtjuːʃən/", "noun", "the fundamental laws of a country", "hiến pháp", "The constitution protects rights.", "Hiến pháp bảo vệ quyền lợi.", "B2"),
    ("justice", "/ˈdʒʌstɪs/", "noun", "fair treatment in a legal system", "công lý", "They fought for justice.", "Họ đấu tranh cho công lý.", "B2"),
    ("equality", "/ɪˈkwɒlɪti/", "noun", "being treated the same regardless of differences", "bình đẳng", "She advocates for gender equality.", "Cô ấy ủng hộ bình đẳng giới.", "B2"),
    ("poverty", "/ˈpɒvərti/", "noun", "the state of being very poor", "đói nghèo", "Education helps reduce poverty.", "Giáo dục giúp giảm đói nghèo.", "B2"),
    ("welfare", "/ˈwelfeər/", "noun", "the health and happiness of a person", "phúc lợi", "Child welfare is very important.", "Phúc lợi trẻ em rất quan trọng.", "B2"),
    ("immigration", "/ˌɪmɪˈɡreɪʃən/", "noun", "moving to another country permanently", "nhập cư", "Immigration policies are strict.", "Chính sách nhập cư rất nghiêm ngặt.", "B2"),
    # C1 - Advanced verbs
    ("accelerate", "/əkˈseləreɪt/", "verb", "to increase speed or rate", "tăng tốc", "The car accelerated quickly.", "Chiếc xe tăng tốc nhanh chóng.", "C1"),
    ("accumulate", "/əˈkjuːmjuleɪt/", "verb", "to gather or build up over time", "tích lũy", "She accumulated years of experience.", "Cô ấy tích lũy nhiều năm kinh nghiệm.", "C1"),
    ("advocate", "/ˈædvəkeɪt/", "verb", "to publicly support something", "ủng hộ", "He advocates for human rights.", "Anh ấy ủng hộ quyền con người.", "C1"),
    ("alleviate", "/əˈliːvieɪt/", "verb", "to make suffering less severe", "giảm nhẹ", "Medicine alleviates pain.", "Thuốc giảm nhẹ cơn đau.", "C1"),
    ("anticipate", "/ænˈtɪsɪpeɪt/", "verb", "to expect something to happen", "dự đoán", "We anticipate strong growth.", "Chúng tôi dự đoán tăng trưởng mạnh.", "C1"),
    ("collaborate", "/kəˈlæbəreɪt/", "verb", "to work together on something", "hợp tác", "They collaborated on the project.", "Họ hợp tác trong dự án.", "C1"),
    ("compensate", "/ˈkɒmpenseɪt/", "verb", "to give something to make up for loss", "bồi thường", "The company compensated the victims.", "Công ty bồi thường cho các nạn nhân.", "C1"),
    ("contradict", "/ˌkɒntrəˈdɪkt/", "verb", "to say the opposite of something", "mâu thuẫn", "Your actions contradict your words.", "Hành động của bạn mâu thuẫn với lời nói.", "C1"),
    ("demonstrate", "/ˈdemənstreɪt/", "verb", "to show something clearly", "minh chứng", "He demonstrated the technique.", "Anh ấy minh chứng kỹ thuật.", "C1"),
    ("distinguish", "/dɪˈstɪŋɡwɪʃ/", "verb", "to recognize a difference between things", "phân biệt", "Can you distinguish the two colours?", "Bạn có thể phân biệt hai màu không?", "C1"),
    ("dominate", "/ˈdɒmɪneɪt/", "verb", "to have control or power over", "thống trị", "She dominated the competition.", "Cô ấy thống trị cuộc thi.", "C1"),
    ("enhance", "/ɪnˈhɑːns/", "verb", "to improve the quality of something", "nâng cao", "Music can enhance your mood.", "Âm nhạc có thể nâng cao tâm trạng.", "C1"),
    ("exaggerate", "/ɪɡˈzædʒəreɪt/", "verb", "to make something seem more than it is", "phóng đại", "Don't exaggerate the problem.", "Đừng phóng đại vấn đề.", "C1"),
    ("exploit", "/ɪkˈsplɔɪt/", "verb", "to use unfairly for personal gain", "khai thác/lợi dụng", "Do not exploit workers.", "Đừng lợi dụng người lao động.", "C1"),
    ("fluctuate", "/ˈflʌktʃueɪt/", "verb", "to change frequently", "biến động", "Prices fluctuate with demand.", "Giá cả biến động theo nhu cầu.", "C1"),
    ("generate", "/ˈdʒenəreɪt/", "verb", "to produce or create something", "tạo ra", "Solar panels generate electricity.", "Tấm pin mặt trời tạo ra điện.", "C1"),
    ("implement", "/ˈɪmplɪment/", "verb", "to put a plan into action", "thực hiện", "They implemented the new system.", "Họ thực hiện hệ thống mới.", "C1"),
    ("imply", "/ɪmˈplaɪ/", "verb", "to suggest without saying directly", "ngụ ý", "What does his silence imply?", "Sự im lặng của anh ấy ngụ ý gì?", "C1"),
    ("incorporate", "/ɪnˈkɔːrpəreɪt/", "verb", "to include something as part of a whole", "kết hợp", "Incorporate feedback into your work.", "Kết hợp phản hồi vào công việc.", "C1"),
    ("indicate", "/ˈɪndɪkeɪt/", "verb", "to show or point to something", "chỉ ra", "The data indicates a problem.", "Dữ liệu chỉ ra một vấn đề.", "C1"),
    # C1 - Advanced adjectives
    ("ambivalent", "/æmˈbɪvələnt/", "adjective", "having mixed feelings about something", "lưỡng lự", "She was ambivalent about the offer.", "Cô ấy lưỡng lự về đề nghị đó.", "C1"),
    ("coherent", "/kəʊˈhɪərənt/", "adjective", "logical and consistent", "mạch lạc", "His argument was clear and coherent.", "Lập luận của anh ấy rõ ràng và mạch lạc.", "C1"),
    ("comprehensive", "/ˌkɒmprɪˈhensɪv/", "adjective", "including everything that is necessary", "toàn diện", "She wrote a comprehensive report.", "Cô ấy viết một báo cáo toàn diện.", "C1"),
    ("controversial", "/ˌkɒntrəˈvɜːrʃəl/", "adjective", "causing disagreement or debate", "gây tranh cãi", "The decision was controversial.", "Quyết định đó gây tranh cãi.", "C1"),
    ("credible", "/ˈkredɪbəl/", "adjective", "able to be believed or trusted", "đáng tin cậy", "She is a credible witness.", "Cô ấy là nhân chứng đáng tin cậy.", "C1"),
    ("detrimental", "/ˌdetrɪˈmentəl/", "adjective", "causing harm or damage", "có hại", "Smoking is detrimental to health.", "Hút thuốc có hại cho sức khỏe.", "C1"),
    ("diverse", "/daɪˈvɜːrs/", "adjective", "very different from each other", "đa dạng", "The team has diverse backgrounds.", "Nhóm có nhiều nền tảng khác nhau.", "C1"),
    ("explicit", "/ɪkˈsplɪsɪt/", "adjective", "stated clearly and in detail", "rõ ràng", "Give explicit instructions.", "Đưa ra hướng dẫn rõ ràng.", "C1"),
    ("inherent", "/ɪnˈhɪərənt/", "adjective", "existing as a natural part of something", "vốn có", "There are inherent risks.", "Có những rủi ro vốn có.", "C1"),
    ("pragmatic", "/præɡˈmætɪk/", "adjective", "dealing with things in a practical way", "thực dụng", "She takes a pragmatic approach.", "Cô ấy có cách tiếp cận thực dụng.", "C1"),
    # TOEIC - HR & Office
    ("applicant", "/ˈæplɪkənt/", "noun", "someone applying for a job", "ứng viên", "Ten applicants were shortlisted.", "Mười ứng viên được chọn vào vòng cuối.", "TOEIC"),
    ("recruitment", "/rɪˈkruːtmənt/", "noun", "the process of hiring new staff", "tuyển dụng", "Recruitment is ongoing.", "Tuyển dụng đang diễn ra.", "TOEIC"),
    ("resume", "/ˈrezjumeɪ/", "noun", "a document listing your work experience", "hồ sơ xin việc", "Update your resume before applying.", "Cập nhật hồ sơ trước khi nộp đơn.", "TOEIC"),
    ("reference", "/ˈrefərəns/", "noun", "a person who supports your application", "người tham chiếu", "Provide two professional references.", "Cung cấp hai người tham chiếu chuyên nghiệp.", "TOEIC"),
    ("probation", "/prəˈbeɪʃən/", "noun", "a trial period for a new employee", "thử việc", "He is on probation for 3 months.", "Anh ấy đang trong thời gian thử việc 3 tháng.", "TOEIC"),
    ("appraisal", "/əˈpreɪzəl/", "noun", "a formal assessment of performance", "đánh giá hiệu suất", "Annual appraisals motivate staff.", "Đánh giá hàng năm thúc đẩy nhân viên.", "TOEIC"),
    ("incentive", "/ɪnˈsentɪv/", "noun", "something that encourages action", "khuyến khích", "A bonus is a financial incentive.", "Tiền thưởng là khuyến khích tài chính.", "TOEIC"),
    ("reimburse", "/ˌriːɪmˈbɜːrs/", "verb", "to pay back money that was spent", "hoàn trả", "The company reimbursed his expenses.", "Công ty hoàn trả chi phí của anh ấy.", "TOEIC"),
    ("turnover", "/ˈtɜːrnˌəʊvər/", "noun", "the rate at which employees leave", "tỷ lệ thôi việc", "High turnover costs companies money.", "Tỷ lệ thôi việc cao tốn kém tiền.", "TOEIC"),
    ("workforce", "/ˈwɜːrkfɔːrs/", "noun", "all the people employed in a company", "lực lượng lao động", "The workforce is expanding.", "Lực lượng lao động đang mở rộng.", "TOEIC"),
    ("productivity", "/ˌprɒdʌkˈtɪvɪti/", "noun", "efficiency in producing results", "năng suất", "Technology boosts productivity.", "Công nghệ tăng năng suất.", "TOEIC"),
    ("collaboration", "/kəˌlæbəˈreɪʃən/", "noun", "working jointly with others", "sự hợp tác", "Collaboration leads to innovation.", "Hợp tác dẫn đến đổi mới.", "TOEIC"),
    ("initiative", "/ɪˈnɪʃətɪv/", "noun", "the ability to act without being told", "sáng kiến", "She showed great initiative.", "Cô ấy thể hiện sáng kiến tuyệt vời.", "TOEIC"),
    ("delegation", "/ˌdelɪˈɡeɪʃən/", "noun", "the assignment of tasks to others", "phân quyền", "Good leadership includes delegation.", "Lãnh đạo tốt bao gồm phân quyền.", "TOEIC"),
    ("accountability", "/əˌkaʊntəˈbɪlɪti/", "noun", "being responsible for one's actions", "trách nhiệm giải trình", "Accountability improves performance.", "Trách nhiệm giải trình cải thiện hiệu suất.", "TOEIC"),
    ("confidential", "/ˌkɒnfɪˈdenʃəl/", "adjective", "secret and not for public knowledge", "bảo mật", "This document is confidential.", "Tài liệu này là bảo mật.", "TOEIC"),
    ("correspondence", "/ˌkɒrɪˈspɒndəns/", "noun", "letters or emails exchanged", "thư từ", "All correspondence must be archived.", "Tất cả thư từ phải được lưu trữ.", "TOEIC"),
    ("teleconference", "/ˈtelɪˌkɒnfərəns/", "noun", "a meeting conducted remotely by phone", "hội nghị từ xa", "We held a teleconference with Japan.", "Chúng tôi tổ chức hội nghị từ xa với Nhật Bản.", "TOEIC"),
    ("outsource", "/ˈaʊtsɔːrs/", "verb", "to hire an external company for work", "thuê ngoài", "They outsourced customer support.", "Họ thuê ngoài bộ phận hỗ trợ khách hàng.", "TOEIC"),
    ("compliance", "/kəmˈplaɪəns/", "noun", "following rules and regulations", "tuân thủ", "Compliance with the law is required.", "Tuân thủ pháp luật là bắt buộc.", "TOEIC"),
    # B2 - Science & research
    ("experiment", "/ɪkˈsperɪmənt/", "noun", "a test done to discover something", "thí nghiệm", "The scientist conducted an experiment.", "Nhà khoa học tiến hành thí nghiệm.", "B2"),
    ("observation", "/ˌɒbzəˈveɪʃən/", "noun", "the act of watching carefully", "quan sát", "Make careful observations.", "Thực hiện quan sát cẩn thận.", "B2"),
    ("sample", "/ˈsɑːmpəl/", "noun", "a small part representing a whole", "mẫu", "They tested a soil sample.", "Họ kiểm tra mẫu đất.", "B2"),
    ("variable", "/ˈveəriəbəl/", "noun", "a factor that can change in an experiment", "biến số", "Control all variables in the test.", "Kiểm soát tất cả biến số trong thử nghiệm.", "B2"),
    ("accurate", "/ˈækjərɪt/", "adjective", "correct and without errors", "chính xác", "The measurement must be accurate.", "Phép đo phải chính xác.", "B2"),
    ("reliable", "/rɪˈlaɪəbəl/", "adjective", "consistently good and trustworthy", "đáng tin cậy", "Use reliable sources.", "Sử dụng nguồn đáng tin cậy.", "B2"),
    ("valid", "/ˈvælɪd/", "adjective", "based on sound reasoning", "hợp lệ", "Is this a valid conclusion?", "Đây có phải là kết luận hợp lệ không?", "B2"),
    ("replicate", "/ˈreplɪkeɪt/", "verb", "to repeat an experiment to confirm results", "sao chép/lặp lại", "Can you replicate the findings?", "Bạn có thể lặp lại kết quả không?", "B2"),
    ("statistic", "/stəˈtɪstɪk/", "noun", "a fact expressed as a number", "thống kê", "The statistics are alarming.", "Các số liệu thống kê đáng lo ngại.", "B2"),
    ("formula", "/ˈfɔːrmjʊlə/", "noun", "a mathematical or scientific rule", "công thức", "Use the formula to solve it.", "Dùng công thức để giải nó.", "B2"),
    # B1 - Nature & animals
    ("wildlife", "/ˈwaɪldlaɪf/", "noun", "animals and plants in natural habitats", "động vật hoang dã", "Protect wildlife from poaching.", "Bảo vệ động vật hoang dã khỏi săn trộm.", "B1"),
    ("habitat", "/ˈhæbɪtæt/", "noun", "the natural home of an animal", "môi trường sống", "Polar bears lose their habitat.", "Gấu Bắc Cực đang mất môi trường sống.", "B1"),
    ("extinct", "/ɪkˈstɪŋkt/", "adjective", "no longer existing", "tuyệt chủng", "Dinosaurs are extinct.", "Khủng long đã tuyệt chủng.", "B1"),
    ("species", "/ˈspiːʃiːz/", "noun", "a group of similar living things", "loài", "Many species are endangered.", "Nhiều loài đang có nguy cơ tuyệt chủng.", "B1"),
    ("prey", "/preɪ/", "noun", "an animal hunted by another", "con mồi", "The mouse is the cat's prey.", "Con chuột là con mồi của mèo.", "B1"),
    ("predator", "/ˈpredətər/", "noun", "an animal that hunts others", "động vật săn mồi", "Lions are apex predators.", "Sư tử là thú săn mồi đứng đầu chuỗi thức ăn.", "B1"),
    ("migrate", "/maɪˈɡreɪt/", "verb", "to move to another region seasonally", "di cư", "Birds migrate south in winter.", "Chim di cư về phía nam vào mùa đông.", "B1"),
    ("domesticate", "/dəˈmestɪkeɪt/", "verb", "to tame animals for human use", "thuần hóa", "Humans domesticated dogs long ago.", "Con người đã thuần hóa chó từ lâu.", "B1"),
    ("insect", "/ˈɪnsekt/", "noun", "a small animal with six legs", "côn trùng", "Bees are useful insects.", "Ong là loài côn trùng hữu ích.", "B1"),
    ("reptile", "/ˈreptaɪl/", "noun", "a cold-blooded animal with scales", "bò sát", "Snakes are reptiles.", "Rắn là loài bò sát.", "B1"),
    # A2 - Household objects
    ("fridge", "/frɪdʒ/", "noun", "a machine that keeps food cold", "tủ lạnh", "Put the milk in the fridge.", "Để sữa vào tủ lạnh.", "A2"),
    ("oven", "/ˈʌvən/", "noun", "a device for baking food", "lò nướng", "Bake the cake in the oven.", "Nướng bánh trong lò.", "A2"),
    ("microwave", "/ˈmaɪkrəweɪv/", "noun", "a machine that heats food quickly", "lò vi sóng", "Heat the soup in the microwave.", "Hâm nóng súp trong lò vi sóng.", "A2"),
    ("washing machine", "/ˈwɒʃɪŋ məˌʃiːn/", "noun", "a machine that washes clothes", "máy giặt", "Put the clothes in the washing machine.", "Cho quần áo vào máy giặt.", "A2"),
    ("vacuum cleaner", "/ˈvækjuəm ˌkliːnər/", "noun", "a machine that sucks up dust", "máy hút bụi", "Use the vacuum cleaner on the carpet.", "Dùng máy hút bụi trên thảm.", "A2"),
    ("air conditioner", "/ˈeər kənˌdɪʃənər/", "noun", "a machine that cools or heats air", "máy điều hòa", "Turn on the air conditioner.", "Bật máy điều hòa lên.", "A2"),
    ("television", "/ˈtelɪvɪʒən/", "noun", "a device that shows moving pictures", "ti vi", "We watch TV in the evening.", "Chúng tôi xem ti vi vào buổi tối.", "A2"),
    ("remote control", "/rɪˌməʊt kənˈtrəʊl/", "noun", "a device to control electronics from a distance", "điều khiển từ xa", "Where is the remote control?", "Điều khiển từ xa ở đâu?", "A2"),
    ("kettle", "/ˈketəl/", "noun", "a container for boiling water", "ấm đun nước", "Boil water in the kettle.", "Đun nước trong ấm.", "A2"),
    ("blender", "/ˈblendər/", "noun", "a machine for mixing food", "máy xay sinh tố", "Use a blender to make smoothies.", "Dùng máy xay sinh tố để làm sinh tố.", "A2"),
    ("toaster", "/ˈtəʊstər/", "noun", "a machine for toasting bread", "máy nướng bánh mì", "Make toast in the toaster.", "Nướng bánh mì bằng máy.", "A2"),
    ("shelf", "/ʃelf/", "noun", "a flat board fixed to a wall", "kệ", "Books are on the shelf.", "Sách ở trên kệ.", "A2"),
    ("drawer", "/drɔːr/", "noun", "a box that slides in and out of furniture", "ngăn kéo", "The keys are in the drawer.", "Chìa khóa ở trong ngăn kéo.", "A2"),
    ("mirror", "/ˈmɪrər/", "noun", "a reflective glass surface", "gương", "She looked in the mirror.", "Cô ấy nhìn vào gương.", "A2"),
    ("curtain", "/ˈkɜːrtən/", "noun", "a hanging cloth covering a window", "rèm cửa", "Close the curtains at night.", "Kéo rèm lại vào ban đêm.", "A2"),
    ("carpet", "/ˈkɑːrpɪt/", "noun", "a thick fabric covering the floor", "thảm", "The carpet is soft and warm.", "Thảm mềm và ấm áp.", "A2"),
    ("pillow", "/ˈpɪləʊ/", "noun", "a soft cushion for the head", "gối", "She rested her head on the pillow.", "Cô ấy tựa đầu vào gối.", "A2"),
    ("blanket", "/ˈblæŋkɪt/", "noun", "a warm covering for a bed", "chăn", "Pull the blanket up.", "Kéo chăn lên.", "A2"),
    ("towel", "/ˈtaʊəl/", "noun", "a cloth used for drying", "khăn tắm", "Use a clean towel.", "Dùng khăn tắm sạch.", "A2"),
    ("soap", "/səʊp/", "noun", "a substance used for washing", "xà phòng", "Wash your hands with soap.", "Rửa tay bằng xà phòng.", "A2"),
    ("shampoo", "/ʃæmˈpuː/", "noun", "a liquid used for washing hair", "dầu gội", "Use shampoo to wash your hair.", "Dùng dầu gội để gội đầu.", "A2"),
    ("toothbrush", "/ˈtuːθbrʌʃ/", "noun", "a brush used to clean teeth", "bàn chải đánh răng", "Brush your teeth twice a day.", "Đánh răng hai lần mỗi ngày.", "A2"),
    ("toothpaste", "/ˈtuːθpeɪst/", "noun", "a paste used with a toothbrush", "kem đánh răng", "Apply toothpaste to the brush.", "Cho kem đánh răng lên bàn chải.", "A2"),
    # B1 - Describing things
    ("ancient", "/ˈeɪnʃənt/", "adjective", "very old, from a long time ago", "cổ xưa", "The ancient ruins are fascinating.", "Di tích cổ đại rất hấp dẫn.", "B1"),
    ("modern", "/ˈmɒdərn/", "adjective", "relating to the present time", "hiện đại", "The city has a modern skyline.", "Thành phố có đường chân trời hiện đại.", "B1"),
    ("traditional", "/trəˈdɪʃənəl/", "adjective", "following long-established customs", "truyền thống", "They enjoyed traditional food.", "Họ thưởng thức món ăn truyền thống.", "B1"),
    ("typical", "/ˈtɪpɪkəl/", "adjective", "showing the usual characteristics", "điển hình", "This is a typical example.", "Đây là một ví dụ điển hình.", "B1"),
    ("rare", "/reər/", "adjective", "not common or not often happening", "hiếm", "Finding a job is rare here.", "Tìm việc làm ở đây rất hiếm.", "B1"),
    ("ordinary", "/ˈɔːrdɪneri/", "adjective", "not special or unusual", "bình thường", "It was an ordinary day.", "Đó là một ngày bình thường.", "B1"),
    ("unique", "/juːˈniːk/", "adjective", "being the only one of its kind", "độc đáo", "Her style is truly unique.", "Phong cách của cô ấy thực sự độc đáo.", "B1"),
    ("complex", "/ˈkɒmpleks/", "adjective", "made of many parts", "phức tạp", "The problem is very complex.", "Vấn đề rất phức tạp.", "B1"),
    ("obvious", "/ˈɒbviəs/", "adjective", "easy to see or understand", "rõ ràng", "The answer is obvious.", "Câu trả lời rõ ràng.", "B1"),
    ("enormous", "/ɪˈnɔːrməs/", "adjective", "extremely large", "khổng lồ", "The building is enormous.", "Tòa nhà khổng lồ.", "B1"),
    ("tiny", "/ˈtaɪni/", "adjective", "very small", "rất nhỏ", "The baby has tiny hands.", "Em bé có đôi tay rất nhỏ.", "B1"),
    ("narrow", "/ˈnærəʊ/", "adjective", "small in width", "hẹp", "The road is too narrow.", "Con đường quá hẹp.", "B1"),
    ("wide", "/waɪd/", "adjective", "large in distance from side to side", "rộng", "The river is very wide.", "Con sông rất rộng.", "B1"),
    ("deep", "/diːp/", "adjective", "going far down from the surface", "sâu", "The ocean is very deep.", "Đại dương rất sâu.", "B1"),
    ("shallow", "/ˈʃæləʊ/", "adjective", "not very deep", "nông", "The water here is shallow.", "Nước ở đây nông.", "B1"),
    ("smooth", "/smuːð/", "adjective", "having an even surface", "mượt mà", "The road surface is smooth.", "Mặt đường nhẵn bóng.", "B1"),
    ("rough", "/rʌf/", "adjective", "having an uneven surface", "gồ ghề", "The mountain path is rough.", "Con đường núi gồ ghề.", "B1"),
]


def run():
    created = 0
    skipped = 0
    for item in WORDS:
        text, phonetic, pos, def_en, def_vi, ex_en, ex_vi, level = item
        _, is_new = Word.objects.get_or_create(
            text=text,
            defaults={
                "phonetic": phonetic,
                "part_of_speech": pos,
                "definition_en": def_en,
                "definition_vi": def_vi,
                "example_en": ex_en,
                "example_vi": ex_vi,
                "level": level,
            },
        )
        if is_new:
            created += 1
        else:
            skipped += 1
    total = Word.objects.count()
    print(f"Hoàn thành: {created} từ mới, {skipped} bỏ qua.")
    print(f"Tổng từ vựng hiện tại: {total}")


run()
