# Generated by Django 4.2.13 on 2026-05-14 04:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('learning', '0004_rename_notif_user_read_idx_notificatio_user_id_a4dd5c_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Tên khóa học')),
                ('slug', models.SlugField(max_length=80, unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, verbose_name='Mô tả')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang hoạt động')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Khóa học',
                'verbose_name_plural': 'Khóa học',
                'db_table': 'courses',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Tiêu đề')),
                ('description', models.TextField(blank=True, verbose_name='Mô tả')),
                ('order_index', models.PositiveIntegerField(default=0, verbose_name='Thứ tự')),
                ('required_lessons_to_unlock', models.PositiveIntegerField(default=1, verbose_name='Số bài tối thiểu để mở unit kế')),
                ('is_published', models.BooleanField(default=False, verbose_name='Đã công bố')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='learning.course', verbose_name='Khóa học')),
            ],
            options={
                'verbose_name': 'Unit',
                'verbose_name_plural': 'Units',
                'db_table': 'units',
                'ordering': ['order_index'],
                'unique_together': {('course', 'order_index')},
            },
        ),
        migrations.CreateModel(
            name='LearningSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('started', 'Đang học'), ('completed', 'Hoàn thành'), ('abandoned', 'Bỏ dở')], default='started', max_length=16, verbose_name='Trạng thái')),
                ('total_answered', models.PositiveIntegerField(default=0, verbose_name='Tổng câu đã trả lời')),
                ('correct_answered', models.PositiveIntegerField(default=0, verbose_name='Tổng câu đúng')),
                ('xp_earned', models.PositiveIntegerField(default=0, verbose_name='XP kiếm được')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='Bắt đầu lúc')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Kết thúc lúc')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='learning.lesson', verbose_name='Bài học')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='learning.unit', verbose_name='Unit')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_sessions', to=settings.AUTH_USER_MODEL, verbose_name='Người dùng')),
            ],
            options={
                'verbose_name': 'Phiên học',
                'verbose_name_plural': 'Phiên học',
                'db_table': 'learning_sessions',
            },
        ),
        migrations.CreateModel(
            name='ExerciseAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_index', models.PositiveIntegerField(verbose_name='Bước số')),
                ('exercise_type', models.CharField(default='mc', max_length=50, verbose_name='Loại bài')),
                ('prompt', models.TextField(blank=True, verbose_name='Nội dung câu hỏi')),
                ('submitted_answer', models.JSONField(blank=True, default=dict, verbose_name='Đáp án gửi lên')),
                ('is_correct', models.BooleanField(verbose_name='Đúng/Sai')),
                ('response_ms', models.PositiveIntegerField(default=0, verbose_name='Thời gian trả lời (ms)')),
                ('awarded_xp', models.PositiveIntegerField(default=0, verbose_name='XP nhận được')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='learning.learningsession', verbose_name='Phiên học')),
            ],
            options={
                'verbose_name': 'Lượt trả lời',
                'verbose_name_plural': 'Lượt trả lời',
                'db_table': 'exercise_attempts',
            },
        ),
        migrations.CreateModel(
            name='UserUnitProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_lessons', models.PositiveIntegerField(default=0, verbose_name='Số bài đã hoàn thành')),
                ('total_xp_earned', models.PositiveIntegerField(default=0, verbose_name='XP kiếm được trong unit')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Bắt đầu lúc')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Hoàn thành lúc')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='learning.unit', verbose_name='Unit')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unit_progress', to=settings.AUTH_USER_MODEL, verbose_name='Người dùng')),
            ],
            options={
                'verbose_name': 'Tiến độ Unit',
                'verbose_name_plural': 'Tiến độ Unit',
                'db_table': 'user_unit_progress',
                'indexes': [models.Index(fields=['user', 'unit'], name='user_unit_p_user_id_ee44cd_idx')],
                'unique_together': {('user', 'unit')},
            },
        ),
        migrations.CreateModel(
            name='UnitLesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_index', models.PositiveIntegerField(default=0, verbose_name='Thứ tự')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unit_links', to='learning.lesson', verbose_name='Bài học')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unit_lessons', to='learning.unit', verbose_name='Unit')),
            ],
            options={
                'verbose_name': 'Bài trong Unit',
                'verbose_name_plural': 'Bài trong Unit',
                'db_table': 'unit_lessons',
                'ordering': ['order_index'],
                'unique_together': {('unit', 'order_index'), ('unit', 'lesson')},
            },
        ),
        migrations.AddIndex(
            model_name='learningsession',
            index=models.Index(fields=['user', 'status'], name='learning_se_user_id_d61245_idx'),
        ),
        migrations.AddIndex(
            model_name='learningsession',
            index=models.Index(fields=['unit', 'lesson'], name='learning_se_unit_id_13a18f_idx'),
        ),
        migrations.AddIndex(
            model_name='learningsession',
            index=models.Index(fields=['started_at'], name='learning_se_started_f47896_idx'),
        ),
        migrations.AddIndex(
            model_name='exerciseattempt',
            index=models.Index(fields=['session', 'step_index'], name='exercise_at_session_bddeb3_idx'),
        ),
        migrations.AddIndex(
            model_name='exerciseattempt',
            index=models.Index(fields=['created_at'], name='exercise_at_created_209e2d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='exerciseattempt',
            unique_together={('session', 'step_index')},
        ),
    ]
