# Generated by Django 4.2.13 on 2026-05-14 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0005_course_unit_learningsession_exerciseattempt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningsession',
            name='exercises',
            field=models.JSONField(blank=True, default=list, verbose_name='Bộ bài tập'),
        ),
        migrations.AddField(
            model_name='learningsession',
            name='session_type',
            field=models.CharField(choices=[('lesson', 'Lesson'), ('checkpoint', 'Checkpoint')], default='lesson', max_length=16, verbose_name='Loại phiên'),
        ),
        migrations.AddField(
            model_name='userunitprogress',
            name='checkpoint_passed',
            field=models.BooleanField(default=False, verbose_name='Đã qua checkpoint'),
        ),
        migrations.AddField(
            model_name='userunitprogress',
            name='checkpoint_passed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Qua checkpoint lúc'),
        ),
    ]
