# Generated by Django 4.2.13 on 2026-05-14 05:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('learning', '0006_learningsession_exercises_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_minutes', models.PositiveIntegerField(choices=[(5, '5 minutes'), (10, '10 minutes'), (15, '15 minutes')], default=10, verbose_name='Daily target minutes')),
                ('reward_xp', models.PositiveIntegerField(default=15, verbose_name='Reward XP')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='daily_goal', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Daily goal',
                'verbose_name_plural': 'Daily goals',
                'db_table': 'daily_goals',
            },
        ),
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['name'], 'verbose_name': 'Course', 'verbose_name_plural': 'Courses'},
        ),
        migrations.AlterModelOptions(
            name='exerciseattempt',
            options={'verbose_name': 'Exercise attempt', 'verbose_name_plural': 'Exercise attempts'},
        ),
        migrations.AlterModelOptions(
            name='learningsession',
            options={'verbose_name': 'Learning session', 'verbose_name_plural': 'Learning session'},
        ),
        migrations.AlterModelOptions(
            name='unitlesson',
            options={'ordering': ['order_index'], 'verbose_name': 'Unit lesson', 'verbose_name_plural': 'Unit lessons'},
        ),
        migrations.AlterModelOptions(
            name='userunitprogress',
            options={'verbose_name': 'User unit progress', 'verbose_name_plural': 'User unit progress'},
        ),
        migrations.AddField(
            model_name='userstreak',
            name='last_freeze_used_on',
            field=models.DateField(blank=True, null=True, verbose_name='Ngay dung freeze gan nhat'),
        ),
        migrations.AddField(
            model_name='userstreak',
            name='streak_freezes',
            field=models.PositiveIntegerField(default=0, verbose_name='So streak freeze'),
        ),
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='course',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Course name'),
        ),
        migrations.AlterField(
            model_name='exerciseattempt',
            name='awarded_xp',
            field=models.PositiveIntegerField(default=0, verbose_name='Awarded XP'),
        ),
        migrations.AlterField(
            model_name='exerciseattempt',
            name='exercise_type',
            field=models.CharField(default='mc', max_length=50, verbose_name='Exercise type'),
        ),
        migrations.AlterField(
            model_name='exerciseattempt',
            name='is_correct',
            field=models.BooleanField(verbose_name='Correct'),
        ),
        migrations.AlterField(
            model_name='exerciseattempt',
            name='prompt',
            field=models.TextField(blank=True, verbose_name='Prompt'),
        ),
        migrations.AlterField(
            model_name='exerciseattempt',
            name='response_ms',
            field=models.PositiveIntegerField(default=0, verbose_name='Response ms'),
        ),
        migrations.AlterField(
            model_name='exerciseattempt',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='learning.learningsession', verbose_name='Session'),
        ),
        migrations.AlterField(
            model_name='exerciseattempt',
            name='step_index',
            field=models.PositiveIntegerField(verbose_name='Step index'),
        ),
        migrations.AlterField(
            model_name='exerciseattempt',
            name='submitted_answer',
            field=models.JSONField(blank=True, default=dict, verbose_name='Submitted answer'),
        ),
        migrations.AlterField(
            model_name='learningsession',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Completed at'),
        ),
        migrations.AlterField(
            model_name='learningsession',
            name='correct_answered',
            field=models.PositiveIntegerField(default=0, verbose_name='Correct answered'),
        ),
        migrations.AlterField(
            model_name='learningsession',
            name='exercises',
            field=models.JSONField(blank=True, default=list, verbose_name='Exercises'),
        ),
        migrations.AlterField(
            model_name='learningsession',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='learning.lesson', verbose_name='Lesson'),
        ),
        migrations.AlterField(
            model_name='learningsession',
            name='session_type',
            field=models.CharField(choices=[('lesson', 'Lesson'), ('checkpoint', 'Checkpoint')], default='lesson', max_length=16, verbose_name='Session type'),
        ),
        migrations.AlterField(
            model_name='learningsession',
            name='started_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Started at'),
        ),
        migrations.AlterField(
            model_name='learningsession',
            name='status',
            field=models.CharField(choices=[('started', 'Started'), ('completed', 'Completed'), ('abandoned', 'Abandoned')], default='started', max_length=16, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='learningsession',
            name='total_answered',
            field=models.PositiveIntegerField(default=0, verbose_name='Total answered'),
        ),
        migrations.AlterField(
            model_name='learningsession',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_sessions', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='learningsession',
            name='xp_earned',
            field=models.PositiveIntegerField(default=0, verbose_name='XP earned'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='learning.course', verbose_name='Course'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='is_published',
            field=models.BooleanField(default=False, verbose_name='Published'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='order_index',
            field=models.PositiveIntegerField(default=0, verbose_name='Order'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='required_lessons_to_unlock',
            field=models.PositiveIntegerField(default=1, verbose_name='Required lessons for next unit'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='unitlesson',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unit_links', to='learning.lesson', verbose_name='Lesson'),
        ),
        migrations.AlterField(
            model_name='unitlesson',
            name='order_index',
            field=models.PositiveIntegerField(default=0, verbose_name='Order'),
        ),
        migrations.AlterField(
            model_name='userunitprogress',
            name='checkpoint_passed',
            field=models.BooleanField(default=False, verbose_name='Checkpoint passed'),
        ),
        migrations.AlterField(
            model_name='userunitprogress',
            name='checkpoint_passed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Checkpoint passed at'),
        ),
        migrations.AlterField(
            model_name='userunitprogress',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Completed at'),
        ),
        migrations.AlterField(
            model_name='userunitprogress',
            name='completed_lessons',
            field=models.PositiveIntegerField(default=0, verbose_name='Completed lessons'),
        ),
        migrations.AlterField(
            model_name='userunitprogress',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Started at'),
        ),
        migrations.AlterField(
            model_name='userunitprogress',
            name='total_xp_earned',
            field=models.PositiveIntegerField(default=0, verbose_name='Total XP earned'),
        ),
        migrations.AlterField(
            model_name='userunitprogress',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unit_progress', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.CreateModel(
            name='UserReminderPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferred_hour', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Preferred hour')),
                ('last_activity_at', models.DateTimeField(blank=True, null=True, verbose_name='Last activity at')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='learning_reminder_pref', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'User reminder preference',
                'verbose_name_plural': 'User reminder preferences',
                'db_table': 'user_reminder_preferences',
            },
        ),
        migrations.CreateModel(
            name='UserHearts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_hearts', models.PositiveIntegerField(default=5, verbose_name='Current hearts')),
                ('max_hearts', models.PositiveIntegerField(default=5, verbose_name='Max hearts')),
                ('refill_interval_minutes', models.PositiveIntegerField(default=240, verbose_name='Refill interval minutes')),
                ('last_refill_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Last refill at')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hearts', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'User hearts',
                'verbose_name_plural': 'User hearts',
                'db_table': 'user_hearts',
            },
        ),
        migrations.CreateModel(
            name='HeartTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('consume', 'Consume'), ('refill', 'Refill'), ('bonus', 'Bonus')], max_length=16, verbose_name='Type')),
                ('delta', models.IntegerField(verbose_name='Delta')),
                ('reason', models.CharField(blank=True, max_length=120, verbose_name='Reason')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hearts', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='learning.userhearts', verbose_name='User hearts')),
            ],
            options={
                'verbose_name': 'Heart transaction',
                'verbose_name_plural': 'Heart transactions',
                'db_table': 'heart_transactions',
                'indexes': [models.Index(fields=['hearts', 'created_at'], name='heart_trans_hearts__3bfbe1_idx')],
            },
        ),
        migrations.CreateModel(
            name='DailyGoalLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal_date', models.DateField(verbose_name='Date')),
                ('studied_minutes', models.PositiveIntegerField(default=0, verbose_name='Studied minutes')),
                ('goal_minutes', models.PositiveIntegerField(default=10, verbose_name='Goal minutes')),
                ('is_achieved', models.BooleanField(default=False, verbose_name='Achieved')),
                ('achieved_at', models.DateTimeField(blank=True, null=True, verbose_name='Achieved at')),
                ('claimed_at', models.DateTimeField(blank=True, null=True, verbose_name='Claimed at')),
                ('reward_xp_awarded', models.PositiveIntegerField(default=0, verbose_name='Reward XP awarded')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='learning.dailygoal', verbose_name='Daily goal')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_goal_logs', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Daily goal log',
                'verbose_name_plural': 'Daily goal logs',
                'db_table': 'daily_goal_logs',
                'indexes': [models.Index(fields=['user', 'goal_date'], name='daily_goal__user_id_aa3d42_idx'), models.Index(fields=['goal_date', 'is_achieved'], name='daily_goal__goal_da_5c2122_idx')],
                'unique_together': {('user', 'goal_date')},
            },
        ),
    ]
