# Generated by Django 4.2.13 on 2026-05-14 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0007_dailygoal_alter_course_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningsession',
            name='difficulty',
            field=models.CharField(choices=[('easy', 'Easy'), ('normal', 'Normal'), ('hard', 'Hard')], default='normal', max_length=10, verbose_name='Difficulty'),
        ),
        migrations.AddField(
            model_name='userstreak',
            name='last_freeze_reward_streak',
            field=models.PositiveIntegerField(default=0, verbose_name='Last rewarded streak'),
        ),
    ]
