# Generated by Django 4.2.13 on 2026-05-14 10:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('learning', '0008_learningsession_difficulty_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('session_start', 'Session Start'), ('answer_submit', 'Answer Submit'), ('session_finish', 'Session Finish'), ('session_quit', 'Session Quit'), ('checkpoint_submit', 'Checkpoint Submit')], max_length=32, verbose_name='Event type')),
                ('meta', models.JSONField(blank=True, default=dict, verbose_name='Event meta')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='learning.learningsession', verbose_name='Session')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_events', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Learning event',
                'verbose_name_plural': 'Learning events',
                'db_table': 'learning_events',
                'indexes': [models.Index(fields=['event_type', 'created_at'], name='learning_ev_event_t_ac218e_idx'), models.Index(fields=['user', 'created_at'], name='learning_ev_user_id_37c831_idx'), models.Index(fields=['session', 'created_at'], name='learning_ev_session_c901ea_idx')],
            },
        ),
    ]
