# Generated by Django 4.2.13 on 2026-05-14 10:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('learning', '0009_learningevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlacementResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommended_level', models.CharField(blank=True, max_length=10, verbose_name='Recommended level')),
                ('score_pct', models.FloatField(default=0, verbose_name='Score percent')),
                ('total_questions', models.PositiveIntegerField(default=0, verbose_name='Total questions')),
                ('correct_answers', models.PositiveIntegerField(default=0, verbose_name='Correct answers')),
                ('answers', models.JSONField(blank=True, default=list, verbose_name='Answer payload')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='placement_results', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Placement result',
                'verbose_name_plural': 'Placement results',
                'db_table': 'placement_results',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='placement_r_user_id_4d1b2c_idx')],
            },
        ),
    ]
