# Generated by Django 4.2.13 on 2026-05-14 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0010_placementresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='content_difficulty',
            field=models.CharField(choices=[('easy', 'Easy'), ('normal', 'Normal'), ('hard', 'Hard')], default='normal', max_length=10, verbose_name='Content difficulty'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='skill_tag',
            field=models.CharField(choices=[('vocab', 'Vocabulary'), ('listening', 'Listening'), ('grammar', 'Grammar'), ('mixed', 'Mixed')], default='vocab', max_length=20, verbose_name='Skill tag'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='topic',
            field=models.CharField(blank=True, max_length=100, verbose_name='Topic'),
        ),
    ]
