# Generated by Django 4.2.13 on 2026-05-14 11:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('learning', '0011_lesson_content_difficulty_lesson_skill_tag_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExperimentAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experiment_key', models.CharField(max_length=80, verbose_name='Experiment key')),
                ('variant_name', models.CharField(max_length=80, verbose_name='Variant name')),
                ('variant_payload', models.JSONField(blank=True, default=dict, verbose_name='Variant payload')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Experiment assignment',
                'verbose_name_plural': 'Experiment assignments',
                'db_table': 'learning_experiment_assignments',
            },
        ),
        migrations.CreateModel(
            name='ExperimentConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=80, unique=True, verbose_name='Experiment key')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Description')),
                ('variants', models.JSONField(blank=True, default=list, verbose_name='Variants')),
                ('is_active', models.BooleanField(default=False, verbose_name='Active')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Started at')),
                ('ended_at', models.DateTimeField(blank=True, null=True, verbose_name='Ended at')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Experiment config',
                'verbose_name_plural': 'Experiment configs',
                'db_table': 'learning_experiment_configs',
            },
        ),
        migrations.CreateModel(
            name='LeagueSeason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=40, unique=True, verbose_name='Season code')),
                ('title', models.CharField(max_length=120, verbose_name='Title')),
                ('start_date', models.DateField(verbose_name='Start date')),
                ('end_date', models.DateField(verbose_name='End date')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'League season',
                'verbose_name_plural': 'League seasons',
                'db_table': 'learning_league_seasons',
                'ordering': ['-start_date'],
            },
        ),
        migrations.AlterField(
            model_name='learningevent',
            name='event_type',
            field=models.CharField(choices=[('session_start', 'Session Start'), ('answer_submit', 'Answer Submit'), ('session_finish', 'Session Finish'), ('session_quit', 'Session Quit'), ('checkpoint_submit', 'Checkpoint Submit'), ('experiment_metric', 'Experiment Metric')], max_length=32, verbose_name='Event type'),
        ),
        migrations.CreateModel(
            name='LeagueStanding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.PositiveIntegerField(default=0, verbose_name='Rank')),
                ('xp_earned', models.PositiveIntegerField(default=0, verbose_name='XP earned')),
                ('sessions_completed', models.PositiveIntegerField(default=0, verbose_name='Sessions completed')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='standings', to='learning.leagueseason', verbose_name='Season')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='league_standings', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'League standing',
                'verbose_name_plural': 'League standings',
                'db_table': 'learning_league_standings',
                'ordering': ['rank', '-xp_earned', '-sessions_completed'],
            },
        ),
        migrations.AddIndex(
            model_name='leagueseason',
            index=models.Index(fields=['is_active', 'start_date'], name='learning_le_is_acti_22965a_idx'),
        ),
        migrations.AddField(
            model_name='experimentassignment',
            name='experiment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments', to='learning.experimentconfig', verbose_name='Experiment config'),
        ),
        migrations.AddField(
            model_name='experimentassignment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_experiment_assignments', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AddIndex(
            model_name='leaguestanding',
            index=models.Index(fields=['season', 'rank'], name='learning_le_season__b19c3d_idx'),
        ),
        migrations.AddIndex(
            model_name='leaguestanding',
            index=models.Index(fields=['user', 'season'], name='learning_le_user_id_c72ecd_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='leaguestanding',
            unique_together={('season', 'user')},
        ),
        migrations.AddIndex(
            model_name='experimentassignment',
            index=models.Index(fields=['experiment_key', 'variant_name'], name='learning_ex_experim_fd6aec_idx'),
        ),
        migrations.AddIndex(
            model_name='experimentassignment',
            index=models.Index(fields=['user', 'experiment_key'], name='learning_ex_user_id_7ad985_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='experimentassignment',
            unique_together={('user', 'experiment_key')},
        ),
    ]
