# Generated by Django 4.2.13 on 2026-05-14 11:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('learning', '0012_experimentassignment_experimentconfig_leagueseason_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCourseProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_units', models.PositiveIntegerField(default=0, verbose_name='Completed units')),
                ('total_xp_earned', models.PositiveIntegerField(default=0, verbose_name='Total XP earned')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Started at')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Completed at')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='learning.course', verbose_name='Course')),
                ('last_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='learning.unit', verbose_name='Last active unit')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_progress', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'User course progress',
                'verbose_name_plural': 'User course progress',
                'db_table': 'user_course_progress',
                'indexes': [models.Index(fields=['user', 'course'], name='user_course_user_id_32dde7_idx')],
                'unique_together': {('user', 'course')},
            },
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_index', models.PositiveIntegerField(default=1, verbose_name='Step index')),
                ('exercise_type', models.CharField(choices=[('mc_meaning', 'Multiple Choice Meaning'), ('listen_choose_word', 'Listen Choose Word'), ('fill_blank', 'Fill Blank'), ('word_order', 'Word Order')], default='mc_meaning', max_length=40, verbose_name='Exercise type')),
                ('prompt', models.TextField(verbose_name='Prompt')),
                ('payload', models.JSONField(blank=True, default=dict, verbose_name='Payload')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercise_bank', to='learning.lesson', verbose_name='Lesson')),
            ],
            options={
                'verbose_name': 'Exercise template',
                'verbose_name_plural': 'Exercise templates',
                'db_table': 'learning_exercises',
                'ordering': ['step_index', 'id'],
                'indexes': [models.Index(fields=['lesson', 'is_active'], name='learning_ex_lesson__7f08e7_idx'), models.Index(fields=['lesson', 'step_index'], name='learning_ex_lesson__cb75a7_idx')],
                'unique_together': {('lesson', 'step_index', 'exercise_type')},
            },
        ),
    ]
