# Generated by Django 4.2.13 on 2026-05-14 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0013_usercourseprogress_exercise'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learningevent',
            name='event_type',
            field=models.CharField(choices=[('session_start', 'Session Start'), ('answer_submit', 'Answer Submit'), ('session_finish', 'Session Finish'), ('session_quit', 'Session Quit'), ('checkpoint_submit', 'Checkpoint Submit'), ('experiment_metric', 'Experiment Metric'), ('onboarding_step', 'Onboarding Step')], max_length=32, verbose_name='Event type'),
        ),
    ]
