# Generated by Django 4.2.13 on 2026-05-15 10:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('learning', '0014_alter_learningevent_event_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=60, unique=True, verbose_name='Plan code')),
                ('name', models.CharField(max_length=200, verbose_name='Plan name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('duration_days', models.PositiveIntegerField(default=30, verbose_name='Duration days')),
                ('price_cents', models.PositiveIntegerField(default=0, verbose_name='Price (cents)')),
                ('currency', models.CharField(default='VND', max_length=10, verbose_name='Currency')),
                ('auto_assign_published_lessons', models.BooleanField(default=False, verbose_name='Auto assign published lessons')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('target_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plans', to='learning.studentclass', verbose_name='Target class')),
            ],
            options={
                'verbose_name': 'Learning plan',
                'verbose_name_plural': 'Learning plans',
                'db_table': 'learning_plans',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PaymentEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(default='manual', max_length=40, verbose_name='Provider')),
                ('transaction_id', models.CharField(max_length=120, verbose_name='Transaction id')),
                ('user_email', models.EmailField(blank=True, max_length=254, verbose_name='User email')),
                ('plan_code', models.CharField(blank=True, max_length=60, verbose_name='Plan code')),
                ('amount_cents', models.PositiveIntegerField(default=0, verbose_name='Amount (cents)')),
                ('currency', models.CharField(default='VND', max_length=10, verbose_name='Currency')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=20, verbose_name='Status')),
                ('payload', models.JSONField(blank=True, default=dict, verbose_name='Raw payload')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='Processed at')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_events', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Payment event',
                'verbose_name_plural': 'Payment events',
                'db_table': 'learning_payment_events',
            },
        ),
        migrations.CreateModel(
            name='LearningSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_at', models.DateTimeField(verbose_name='Start at')),
                ('end_at', models.DateTimeField(verbose_name='End at')),
                ('status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='active', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payment_event', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='subscription', to='learning.paymentevent', verbose_name='Payment event')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='learning.learningplan', verbose_name='Plan')),
                ('student_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscriptions', to='learning.studentclass', verbose_name='Student class')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_subscriptions', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Learning subscription',
                'verbose_name_plural': 'Learning subscriptions',
                'db_table': 'learning_subscriptions',
            },
        ),
        migrations.AddIndex(
            model_name='paymentevent',
            index=models.Index(fields=['provider', 'transaction_id'], name='learning_pa_provide_8c02bb_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentevent',
            index=models.Index(fields=['status', 'created_at'], name='learning_pa_status_381758_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='paymentevent',
            unique_together={('provider', 'transaction_id')},
        ),
        migrations.AddIndex(
            model_name='learningsubscription',
            index=models.Index(fields=['user', 'status'], name='learning_su_user_id_43a658_idx'),
        ),
        migrations.AddIndex(
            model_name='learningsubscription',
            index=models.Index(fields=['end_at', 'status'], name='learning_su_end_at_3154c1_idx'),
        ),
    ]
