# Generated by Django 4.2.13 on 2026-05-15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("learning", "0015_learningplan_paymentevent_learningsubscription_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="LearningSubscription",
        ),
        migrations.DeleteModel(
            name="LearningPlan",
        ),
        migrations.DeleteModel(
            name="PaymentEvent",
        ),
        migrations.DeleteModel(
            name="StudentClass",
        ),
        migrations.DeleteModel(
            name="Assignment",
        ),
    ]
