# Generated by Django 4.2.13 on 2026-05-16 04:39

from django.db import migrations, models


def apply_hearts_policy(apps, schema_editor):
    UserHearts = apps.get_model("learning", "UserHearts")
    for hearts in UserHearts.objects.all().iterator():
        changed = False
        if hearts.max_hearts < 10:
            hearts.max_hearts = 10
            changed = True
        if hearts.current_hearts > hearts.max_hearts:
            hearts.current_hearts = hearts.max_hearts
            changed = True
        if hearts.refill_interval_minutes > 10:
            hearts.refill_interval_minutes = 10
            changed = True
        if changed:
            hearts.save(update_fields=["max_hearts", "current_hearts", "refill_interval_minutes", "updated_at"])


def revert_hearts_policy(apps, schema_editor):
    UserHearts = apps.get_model("learning", "UserHearts")
    for hearts in UserHearts.objects.all().iterator():
        changed = False
        if hearts.max_hearts > 5:
            hearts.max_hearts = 5
            changed = True
        if hearts.current_hearts > hearts.max_hearts:
            hearts.current_hearts = hearts.max_hearts
            changed = True
        if hearts.refill_interval_minutes < 240:
            hearts.refill_interval_minutes = 240
            changed = True
        if changed:
            hearts.save(update_fields=["max_hearts", "current_hearts", "refill_interval_minutes", "updated_at"])


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0016_remove_legacy_teacher_and_billing_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userhearts',
            name='current_hearts',
            field=models.PositiveIntegerField(default=10, verbose_name='Current hearts'),
        ),
        migrations.AlterField(
            model_name='userhearts',
            name='max_hearts',
            field=models.PositiveIntegerField(default=10, verbose_name='Max hearts'),
        ),
        migrations.AlterField(
            model_name='userhearts',
            name='refill_interval_minutes',
            field=models.PositiveIntegerField(default=10, verbose_name='Refill interval minutes'),
        ),
        migrations.RunPython(apply_hearts_policy, revert_hearts_policy),
    ]
