# Generated by Django 4.2.13 on 2026-06-05 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0017_alter_userhearts_current_hearts_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='listening_estimated_seconds',
            field=models.PositiveIntegerField(default=30, verbose_name='Listening duration'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='listening_transcript',
            field=models.TextField(blank=True, verbose_name='Listening transcript'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='listening_translation_vi',
            field=models.TextField(blank=True, verbose_name='Listening translation'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='listening_tts_lang',
            field=models.CharField(default='en-US', max_length=16, verbose_name='Listening TTS language'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='listening_tts_rate',
            field=models.FloatField(default=0.9, verbose_name='Listening TTS rate'),
        ),
    ]
