# Generated by Django 4.2.13 on 2026-06-06 04:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('learning', '0018_lesson_listening_estimated_seconds_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListeningPassage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('topic', models.CharField(blank=True, max_length=100, verbose_name='Topic')),
                ('level', models.CharField(choices=[('A1', 'A1'), ('A2', 'A2'), ('B1', 'B1'), ('B2', 'B2'), ('C1', 'C1'), ('C2', 'C2'), ('TOEIC', 'TOEIC')], default='A1', max_length=10, verbose_name='Level')),
                ('transcript', models.TextField(verbose_name='Transcript')),
                ('translation_vi', models.TextField(blank=True, verbose_name='Vietnamese translation')),
                ('estimated_seconds', models.PositiveIntegerField(default=30, verbose_name='Estimated seconds')),
                ('tts_lang', models.CharField(default='en-US', max_length=16, verbose_name='TTS language')),
                ('tts_rate', models.FloatField(default=0.9, verbose_name='TTS rate')),
                ('is_published', models.BooleanField(default=False, verbose_name='Published')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listening_passages_created', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
            ],
            options={
                'verbose_name': 'Listening passage',
                'verbose_name_plural': 'Listening passages',
                'db_table': 'listening_passages',
                'ordering': ['level', 'title'],
            },
        ),
        migrations.CreateModel(
            name='ListeningSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('started', 'Started'), ('completed', 'Completed'), ('abandoned', 'Abandoned')], default='started', max_length=16, verbose_name='Status')),
                ('current_question_index', models.PositiveIntegerField(default=0, verbose_name='Current question index')),
                ('score', models.PositiveIntegerField(default=0, verbose_name='Score')),
                ('score_pct', models.FloatField(default=0, verbose_name='Score percent')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='Started at')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Completed at')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('passage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='learning.listeningpassage', verbose_name='Passage')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listening_sessions', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Listening session',
                'verbose_name_plural': 'Listening sessions',
                'db_table': 'listening_sessions',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='ListeningQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_type', models.CharField(choices=[('multiple_choice', 'Multiple Choice'), ('true_false', 'True/False'), ('fill_blank', 'Fill Blank')], default='multiple_choice', max_length=32, verbose_name='Question type')),
                ('prompt', models.TextField(verbose_name='Prompt')),
                ('choices_json', models.JSONField(blank=True, default=list, verbose_name='Choices')),
                ('correct_answer', models.JSONField(blank=True, default=dict, verbose_name='Correct answer')),
                ('explanation', models.TextField(blank=True, verbose_name='Explanation')),
                ('order_index', models.PositiveIntegerField(default=1, verbose_name='Order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('passage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='learning.listeningpassage', verbose_name='Passage')),
            ],
            options={
                'verbose_name': 'Listening question',
                'verbose_name_plural': 'Listening questions',
                'db_table': 'listening_questions',
                'ordering': ['order_index', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ListeningAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_answer', models.JSONField(blank=True, default=dict, verbose_name='Submitted answer')),
                ('is_correct', models.BooleanField(default=False, verbose_name='Correct')),
                ('answered_at', models.DateTimeField(auto_now_add=True, verbose_name='Answered at')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='learning.listeningquestion', verbose_name='Question')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='learning.listeningsession', verbose_name='Session')),
            ],
            options={
                'verbose_name': 'Listening answer',
                'verbose_name_plural': 'Listening answers',
                'db_table': 'listening_answers',
            },
        ),
        migrations.AddIndex(
            model_name='listeningsession',
            index=models.Index(fields=['user', 'status'], name='listening_s_user_id_bd05c4_idx'),
        ),
        migrations.AddIndex(
            model_name='listeningsession',
            index=models.Index(fields=['passage', 'status'], name='listening_s_passage_7b68e8_idx'),
        ),
        migrations.AddIndex(
            model_name='listeningquestion',
            index=models.Index(fields=['passage', 'order_index'], name='listening_q_passage_9b297c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='listeningquestion',
            unique_together={('passage', 'order_index')},
        ),
        migrations.AddIndex(
            model_name='listeningpassage',
            index=models.Index(fields=['is_published', 'level'], name='listening_p_is_publ_4d6f5b_idx'),
        ),
        migrations.AddIndex(
            model_name='listeningpassage',
            index=models.Index(fields=['topic', 'level'], name='listening_p_topic_ffebc4_idx'),
        ),
        migrations.AddIndex(
            model_name='listeninganswer',
            index=models.Index(fields=['session', 'question'], name='listening_a_session_f729a5_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='listeninganswer',
            unique_together={('session', 'question')},
        ),
    ]
