# Generated by Django 4.2.13 on 2026-06-06 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0019_listeningpassage_listeningsession_listeningquestion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userunitprogress',
            name='checkpoint_attempts',
            field=models.PositiveIntegerField(default=0, verbose_name='Checkpoint attempts'),
        ),
        migrations.AddField(
            model_name='userunitprogress',
            name='checkpoint_last_attempt_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Checkpoint last attempt at'),
        ),
        migrations.AddField(
            model_name='userunitprogress',
            name='checkpoint_locked_until',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Checkpoint locked until'),
        ),
    ]
