# Generated by Django 4.2.13 on 2026-06-09 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0020_userunitprogress_checkpoint_attempts_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('level_up', 'Lên cấp'), ('streak', 'Streak milestone'), ('reminder', 'Nhắc nhở ôn tập')], max_length=50, verbose_name='Loại'),
        ),
        migrations.AlterField(
            model_name='userstreak',
            name='last_freeze_used_on',
            field=models.DateField(blank=True, null=True, verbose_name='Ngày dùng freeze gần nhất'),
        ),
        migrations.AlterField(
            model_name='userstreak',
            name='streak_freezes',
            field=models.PositiveIntegerField(default=0, verbose_name='Số streak freeze'),
        ),
    ]
