# Generated by Django 4.2.13 on 2026-06-11 14:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quiz', '0002_alter_quiz_id_alter_quizresult_id'),
        ('learning', '0021_alter_notification_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnitActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('vocab', 'Vocabulary'), ('listening', 'Listening'), ('grammar', 'Grammar'), ('writing', 'Writing'), ('quiz', 'Quiz'), ('checkpoint', 'Checkpoint')], max_length=24, verbose_name='Activity type')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('order_index', models.PositiveIntegerField(default=1, verbose_name='Order')),
                ('is_required', models.BooleanField(default=True, verbose_name='Required')),
                ('is_published', models.BooleanField(default=False, verbose_name='Published')),
                ('estimated_minutes', models.PositiveIntegerField(default=5, verbose_name='Estimated minutes')),
                ('min_score_to_pass', models.PositiveIntegerField(default=70, verbose_name='Minimum score to pass')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Metadata')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unit_activities', to='learning.lesson', verbose_name='Lesson')),
                ('listening_passage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unit_activities', to='learning.listeningpassage', verbose_name='Listening passage')),
                ('quiz', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unit_activities', to='quiz.quiz', verbose_name='Quiz')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='learning.unit', verbose_name='Unit')),
            ],
            options={
                'verbose_name': 'Unit activity',
                'verbose_name_plural': 'Unit activities',
                'db_table': 'unit_activities',
                'ordering': ['unit', 'order_index'],
            },
        ),
        migrations.CreateModel(
            name='WritingSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt', models.TextField(verbose_name='Prompt')),
                ('answer_text', models.TextField(blank=True, verbose_name='Answer text')),
                ('word_count', models.PositiveIntegerField(default=0, verbose_name='Word count')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('reviewed', 'Reviewed')], default='draft', max_length=16, verbose_name='Status')),
                ('feedback', models.TextField(blank=True, verbose_name='Feedback')),
                ('score_pct', models.FloatField(default=0, verbose_name='Score percent')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='Submitted at')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='Reviewed at')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='writing_submissions', to='learning.unitactivity', verbose_name='Activity')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='writing_submissions', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Writing submission',
                'verbose_name_plural': 'Writing submissions',
                'db_table': 'writing_submissions',
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['user', 'activity'], name='writing_sub_user_id_ae3b58_idx'), models.Index(fields=['status', 'submitted_at'], name='writing_sub_status_2860c2_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserActivityProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('locked', 'Locked'), ('available', 'Available'), ('started', 'Started'), ('completed', 'Completed')], default='locked', max_length=16, verbose_name='Status')),
                ('score_pct', models.FloatField(default=0, verbose_name='Score percent')),
                ('xp_earned', models.PositiveIntegerField(default=0, verbose_name='XP earned')),
                ('attempts_count', models.PositiveIntegerField(default=0, verbose_name='Attempts count')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Started at')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Completed at')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='learning.unitactivity', verbose_name='Activity')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_progress', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'User activity progress',
                'verbose_name_plural': 'User activity progress',
                'db_table': 'user_activity_progress',
                'indexes': [models.Index(fields=['user', 'status'], name='user_activi_user_id_26ed2f_idx'), models.Index(fields=['activity', 'status'], name='user_activi_activit_b4ab98_idx'), models.Index(fields=['user', 'activity'], name='user_activi_user_id_8d23c9_idx')],
                'unique_together': {('user', 'activity')},
            },
        ),
        migrations.AddIndex(
            model_name='unitactivity',
            index=models.Index(fields=['unit', 'is_published', 'order_index'], name='unit_activi_unit_id_35df88_idx'),
        ),
        migrations.AddIndex(
            model_name='unitactivity',
            index=models.Index(fields=['activity_type', 'is_published'], name='unit_activi_activit_eb281e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='unitactivity',
            unique_together={('unit', 'order_index')},
        ),
    ]
