# Generated by Django 4.2.13 on 2026-06-11 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0022_unitactivity_writingsubmission_useractivityprogress_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningsession',
            name='unit_activity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='learning_sessions', to='learning.unitactivity', verbose_name='Unit activity'),
        ),
        migrations.AddField(
            model_name='listeningsession',
            name='unit_activity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='listening_sessions', to='learning.unitactivity', verbose_name='Unit activity'),
        ),
    ]
