"""
Lệnh seed dữ liệu mẫu cho môi trường development.
Chạy: python manage.py seed_data
"""
from django.contrib.auth import get_user_model
from django.core.management.base import BaseCommand
from django.db import transaction

from apps.vocabulary.models import Word, WordSet, WordSetWord
from apps.learning.models import Lesson, LessonWord

User = get_user_model()

# ── Từ vựng mẫu ──────────────────────────────────────────────────────────────

WORDS = [
    # ── A1 (40 từ) ─────────────────────────────────────────────────────────────
    {"text": "hello",       "phonetic": "/həˈloʊ/",      "part_of_speech": "exclamation", "definition_en": "Used as a greeting",                          "definition_vi": "Xin chào",              "example_en": "Hello, how are you?",                    "example_vi": "Xin chào, bạn khỏe không?",             "level": "A1"},
    {"text": "goodbye",     "phonetic": "/ˌɡʊdˈbaɪ/",    "part_of_speech": "exclamation", "definition_en": "Used when leaving or parting",                "definition_vi": "Tạm biệt",              "example_en": "Goodbye, see you tomorrow!",              "example_vi": "Tạm biệt, hẹn gặp lại ngày mai!",      "level": "A1"},
    {"text": "book",        "phonetic": "/bʊk/",          "part_of_speech": "noun",        "definition_en": "A written or printed work",                   "definition_vi": "Cuốn sách",             "example_en": "I read a book every week.",               "example_vi": "Tôi đọc một cuốn sách mỗi tuần.",       "level": "A1"},
    {"text": "water",       "phonetic": "/ˈwɔːtər/",      "part_of_speech": "noun",        "definition_en": "A clear liquid essential for life",            "definition_vi": "Nước",                  "example_en": "Please give me a glass of water.",        "example_vi": "Vui lòng cho tôi một ly nước.",          "level": "A1"},
    {"text": "eat",         "phonetic": "/iːt/",          "part_of_speech": "verb",        "definition_en": "To put food in your mouth and swallow it",     "definition_vi": "Ăn",                    "example_en": "We eat dinner at 7pm.",                   "example_vi": "Chúng tôi ăn tối lúc 7 giờ tối.",       "level": "A1"},
    {"text": "sleep",       "phonetic": "/sliːp/",        "part_of_speech": "verb",        "definition_en": "To rest in a state of sleep",                  "definition_vi": "Ngủ",                   "example_en": "I sleep eight hours a night.",            "example_vi": "Tôi ngủ tám tiếng mỗi đêm.",            "level": "A1"},
    {"text": "house",       "phonetic": "/haʊs/",         "part_of_speech": "noun",        "definition_en": "A building for people to live in",             "definition_vi": "Ngôi nhà",              "example_en": "They live in a big house.",               "example_vi": "Họ sống trong một ngôi nhà lớn.",        "level": "A1"},
    {"text": "family",      "phonetic": "/ˈfæməli/",      "part_of_speech": "noun",        "definition_en": "A group of people related to each other",      "definition_vi": "Gia đình",              "example_en": "My family has four members.",             "example_vi": "Gia đình tôi có bốn thành viên.",        "level": "A1"},
    {"text": "school",      "phonetic": "/skuːl/",        "part_of_speech": "noun",        "definition_en": "A place where children are educated",          "definition_vi": "Trường học",             "example_en": "She goes to school by bus.",              "example_vi": "Cô ấy đi học bằng xe buýt.",             "level": "A1"},
    {"text": "friend",      "phonetic": "/frend/",        "part_of_speech": "noun",        "definition_en": "A person you like and enjoy being with",       "definition_vi": "Bạn bè",                "example_en": "He is my best friend.",                   "example_vi": "Anh ấy là người bạn thân nhất của tôi.", "level": "A1"},
    {"text": "cat",         "phonetic": "/kæt/",          "part_of_speech": "noun",        "definition_en": "A small furry domestic animal",                "definition_vi": "Con mèo",               "example_en": "My cat sleeps all day.",                  "example_vi": "Con mèo của tôi ngủ cả ngày.",           "level": "A1"},
    {"text": "dog",         "phonetic": "/dɒɡ/",          "part_of_speech": "noun",        "definition_en": "A common domesticated carnivore kept as a pet", "definition_vi": "Con chó",               "example_en": "The dog barks loudly.",                   "example_vi": "Con chó sủa to.",                        "level": "A1"},
    {"text": "apple",       "phonetic": "/ˈæpəl/",        "part_of_speech": "noun",        "definition_en": "A round fruit with red or green skin",         "definition_vi": "Quả táo",               "example_en": "She eats an apple every morning.",        "example_vi": "Cô ấy ăn một quả táo mỗi sáng.",        "level": "A1"},
    {"text": "milk",        "phonetic": "/mɪlk/",         "part_of_speech": "noun",        "definition_en": "A white liquid produced by cows",              "definition_vi": "Sữa",                   "example_en": "Children drink milk every day.",          "example_vi": "Trẻ em uống sữa mỗi ngày.",              "level": "A1"},
    {"text": "sun",         "phonetic": "/sʌn/",          "part_of_speech": "noun",        "definition_en": "The star at the centre of the solar system",   "definition_vi": "Mặt trời",              "example_en": "The sun rises in the east.",              "example_vi": "Mặt trời mọc ở phía đông.",              "level": "A1"},
    {"text": "chair",       "phonetic": "/tʃeər/",        "part_of_speech": "noun",        "definition_en": "A separate seat for one person",               "definition_vi": "Cái ghế",               "example_en": "Please sit on the chair.",                "example_vi": "Vui lòng ngồi vào ghế.",                 "level": "A1"},
    {"text": "table",       "phonetic": "/ˈteɪbəl/",      "part_of_speech": "noun",        "definition_en": "A piece of furniture with a flat surface",     "definition_vi": "Cái bàn",               "example_en": "The books are on the table.",             "example_vi": "Những cuốn sách ở trên bàn.",            "level": "A1"},
    {"text": "happy",       "phonetic": "/ˈhæpi/",        "part_of_speech": "adjective",   "definition_en": "Feeling pleasure and satisfaction",            "definition_vi": "Hạnh phúc / vui vẻ",    "example_en": "She looks happy today.",                  "example_vi": "Hôm nay cô ấy trông vui vẻ.",            "level": "A1"},
    {"text": "big",         "phonetic": "/bɪɡ/",          "part_of_speech": "adjective",   "definition_en": "Of considerable size",                         "definition_vi": "To / lớn",              "example_en": "That is a very big tree.",                "example_vi": "Đó là một cái cây rất to.",               "level": "A1"},
    {"text": "small",       "phonetic": "/smɔːl/",        "part_of_speech": "adjective",   "definition_en": "Of limited size or amount",                    "definition_vi": "Nhỏ",                   "example_en": "He has a small room.",                    "example_vi": "Anh ấy có một căn phòng nhỏ.",            "level": "A1"},
    {"text": "run",         "phonetic": "/rʌn/",          "part_of_speech": "verb",        "definition_en": "To move at a speed faster than a walk",        "definition_vi": "Chạy",                  "example_en": "I run every morning.",                    "example_vi": "Tôi chạy bộ mỗi sáng.",                  "level": "A1"},
    {"text": "walk",        "phonetic": "/wɔːk/",         "part_of_speech": "verb",        "definition_en": "To move on foot at a regular pace",            "definition_vi": "Đi bộ",                 "example_en": "We walk to school every day.",            "example_vi": "Chúng tôi đi bộ đến trường mỗi ngày.",   "level": "A1"},
    {"text": "open",        "phonetic": "/ˈoʊpən/",       "part_of_speech": "verb",        "definition_en": "To move so as to allow access",                "definition_vi": "Mở",                    "example_en": "Please open the window.",                 "example_vi": "Vui lòng mở cửa sổ.",                    "level": "A1"},
    {"text": "close",       "phonetic": "/kloʊz/",        "part_of_speech": "verb",        "definition_en": "To move so as to block an opening",            "definition_vi": "Đóng",                  "example_en": "Please close the door.",                  "example_vi": "Vui lòng đóng cửa lại.",                 "level": "A1"},
    {"text": "red",         "phonetic": "/red/",          "part_of_speech": "adjective",   "definition_en": "Having the colour of blood",                   "definition_vi": "Màu đỏ",                "example_en": "She wears a red dress.",                  "example_vi": "Cô ấy mặc váy đỏ.",                      "level": "A1"},
    {"text": "blue",        "phonetic": "/bluː/",         "part_of_speech": "adjective",   "definition_en": "Having the colour of the sky",                 "definition_vi": "Màu xanh da trời",      "example_en": "The sky is blue today.",                  "example_vi": "Hôm nay bầu trời màu xanh.",             "level": "A1"},
    {"text": "one",         "phonetic": "/wʌn/",          "part_of_speech": "number",      "definition_en": "The number 1",                                 "definition_vi": "Số một",                "example_en": "I have one sister.",                      "example_vi": "Tôi có một người chị.",                   "level": "A1"},
    {"text": "pen",         "phonetic": "/pen/",          "part_of_speech": "noun",        "definition_en": "An instrument for writing with ink",           "definition_vi": "Cái bút",               "example_en": "Give me a pen, please.",                  "example_vi": "Vui lòng đưa cho tôi một cái bút.",      "level": "A1"},
    {"text": "bag",         "phonetic": "/bæɡ/",          "part_of_speech": "noun",        "definition_en": "A flexible container for carrying things",     "definition_vi": "Cái túi",               "example_en": "Her bag is heavy.",                       "example_vi": "Túi của cô ấy rất nặng.",                 "level": "A1"},
    {"text": "mother",      "phonetic": "/ˈmʌðər/",       "part_of_speech": "noun",        "definition_en": "A female parent",                              "definition_vi": "Mẹ",                    "example_en": "My mother cooks every day.",              "example_vi": "Mẹ tôi nấu ăn mỗi ngày.",                "level": "A1"},
    {"text": "father",      "phonetic": "/ˈfɑːðər/",      "part_of_speech": "noun",        "definition_en": "A male parent",                                "definition_vi": "Bố / cha",              "example_en": "My father works in an office.",           "example_vi": "Bố tôi làm việc ở văn phòng.",           "level": "A1"},
    {"text": "yes",         "phonetic": "/jes/",          "part_of_speech": "exclamation", "definition_en": "Used to give a positive answer",               "definition_vi": "Vâng / có",             "example_en": "Yes, I understand.",                      "example_vi": "Vâng, tôi hiểu.",                         "level": "A1"},
    {"text": "no",          "phonetic": "/noʊ/",          "part_of_speech": "exclamation", "definition_en": "Used to give a negative answer",               "definition_vi": "Không",                 "example_en": "No, that is not right.",                  "example_vi": "Không, điều đó không đúng.",              "level": "A1"},
    {"text": "food",        "phonetic": "/fuːd/",         "part_of_speech": "noun",        "definition_en": "Substances we eat to give us energy",          "definition_vi": "Thức ăn",               "example_en": "This food tastes delicious.",             "example_vi": "Thức ăn này rất ngon.",                   "level": "A1"},
    {"text": "shirt",       "phonetic": "/ʃɜːrt/",        "part_of_speech": "noun",        "definition_en": "A garment worn on the upper body",             "definition_vi": "Áo sơ mi",              "example_en": "He wears a white shirt to work.",         "example_vi": "Anh ấy mặc áo sơ mi trắng đi làm.",      "level": "A1"},
    {"text": "car",         "phonetic": "/kɑːr/",         "part_of_speech": "noun",        "definition_en": "A road vehicle powered by an engine",          "definition_vi": "Xe ô tô",               "example_en": "He drives a red car.",                    "example_vi": "Anh ấy lái xe ô tô màu đỏ.",             "level": "A1"},
    {"text": "bus",         "phonetic": "/bʌs/",          "part_of_speech": "noun",        "definition_en": "A large motor vehicle for passengers",         "definition_vi": "Xe buýt",               "example_en": "I take the bus to work.",                 "example_vi": "Tôi đi xe buýt đến chỗ làm.",            "level": "A1"},
    {"text": "fish",        "phonetic": "/fɪʃ/",          "part_of_speech": "noun",        "definition_en": "A cold-blooded creature that lives in water",  "definition_vi": "Con cá",                "example_en": "We eat fish on Fridays.",                 "example_vi": "Chúng tôi ăn cá vào ngày thứ Sáu.",      "level": "A1"},
    {"text": "bird",        "phonetic": "/bɜːrd/",        "part_of_speech": "noun",        "definition_en": "A feathered animal with wings",                "definition_vi": "Con chim",              "example_en": "A bird is singing outside.",              "example_vi": "Một con chim đang hót bên ngoài.",        "level": "A1"},
    {"text": "hat",         "phonetic": "/hæt/",          "part_of_speech": "noun",        "definition_en": "A covering worn on the head",                  "definition_vi": "Cái mũ",                "example_en": "He wears a hat in summer.",               "example_vi": "Anh ấy đội mũ vào mùa hè.",              "level": "A1"},

    # ── A2 (40 từ) ─────────────────────────────────────────────────────────────
    {"text": "travel",         "phonetic": "/ˈtrævəl/",       "part_of_speech": "verb",        "definition_en": "To make a journey",                                "definition_vi": "Du lịch",               "example_en": "I love to travel to new places.",          "example_vi": "Tôi thích du lịch đến những nơi mới.",      "level": "A2"},
    {"text": "weather",        "phonetic": "/ˈweðər/",        "part_of_speech": "noun",        "definition_en": "The state of the atmosphere at a time",             "definition_vi": "Thời tiết",             "example_en": "The weather today is sunny.",               "example_vi": "Thời tiết hôm nay nắng đẹp.",               "level": "A2"},
    {"text": "shopping",       "phonetic": "/ˈʃɒpɪŋ/",        "part_of_speech": "noun",        "definition_en": "The activity of buying goods",                      "definition_vi": "Mua sắm",               "example_en": "She enjoys shopping on weekends.",           "example_vi": "Cô ấy thích mua sắm vào cuối tuần.",        "level": "A2"},
    {"text": "hospital",       "phonetic": "/ˈhɒspɪtl/",      "part_of_speech": "noun",        "definition_en": "A place where sick people receive treatment",        "definition_vi": "Bệnh viện",             "example_en": "He works at the local hospital.",            "example_vi": "Anh ấy làm việc tại bệnh viện địa phương.", "level": "A2"},
    {"text": "doctor",         "phonetic": "/ˈdɒktər/",       "part_of_speech": "noun",        "definition_en": "A person qualified to practise medicine",            "definition_vi": "Bác sĩ",                "example_en": "The doctor examined the patient.",           "example_vi": "Bác sĩ khám bệnh cho bệnh nhân.",            "level": "A2"},
    {"text": "market",         "phonetic": "/ˈmɑːrkɪt/",      "part_of_speech": "noun",        "definition_en": "A place where goods are bought and sold",            "definition_vi": "Chợ / thị trường",      "example_en": "We buy vegetables at the market.",           "example_vi": "Chúng tôi mua rau ở chợ.",                   "level": "A2"},
    {"text": "restaurant",     "phonetic": "/ˈrestrɒnt/",     "part_of_speech": "noun",        "definition_en": "A place where meals are cooked and served",          "definition_vi": "Nhà hàng",              "example_en": "Let's have dinner at that restaurant.",      "example_vi": "Hãy ăn tối ở nhà hàng đó.",                  "level": "A2"},
    {"text": "holiday",        "phonetic": "/ˈhɒlɪdeɪ/",      "part_of_speech": "noun",        "definition_en": "A period of time spent away from work",             "definition_vi": "Kỳ nghỉ",               "example_en": "We are going on holiday next week.",         "example_vi": "Chúng tôi sẽ đi nghỉ tuần tới.",             "level": "A2"},
    {"text": "telephone",      "phonetic": "/ˈtelɪfoʊn/",     "part_of_speech": "noun",        "definition_en": "A device used for voice communication",             "definition_vi": "Điện thoại",            "example_en": "Can I use your telephone?",                  "example_vi": "Tôi có thể dùng điện thoại của bạn không?",  "level": "A2"},
    {"text": "money",          "phonetic": "/ˈmʌni/",         "part_of_speech": "noun",        "definition_en": "Currency used in transactions",                     "definition_vi": "Tiền",                  "example_en": "I don't have enough money.",                 "example_vi": "Tôi không có đủ tiền.",                       "level": "A2"},
    {"text": "question",       "phonetic": "/ˈkwestʃən/",     "part_of_speech": "noun",        "definition_en": "A sentence that asks for information",              "definition_vi": "Câu hỏi",               "example_en": "Do you have any questions?",                 "example_vi": "Bạn có câu hỏi nào không?",                  "level": "A2"},
    {"text": "answer",         "phonetic": "/ˈɑːnsər/",       "part_of_speech": "noun",        "definition_en": "A response to a question",                          "definition_vi": "Câu trả lời",           "example_en": "Please give me your answer.",                "example_vi": "Vui lòng cho tôi câu trả lời của bạn.",      "level": "A2"},
    {"text": "city",           "phonetic": "/ˈsɪti/",         "part_of_speech": "noun",        "definition_en": "A large human settlement",                          "definition_vi": "Thành phố",             "example_en": "I live in a big city.",                      "example_vi": "Tôi sống ở một thành phố lớn.",               "level": "A2"},
    {"text": "country",        "phonetic": "/ˈkʌntri/",       "part_of_speech": "noun",        "definition_en": "A nation with its own government",                  "definition_vi": "Đất nước / quốc gia",   "example_en": "Vietnam is a beautiful country.",            "example_vi": "Việt Nam là một đất nước tươi đẹp.",          "level": "A2"},
    {"text": "music",          "phonetic": "/ˈmjuːzɪk/",      "part_of_speech": "noun",        "definition_en": "Sounds arranged to be pleasant to hear",            "definition_vi": "Âm nhạc",               "example_en": "I love listening to music.",                 "example_vi": "Tôi thích nghe nhạc.",                        "level": "A2"},
    {"text": "sport",          "phonetic": "/spɔːrt/",        "part_of_speech": "noun",        "definition_en": "An activity requiring physical effort",              "definition_vi": "Thể thao",              "example_en": "Football is my favourite sport.",            "example_vi": "Bóng đá là môn thể thao yêu thích của tôi.", "level": "A2"},
    {"text": "colour",         "phonetic": "/ˈkʌlər/",        "part_of_speech": "noun",        "definition_en": "Visual property of light wavelength",               "definition_vi": "Màu sắc",               "example_en": "What is your favourite colour?",             "example_vi": "Màu sắc yêu thích của bạn là gì?",           "level": "A2"},
    {"text": "number",         "phonetic": "/ˈnʌmbər/",       "part_of_speech": "noun",        "definition_en": "A mathematical value used to count",                "definition_vi": "Con số / số",           "example_en": "What is your phone number?",                 "example_vi": "Số điện thoại của bạn là gì?",                "level": "A2"},
    {"text": "week",           "phonetic": "/wiːk/",          "part_of_speech": "noun",        "definition_en": "A period of seven days",                            "definition_vi": "Tuần",                  "example_en": "I study five days a week.",                  "example_vi": "Tôi học năm ngày mỗi tuần.",                  "level": "A2"},
    {"text": "month",          "phonetic": "/mʌnθ/",          "part_of_speech": "noun",        "definition_en": "One of the twelve periods in a year",               "definition_vi": "Tháng",                 "example_en": "January is the first month.",                "example_vi": "Tháng Giêng là tháng đầu tiên.",              "level": "A2"},
    {"text": "birthday",       "phonetic": "/ˈbɜːrθdeɪ/",     "part_of_speech": "noun",        "definition_en": "The annual anniversary of one's birth",             "definition_vi": "Sinh nhật",             "example_en": "Happy birthday to you!",                     "example_vi": "Chúc mừng sinh nhật bạn!",                    "level": "A2"},
    {"text": "teacher",        "phonetic": "/ˈtiːtʃər/",      "part_of_speech": "noun",        "definition_en": "A person who teaches in a school",                  "definition_vi": "Giáo viên",             "example_en": "My teacher is very kind.",                   "example_vi": "Giáo viên của tôi rất tốt bụng.",             "level": "A2"},
    {"text": "student",        "phonetic": "/ˈstjuːdənt/",    "part_of_speech": "noun",        "definition_en": "A person who is studying at school",                "definition_vi": "Học sinh / sinh viên",  "example_en": "She is a good student.",                     "example_vi": "Cô ấy là một học sinh giỏi.",                 "level": "A2"},
    {"text": "breakfast",      "phonetic": "/ˈbrekfəst/",     "part_of_speech": "noun",        "definition_en": "The first meal of the day",                         "definition_vi": "Bữa sáng",              "example_en": "I always eat breakfast.",                    "example_vi": "Tôi luôn ăn sáng.",                           "level": "A2"},
    {"text": "lunch",          "phonetic": "/lʌntʃ/",         "part_of_speech": "noun",        "definition_en": "A meal eaten in the middle of the day",             "definition_vi": "Bữa trưa",              "example_en": "We have lunch at noon.",                     "example_vi": "Chúng tôi ăn trưa vào buổi trưa.",           "level": "A2"},
    {"text": "dinner",         "phonetic": "/ˈdɪnər/",        "part_of_speech": "noun",        "definition_en": "The main meal of the day eaten in the evening",      "definition_vi": "Bữa tối",               "example_en": "Dinner is ready at 7.",                      "example_vi": "Bữa tối đã sẵn sàng lúc 7 giờ.",             "level": "A2"},
    {"text": "kitchen",        "phonetic": "/ˈkɪtʃɪn/",       "part_of_speech": "noun",        "definition_en": "A room where food is prepared",                     "definition_vi": "Nhà bếp",               "example_en": "She is cooking in the kitchen.",             "example_vi": "Cô ấy đang nấu ăn trong bếp.",               "level": "A2"},
    {"text": "bedroom",        "phonetic": "/ˈbedruːm/",      "part_of_speech": "noun",        "definition_en": "A room used for sleeping",                          "definition_vi": "Phòng ngủ",             "example_en": "My bedroom is on the second floor.",         "example_vi": "Phòng ngủ của tôi ở tầng hai.",               "level": "A2"},
    {"text": "garden",         "phonetic": "/ˈɡɑːrdən/",      "part_of_speech": "noun",        "definition_en": "A piece of ground for growing plants",               "definition_vi": "Khu vườn",              "example_en": "We grow flowers in the garden.",             "example_vi": "Chúng tôi trồng hoa trong vườn.",             "level": "A2"},
    {"text": "river",          "phonetic": "/ˈrɪvər/",        "part_of_speech": "noun",        "definition_en": "A large natural stream of water",                   "definition_vi": "Dòng sông",             "example_en": "The river flows to the sea.",                "example_vi": "Dòng sông chảy ra biển.",                     "level": "A2"},
    {"text": "mountain",       "phonetic": "/ˈmaʊntən/",      "part_of_speech": "noun",        "definition_en": "A large natural elevation of the earth",            "definition_vi": "Ngọn núi",              "example_en": "We climbed the mountain.",                   "example_vi": "Chúng tôi leo lên ngọn núi.",                 "level": "A2"},
    {"text": "beach",          "phonetic": "/biːtʃ/",         "part_of_speech": "noun",        "definition_en": "A sandy area by the sea or lake",                   "definition_vi": "Bãi biển",              "example_en": "We went to the beach last summer.",          "example_vi": "Chúng tôi đã đến bãi biển mùa hè trước.",    "level": "A2"},
    {"text": "airport",        "phonetic": "/ˈeərpɔːrt/",     "part_of_speech": "noun",        "definition_en": "A place where aircraft take off and land",           "definition_vi": "Sân bay",               "example_en": "We arrived at the airport early.",           "example_vi": "Chúng tôi đến sân bay sớm.",                  "level": "A2"},
    {"text": "ticket",         "phonetic": "/ˈtɪkɪt/",        "part_of_speech": "noun",        "definition_en": "A card that gives you the right to enter or travel", "definition_vi": "Vé",                    "example_en": "I bought a ticket to Hanoi.",                "example_vi": "Tôi mua vé đi Hà Nội.",                       "level": "A2"},
    {"text": "hotel",          "phonetic": "/hoʊˈtel/",        "part_of_speech": "noun",        "definition_en": "A building where people pay to stay",                "definition_vi": "Khách sạn",             "example_en": "We stayed at a nice hotel.",                 "example_vi": "Chúng tôi ở một khách sạn đẹp.",              "level": "A2"},
    {"text": "map",            "phonetic": "/mæp/",           "part_of_speech": "noun",        "definition_en": "A drawing of a place showing roads and areas",       "definition_vi": "Bản đồ",                "example_en": "Use the map to find the way.",               "example_vi": "Dùng bản đồ để tìm đường.",                   "level": "A2"},
    {"text": "newspaper",      "phonetic": "/ˈnjuːzpeɪpər/",  "part_of_speech": "noun",        "definition_en": "A printed daily publication of news",               "definition_vi": "Báo / tờ báo",          "example_en": "He reads the newspaper every morning.",      "example_vi": "Anh ấy đọc báo mỗi buổi sáng.",              "level": "A2"},
    {"text": "computer",       "phonetic": "/kəmˈpjuːtər/",   "part_of_speech": "noun",        "definition_en": "An electronic device that processes data",           "definition_vi": "Máy tính",              "example_en": "I work on a computer all day.",              "example_vi": "Tôi làm việc trên máy tính cả ngày.",         "level": "A2"},
    {"text": "internet",       "phonetic": "/ˈɪntərnet/",     "part_of_speech": "noun",        "definition_en": "A global computer network",                         "definition_vi": "Mạng internet",         "example_en": "I use the internet for research.",           "example_vi": "Tôi dùng internet để nghiên cứu.",            "level": "A2"},
    {"text": "language",       "phonetic": "/ˈlæŋɡwɪdʒ/",    "part_of_speech": "noun",        "definition_en": "A system of communication used by a country",        "definition_vi": "Ngôn ngữ",              "example_en": "English is a global language.",              "example_vi": "Tiếng Anh là ngôn ngữ toàn cầu.",             "level": "A2"},
    {"text": "exercise",       "phonetic": "/ˈeksərsaɪz/",    "part_of_speech": "noun",        "definition_en": "Physical activity done to keep fit",                 "definition_vi": "Bài tập / tập thể dục", "example_en": "Daily exercise keeps you healthy.",           "example_vi": "Tập thể dục hằng ngày giúp bạn khỏe mạnh.",  "level": "A2"},

    # ── B1 (35 từ) ─────────────────────────────────────────────────────────────
    {"text": "environment",    "phonetic": "/ɪnˈvaɪrənmənt/",  "part_of_speech": "noun",        "definition_en": "The natural world around us",                                       "definition_vi": "Môi trường",              "example_en": "We must protect the environment.",             "example_vi": "Chúng ta phải bảo vệ môi trường.",              "level": "B1"},
    {"text": "opportunity",    "phonetic": "/ˌɒpəˈtjuːnɪti/",  "part_of_speech": "noun",        "definition_en": "A set of circumstances that makes something possible",               "definition_vi": "Cơ hội",                  "example_en": "This is a great opportunity for you.",         "example_vi": "Đây là một cơ hội tuyệt vời cho bạn.",          "level": "B1"},
    {"text": "society",        "phonetic": "/səˈsaɪɪti/",       "part_of_speech": "noun",        "definition_en": "The community of people living together",                            "definition_vi": "Xã hội",                  "example_en": "Technology changes society rapidly.",           "example_vi": "Công nghệ thay đổi xã hội nhanh chóng.",        "level": "B1"},
    {"text": "culture",        "phonetic": "/ˈkʌltʃər/",        "part_of_speech": "noun",        "definition_en": "The ideas and customs of a group of people",                        "definition_vi": "Văn hóa",                 "example_en": "Vietnamese culture is rich and diverse.",       "example_vi": "Văn hóa Việt Nam phong phú và đa dạng.",        "level": "B1"},
    {"text": "technology",     "phonetic": "/tekˈnɒlədʒi/",     "part_of_speech": "noun",        "definition_en": "The application of scientific knowledge",                           "definition_vi": "Công nghệ",               "example_en": "Technology has transformed our lives.",         "example_vi": "Công nghệ đã biến đổi cuộc sống của chúng ta.", "level": "B1"},
    {"text": "education",      "phonetic": "/ˌedjʊˈkeɪʃən/",    "part_of_speech": "noun",        "definition_en": "The process of receiving or giving instruction",                    "definition_vi": "Giáo dục",                "example_en": "Education is the key to success.",             "example_vi": "Giáo dục là chìa khóa dẫn đến thành công.",    "level": "B1"},
    {"text": "experience",     "phonetic": "/ɪkˈspɪəriəns/",    "part_of_speech": "noun",        "definition_en": "Practical contact with and observation of facts",                   "definition_vi": "Kinh nghiệm",             "example_en": "She has ten years of teaching experience.",     "example_vi": "Cô ấy có mười năm kinh nghiệm giảng dạy.",     "level": "B1"},
    {"text": "communicate",    "phonetic": "/kəˈmjuːnɪkeɪt/",   "part_of_speech": "verb",        "definition_en": "To share or exchange information",                                  "definition_vi": "Giao tiếp",               "example_en": "It's important to communicate clearly.",        "example_vi": "Giao tiếp rõ ràng là điều quan trọng.",         "level": "B1"},
    {"text": "achievement",    "phonetic": "/əˈtʃiːvmənt/",     "part_of_speech": "noun",        "definition_en": "A thing done successfully with effort",                             "definition_vi": "Thành tích",              "example_en": "Winning the award was a great achievement.",    "example_vi": "Giành được giải thưởng là một thành tích lớn.", "level": "B1"},
    {"text": "challenge",      "phonetic": "/ˈtʃælɪndʒ/",       "part_of_speech": "noun",        "definition_en": "A task that is difficult but stimulating",                          "definition_vi": "Thử thách",               "example_en": "Learning a language is a real challenge.",      "example_vi": "Học một ngôn ngữ là một thử thách thực sự.",    "level": "B1"},
    {"text": "government",     "phonetic": "/ˈɡʌvənmənt/",      "part_of_speech": "noun",        "definition_en": "The group of people who control a country",                         "definition_vi": "Chính phủ",               "example_en": "The government announced new policies.",        "example_vi": "Chính phủ thông báo các chính sách mới.",        "level": "B1"},
    {"text": "economy",        "phonetic": "/ɪˈkɒnəmi/",        "part_of_speech": "noun",        "definition_en": "The system of trade and production in a country",                   "definition_vi": "Nền kinh tế",             "example_en": "The economy is growing steadily.",              "example_vi": "Nền kinh tế đang phát triển ổn định.",           "level": "B1"},
    {"text": "health",         "phonetic": "/helθ/",             "part_of_speech": "noun",        "definition_en": "The state of being free from illness",                              "definition_vi": "Sức khỏe",                "example_en": "Good health is more important than wealth.",    "example_vi": "Sức khỏe tốt quan trọng hơn tiền bạc.",         "level": "B1"},
    {"text": "pollution",      "phonetic": "/pəˈluːʃən/",       "part_of_speech": "noun",        "definition_en": "The presence of harmful substances in the environment",             "definition_vi": "Ô nhiễm",                 "example_en": "Air pollution is a serious problem.",           "example_vi": "Ô nhiễm không khí là vấn đề nghiêm trọng.",     "level": "B1"},
    {"text": "solution",       "phonetic": "/səˈluːʃən/",       "part_of_speech": "noun",        "definition_en": "A means of solving a problem",                                     "definition_vi": "Giải pháp",               "example_en": "We need to find a solution quickly.",           "example_vi": "Chúng ta cần tìm giải pháp nhanh chóng.",       "level": "B1"},
    {"text": "problem",        "phonetic": "/ˈprɒbləm/",        "part_of_speech": "noun",        "definition_en": "A matter that is difficult to deal with",                          "definition_vi": "Vấn đề / bài toán",       "example_en": "We have a serious problem to solve.",           "example_vi": "Chúng ta có một vấn đề nghiêm trọng cần giải.", "level": "B1"},
    {"text": "decision",       "phonetic": "/dɪˈsɪʒən/",        "part_of_speech": "noun",        "definition_en": "A conclusion reached after consideration",                          "definition_vi": "Quyết định",              "example_en": "It was a difficult decision to make.",          "example_vi": "Đó là một quyết định khó khăn phải đưa ra.",    "level": "B1"},
    {"text": "information",    "phonetic": "/ˌɪnfəˈmeɪʃən/",   "part_of_speech": "noun",        "definition_en": "Facts provided or learned about something",                         "definition_vi": "Thông tin",               "example_en": "I need more information about this.",           "example_vi": "Tôi cần thêm thông tin về điều này.",            "level": "B1"},
    {"text": "relationship",   "phonetic": "/rɪˈleɪʃənʃɪp/",   "part_of_speech": "noun",        "definition_en": "The way two people or things are connected",                        "definition_vi": "Mối quan hệ",             "example_en": "They have a good working relationship.",        "example_vi": "Họ có mối quan hệ làm việc tốt.",                "level": "B1"},
    {"text": "opinion",        "phonetic": "/əˈpɪnjən/",        "part_of_speech": "noun",        "definition_en": "A view or judgement formed about something",                        "definition_vi": "Ý kiến / quan điểm",      "example_en": "In my opinion, we should act now.",             "example_vi": "Theo ý kiến của tôi, chúng ta nên hành động.",  "level": "B1"},
    {"text": "describe",       "phonetic": "/dɪˈskraɪb/",       "part_of_speech": "verb",        "definition_en": "To give a detailed account of something",                          "definition_vi": "Mô tả",                   "example_en": "Can you describe what happened?",               "example_vi": "Bạn có thể mô tả những gì đã xảy ra không?",    "level": "B1"},
    {"text": "develop",        "phonetic": "/dɪˈveləp/",        "part_of_speech": "verb",        "definition_en": "To grow or cause to grow more advanced",                           "definition_vi": "Phát triển",              "example_en": "We want to develop new skills.",                "example_vi": "Chúng tôi muốn phát triển kỹ năng mới.",        "level": "B1"},
    {"text": "improve",        "phonetic": "/ɪmˈpruːv/",        "part_of_speech": "verb",        "definition_en": "To make or become better",                                         "definition_vi": "Cải thiện / cải tiến",    "example_en": "I want to improve my English.",                 "example_vi": "Tôi muốn cải thiện tiếng Anh của mình.",        "level": "B1"},
    {"text": "discuss",        "phonetic": "/dɪˈskʌs/",         "part_of_speech": "verb",        "definition_en": "To talk about something with another person",                       "definition_vi": "Thảo luận",               "example_en": "Let's discuss the plan together.",              "example_vi": "Hãy cùng thảo luận về kế hoạch.",               "level": "B1"},
    {"text": "explain",        "phonetic": "/ɪkˈspleɪn/",       "part_of_speech": "verb",        "definition_en": "To make something clear by describing it",                         "definition_vi": "Giải thích",              "example_en": "Please explain your idea to us.",               "example_vi": "Vui lòng giải thích ý tưởng của bạn cho chúng.", "level": "B1"},
    {"text": "advantage",      "phonetic": "/ədˈvɑːntɪdʒ/",     "part_of_speech": "noun",        "definition_en": "A condition that puts one in a better position",                    "definition_vi": "Lợi thế / ưu điểm",      "example_en": "Being bilingual is a big advantage.",           "example_vi": "Biết hai ngôn ngữ là một lợi thế lớn.",          "level": "B1"},
    {"text": "disadvantage",   "phonetic": "/ˌdɪsədˈvɑːntɪdʒ/", "part_of_speech": "noun",       "definition_en": "An unfavourable circumstance",                                      "definition_vi": "Bất lợi / nhược điểm",   "example_en": "The main disadvantage is the cost.",            "example_vi": "Bất lợi chính là chi phí.",                      "level": "B1"},
    {"text": "important",      "phonetic": "/ɪmˈpɔːrtənt/",     "part_of_speech": "adjective",   "definition_en": "Of great significance or value",                                   "definition_vi": "Quan trọng",              "example_en": "It is important to be honest.",                 "example_vi": "Trung thực là điều quan trọng.",                 "level": "B1"},
    {"text": "necessary",      "phonetic": "/ˈnesəseri/",        "part_of_speech": "adjective",   "definition_en": "Required to be done; essential",                                   "definition_vi": "Cần thiết",               "example_en": "It is necessary to study every day.",           "example_vi": "Học tập mỗi ngày là điều cần thiết.",            "level": "B1"},
    {"text": "popular",        "phonetic": "/ˈpɒpjʊlər/",       "part_of_speech": "adjective",   "definition_en": "Liked or admired by many people",                                  "definition_vi": "Phổ biến",                "example_en": "This song is very popular.",                    "example_vi": "Bài hát này rất phổ biến.",                      "level": "B1"},
    {"text": "traditional",    "phonetic": "/trəˈdɪʃənəl/",     "part_of_speech": "adjective",   "definition_en": "Relating to long-established customs",                             "definition_vi": "Truyền thống",            "example_en": "They wore traditional costumes.",               "example_vi": "Họ mặc trang phục truyền thống.",                "level": "B1"},
    {"text": "modern",         "phonetic": "/ˈmɒdərn/",         "part_of_speech": "adjective",   "definition_en": "Relating to the present or recent times",                          "definition_vi": "Hiện đại",                "example_en": "This is a modern building.",                    "example_vi": "Đây là một tòa nhà hiện đại.",                   "level": "B1"},
    {"text": "local",          "phonetic": "/ˈloʊkəl/",         "part_of_speech": "adjective",   "definition_en": "Relating to a particular area or neighborhood",                    "definition_vi": "Địa phương",              "example_en": "I shop at the local market.",                   "example_vi": "Tôi mua sắm ở chợ địa phương.",                  "level": "B1"},
    {"text": "natural",        "phonetic": "/ˈnætʃərəl/",       "part_of_speech": "adjective",   "definition_en": "Existing in or caused by nature",                                  "definition_vi": "Tự nhiên",                "example_en": "This park is a natural area.",                  "example_vi": "Công viên này là khu vực tự nhiên.",              "level": "B1"},
    {"text": "succeed",        "phonetic": "/səkˈsiːd/",         "part_of_speech": "verb",        "definition_en": "To achieve a desired aim",                                         "definition_vi": "Thành công",              "example_en": "Hard work helps you succeed.",                  "example_vi": "Chăm chỉ giúp bạn thành công.",                  "level": "B1"},

    # ── B2 (35 từ) ─────────────────────────────────────────────────────────────
    {"text": "innovation",       "phonetic": "/ˌɪnəˈveɪʃən/",    "part_of_speech": "noun",        "definition_en": "The introduction of new ideas or methods",                    "definition_vi": "Đổi mới / sáng tạo",      "example_en": "Innovation drives economic growth.",              "example_vi": "Đổi mới thúc đẩy tăng trưởng kinh tế.",         "level": "B2"},
    {"text": "sustainable",      "phonetic": "/səˈsteɪnəbəl/",    "part_of_speech": "adjective",   "definition_en": "Able to be maintained without depleting resources",            "definition_vi": "Bền vững",                "example_en": "We need sustainable development.",                "example_vi": "Chúng ta cần phát triển bền vững.",               "level": "B2"},
    {"text": "globalization",    "phonetic": "/ˌɡloʊbələˈzeɪʃən/","part_of_speech": "noun",        "definition_en": "The process of international integration",                    "definition_vi": "Toàn cầu hóa",            "example_en": "Globalization has connected the world.",          "example_vi": "Toàn cầu hóa đã kết nối thế giới.",              "level": "B2"},
    {"text": "perspective",      "phonetic": "/pərˈspektɪv/",     "part_of_speech": "noun",        "definition_en": "A particular way of thinking about something",                 "definition_vi": "Quan điểm / góc nhìn",    "example_en": "Consider this from a different perspective.",     "example_vi": "Hãy xem xét điều này từ một góc nhìn khác.",     "level": "B2"},
    {"text": "consequence",      "phonetic": "/ˈkɒnsɪkwəns/",     "part_of_speech": "noun",        "definition_en": "A result or effect of an action",                             "definition_vi": "Hậu quả",                 "example_en": "Every action has consequences.",                  "example_vi": "Mọi hành động đều có hậu quả.",                  "level": "B2"},
    {"text": "significant",      "phonetic": "/sɪɡˈnɪfɪkənt/",   "part_of_speech": "adjective",   "definition_en": "Sufficiently great or important",                             "definition_vi": "Đáng kể / quan trọng",    "example_en": "There has been a significant improvement.",       "example_vi": "Đã có sự cải thiện đáng kể.",                    "level": "B2"},
    {"text": "hypothesis",       "phonetic": "/haɪˈpɒθɪsɪs/",     "part_of_speech": "noun",        "definition_en": "A proposed explanation made on limited evidence",              "definition_vi": "Giả thuyết",              "example_en": "The scientist tested her hypothesis.",            "example_vi": "Nhà khoa học đã kiểm tra giả thuyết của mình.",  "level": "B2"},
    {"text": "collaboration",    "phonetic": "/kəˌlæbəˈreɪʃən/",  "part_of_speech": "noun",        "definition_en": "The action of working with someone",                          "definition_vi": "Hợp tác",                 "example_en": "Success requires teamwork and collaboration.",    "example_vi": "Thành công đòi hỏi tinh thần đồng đội và hợp tác.", "level": "B2"},
    {"text": "entrepreneurship", "phonetic": "/ˌɒntrəprəˈnɜːʃɪp/","part_of_speech": "noun",        "definition_en": "The activity of setting up a business",                       "definition_vi": "Tinh thần khởi nghiệp",   "example_en": "Entrepreneurship requires courage and vision.",   "example_vi": "Khởi nghiệp đòi hỏi sự can đảm và tầm nhìn.",   "level": "B2"},
    {"text": "phenomenon",       "phonetic": "/fɪˈnɒmɪnən/",       "part_of_speech": "noun",        "definition_en": "A fact or event that is observable",                          "definition_vi": "Hiện tượng",              "example_en": "Climate change is a global phenomenon.",          "example_vi": "Biến đổi khí hậu là một hiện tượng toàn cầu.",   "level": "B2"},
    {"text": "ambiguous",        "phonetic": "/æmˈbɪɡjuəs/",       "part_of_speech": "adjective",   "definition_en": "Open to more than one interpretation",                        "definition_vi": "Mơ hồ / không rõ ràng",   "example_en": "His reply was deliberately ambiguous.",           "example_vi": "Câu trả lời của anh ấy cố tình mơ hồ.",          "level": "B2"},
    {"text": "comprehensive",    "phonetic": "/ˌkɒmprɪˈhensɪv/",   "part_of_speech": "adjective",   "definition_en": "Including all or nearly all elements",                        "definition_vi": "Toàn diện / đầy đủ",      "example_en": "They gave a comprehensive report.",               "example_vi": "Họ đã đưa ra một báo cáo toàn diện.",            "level": "B2"},
    {"text": "controversy",      "phonetic": "/ˈkɒntrəvɜːrsi/",    "part_of_speech": "noun",        "definition_en": "Prolonged public disagreement or debate",                     "definition_vi": "Tranh cãi / gây tranh luận", "example_en": "The new law caused controversy.",              "example_vi": "Luật mới gây ra tranh cãi.",                      "level": "B2"},
    {"text": "emphasise",        "phonetic": "/ˈemfəsaɪz/",        "part_of_speech": "verb",        "definition_en": "To give special importance to something",                     "definition_vi": "Nhấn mạnh",               "example_en": "She emphasised the need for change.",             "example_vi": "Cô ấy nhấn mạnh sự cần thiết phải thay đổi.",   "level": "B2"},
    {"text": "evaluate",         "phonetic": "/ɪˈvæljueɪt/",       "part_of_speech": "verb",        "definition_en": "To assess or appraise something",                             "definition_vi": "Đánh giá",                "example_en": "We evaluate students twice a year.",              "example_vi": "Chúng tôi đánh giá học sinh hai lần mỗi năm.",   "level": "B2"},
    {"text": "interpret",        "phonetic": "/ɪnˈtɜːrprɪt/",      "part_of_speech": "verb",        "definition_en": "To explain the meaning of something",                         "definition_vi": "Giải nghĩa / thông dịch", "example_en": "Please interpret this data for us.",              "example_vi": "Vui lòng giải thích dữ liệu này cho chúng tôi.", "level": "B2"},
    {"text": "analyse",          "phonetic": "/ˈænəlaɪz/",         "part_of_speech": "verb",        "definition_en": "To examine something in detail",                              "definition_vi": "Phân tích",               "example_en": "We need to analyse the results.",                 "example_vi": "Chúng ta cần phân tích kết quả.",                 "level": "B2"},
    {"text": "justify",          "phonetic": "/ˈdʒʌstɪfaɪ/",       "part_of_speech": "verb",        "definition_en": "To show or prove something to be right",                      "definition_vi": "Biện minh / chứng minh",  "example_en": "Can you justify your decision?",                 "example_vi": "Bạn có thể biện minh cho quyết định của mình?",  "level": "B2"},
    {"text": "implication",      "phonetic": "/ˌɪmplɪˈkeɪʃən/",    "part_of_speech": "noun",        "definition_en": "A conclusion that can be drawn from something",               "definition_vi": "Hàm ý / tác động",        "example_en": "What are the implications of this?",              "example_vi": "Tác động của điều này là gì?",                    "level": "B2"},
    {"text": "bias",             "phonetic": "/ˈbaɪəs/",            "part_of_speech": "noun",        "definition_en": "An inclination or prejudice that unfairly affects judgment",  "definition_vi": "Sự thiên vị / thiên kiến","example_en": "The report shows a clear bias.",                  "example_vi": "Báo cáo cho thấy sự thiên vị rõ ràng.",          "level": "B2"},
    {"text": "contradiction",    "phonetic": "/ˌkɒntrəˈdɪkʃən/",   "part_of_speech": "noun",        "definition_en": "A combination of statements that are opposite",               "definition_vi": "Mâu thuẫn",               "example_en": "There is a contradiction in your argument.",     "example_vi": "Có sự mâu thuẫn trong lập luận của bạn.",        "level": "B2"},
    {"text": "assumption",       "phonetic": "/əˈsʌmpʃən/",         "part_of_speech": "noun",        "definition_en": "Something accepted as true without proof",                    "definition_vi": "Giả định",                "example_en": "That assumption may be wrong.",                   "example_vi": "Giả định đó có thể sai.",                         "level": "B2"},
    {"text": "priority",         "phonetic": "/praɪˈɒrɪti/",        "part_of_speech": "noun",        "definition_en": "Something considered more important than others",              "definition_vi": "Ưu tiên",                 "example_en": "Education is our top priority.",                  "example_vi": "Giáo dục là ưu tiên hàng đầu của chúng tôi.",   "level": "B2"},
    {"text": "impact",           "phonetic": "/ˈɪmpækt/",           "part_of_speech": "noun",        "definition_en": "A marked effect or influence",                                "definition_vi": "Tác động / ảnh hưởng",    "example_en": "Technology has a huge impact on life.",           "example_vi": "Công nghệ có tác động lớn đến cuộc sống.",       "level": "B2"},
    {"text": "infrastructure",   "phonetic": "/ˈɪnfrəstrʌktʃər/",  "part_of_speech": "noun",        "definition_en": "The basic physical systems of a country",                     "definition_vi": "Cơ sở hạ tầng",          "example_en": "The city improved its infrastructure.",           "example_vi": "Thành phố đã cải thiện cơ sở hạ tầng.",          "level": "B2"},
    {"text": "diversity",        "phonetic": "/daɪˈvɜːrsɪti/",      "part_of_speech": "noun",        "definition_en": "The state of being diverse; variety",                         "definition_vi": "Sự đa dạng",              "example_en": "Cultural diversity enriches society.",            "example_vi": "Sự đa dạng văn hóa làm phong phú xã hội.",      "level": "B2"},

    # ── TOEIC (30 từ) ──────────────────────────────────────────────────────────
    {"text": "negotiate",      "phonetic": "/nɪˈɡoʊʃieɪt/",    "part_of_speech": "verb",        "definition_en": "To try to reach an agreement through discussion",    "definition_vi": "Đàm phán",                  "example_en": "We need to negotiate the contract terms.",          "example_vi": "Chúng ta cần đàm phán các điều khoản hợp đồng.",  "level": "TOEIC"},
    {"text": "revenue",        "phonetic": "/ˈrevənjuː/",       "part_of_speech": "noun",        "definition_en": "Income generated from business activities",          "definition_vi": "Doanh thu",                 "example_en": "Company revenue grew 20% this year.",               "example_vi": "Doanh thu công ty tăng 20% năm nay.",               "level": "TOEIC"},
    {"text": "deadline",       "phonetic": "/ˈdedlaɪn/",        "part_of_speech": "noun",        "definition_en": "The latest time by which something must be done",   "definition_vi": "Thời hạn chót",             "example_en": "Please submit the report before the deadline.",     "example_vi": "Vui lòng nộp báo cáo trước thời hạn chót.",        "level": "TOEIC"},
    {"text": "headquarters",   "phonetic": "/ˈhedˌkwɔːrtərz/",  "part_of_speech": "noun",        "definition_en": "The main offices of an organization",                "definition_vi": "Trụ sở chính",              "example_en": "The headquarters is located in Hanoi.",             "example_vi": "Trụ sở chính đặt tại Hà Nội.",                      "level": "TOEIC"},
    {"text": "agenda",         "phonetic": "/əˈdʒendə/",         "part_of_speech": "noun",        "definition_en": "A list of items to be discussed at a meeting",       "definition_vi": "Chương trình họp",          "example_en": "Please review the meeting agenda.",                 "example_vi": "Vui lòng xem lại chương trình họp.",                "level": "TOEIC"},
    {"text": "invoice",        "phonetic": "/ˈɪnvɔɪs/",         "part_of_speech": "noun",        "definition_en": "A bill sent for goods or services",                  "definition_vi": "Hóa đơn",                   "example_en": "Please send the invoice by email.",                 "example_vi": "Vui lòng gửi hóa đơn qua email.",                   "level": "TOEIC"},
    {"text": "contract",       "phonetic": "/ˈkɒntrækt/",        "part_of_speech": "noun",        "definition_en": "A written legal agreement",                          "definition_vi": "Hợp đồng",                  "example_en": "Both parties signed the contract.",                 "example_vi": "Cả hai bên đã ký hợp đồng.",                        "level": "TOEIC"},
    {"text": "client",         "phonetic": "/ˈklaɪənt/",        "part_of_speech": "noun",        "definition_en": "A person or company that uses a professional service","definition_vi": "Khách hàng",                "example_en": "We must meet our client's requirements.",            "example_vi": "Chúng ta phải đáp ứng yêu cầu của khách hàng.",    "level": "TOEIC"},
    {"text": "supplier",       "phonetic": "/səˈplaɪər/",        "part_of_speech": "noun",        "definition_en": "A company that provides goods or services",          "definition_vi": "Nhà cung cấp",              "example_en": "We work with reliable suppliers.",                  "example_vi": "Chúng tôi làm việc với các nhà cung cấp uy tín.",   "level": "TOEIC"},
    {"text": "profit",         "phonetic": "/ˈprɒfɪt/",         "part_of_speech": "noun",        "definition_en": "Financial gain after deducting costs",               "definition_vi": "Lợi nhuận",                 "example_en": "The company made a large profit.",                  "example_vi": "Công ty đã tạo ra lợi nhuận lớn.",                  "level": "TOEIC"},
    {"text": "budget",         "phonetic": "/ˈbʌdʒɪt/",         "part_of_speech": "noun",        "definition_en": "An estimate of income and expenditure",              "definition_vi": "Ngân sách",                 "example_en": "We must stay within the budget.",                   "example_vi": "Chúng ta phải giữ trong ngân sách.",                 "level": "TOEIC"},
    {"text": "strategy",       "phonetic": "/ˈstrætɪdʒi/",      "part_of_speech": "noun",        "definition_en": "A plan designed to achieve a long-term goal",        "definition_vi": "Chiến lược",                "example_en": "We need a new marketing strategy.",                 "example_vi": "Chúng ta cần một chiến lược tiếp thị mới.",          "level": "TOEIC"},
    {"text": "implement",      "phonetic": "/ˈɪmplɪment/",      "part_of_speech": "verb",        "definition_en": "To put a plan or decision into effect",              "definition_vi": "Thực hiện / triển khai",    "example_en": "We will implement the plan next month.",            "example_vi": "Chúng tôi sẽ thực hiện kế hoạch vào tháng tới.",   "level": "TOEIC"},
    {"text": "proposal",       "phonetic": "/prəˈpoʊzəl/",       "part_of_speech": "noun",        "definition_en": "A formal suggestion or plan",                        "definition_vi": "Đề xuất / bản đề nghị",    "example_en": "She submitted a business proposal.",                "example_vi": "Cô ấy đã nộp một đề xuất kinh doanh.",              "level": "TOEIC"},
    {"text": "schedule",       "phonetic": "/ˈskedʒuːl/",        "part_of_speech": "noun",        "definition_en": "A plan that lists events with their times",          "definition_vi": "Lịch trình / thời gian biểu","example_en": "Please check the project schedule.",               "example_vi": "Vui lòng kiểm tra lịch trình dự án.",               "level": "TOEIC"},
    {"text": "productivity",   "phonetic": "/ˌprɒdʌkˈtɪvɪti/",  "part_of_speech": "noun",        "definition_en": "The efficiency of production",                       "definition_vi": "Năng suất",                 "example_en": "New tools improve productivity.",                   "example_vi": "Công cụ mới cải thiện năng suất.",                   "level": "TOEIC"},
    {"text": "efficient",      "phonetic": "/ɪˈfɪʃənt/",         "part_of_speech": "adjective",   "definition_en": "Achieving maximum output with minimum wasted effort","definition_vi": "Hiệu quả",                  "example_en": "We need a more efficient process.",                 "example_vi": "Chúng ta cần quy trình hiệu quả hơn.",               "level": "TOEIC"},
    {"text": "colleague",      "phonetic": "/ˈkɒliːɡ/",          "part_of_speech": "noun",        "definition_en": "A person with whom one works",                       "definition_vi": "Đồng nghiệp",               "example_en": "My colleague helped me with the report.",            "example_vi": "Đồng nghiệp của tôi giúp tôi với báo cáo.",         "level": "TOEIC"},
    {"text": "feedback",       "phonetic": "/ˈfiːdbæk/",         "part_of_speech": "noun",        "definition_en": "Information about reactions to a product or service","definition_vi": "Phản hồi",                  "example_en": "Customer feedback is very important.",              "example_vi": "Phản hồi của khách hàng rất quan trọng.",            "level": "TOEIC"},
    {"text": "distribution",   "phonetic": "/ˌdɪstrɪˈbjuːʃən/", "part_of_speech": "noun",        "definition_en": "The action of sharing or supplying goods",           "definition_vi": "Phân phối",                 "example_en": "They improved the distribution network.",            "example_vi": "Họ cải thiện mạng lưới phân phối.",                  "level": "TOEIC"},
    {"text": "inventory",      "phonetic": "/ˈɪnvəntɔːri/",     "part_of_speech": "noun",        "definition_en": "A complete list of goods in stock",                  "definition_vi": "Hàng tồn kho",              "example_en": "We check the inventory monthly.",                   "example_vi": "Chúng tôi kiểm tra hàng tồn kho hàng tháng.",       "level": "TOEIC"},
    {"text": "promotion",      "phonetic": "/prəˈmoʊʃən/",        "part_of_speech": "noun",        "definition_en": "Advancement to a higher position",                   "definition_vi": "Thăng chức / khuyến mãi",  "example_en": "She received a promotion last month.",              "example_vi": "Cô ấy được thăng chức tháng trước.",                 "level": "TOEIC"},
    {"text": "complaint",      "phonetic": "/kəmˈpleɪnt/",        "part_of_speech": "noun",        "definition_en": "An expression of dissatisfaction",                   "definition_vi": "Khiếu nại / phàn nàn",     "example_en": "We received a customer complaint.",                 "example_vi": "Chúng tôi nhận được khiếu nại của khách hàng.",     "level": "TOEIC"},
    {"text": "reimbursement",  "phonetic": "/ˌriːɪmˈbɜːrsmənt/", "part_of_speech": "noun",        "definition_en": "Repayment of money spent",                           "definition_vi": "Hoàn trả / bồi hoàn",      "example_en": "You can claim reimbursement for travel costs.",     "example_vi": "Bạn có thể yêu cầu hoàn trả chi phí đi lại.",       "level": "TOEIC"},
    {"text": "transaction",    "phonetic": "/trænˈzækʃən/",       "part_of_speech": "noun",        "definition_en": "An instance of buying or selling",                   "definition_vi": "Giao dịch",                 "example_en": "The transaction was completed online.",             "example_vi": "Giao dịch được thực hiện trực tuyến.",               "level": "TOEIC"},
    {"text": "freight",        "phonetic": "/freɪt/",             "part_of_speech": "noun",        "definition_en": "Goods transported by truck, ship or plane",          "definition_vi": "Hàng hóa vận chuyển",       "example_en": "The freight arrives next Tuesday.",                 "example_vi": "Hàng hóa sẽ đến vào thứ Ba tới.",                    "level": "TOEIC"},
    {"text": "merger",         "phonetic": "/ˈmɜːrdʒər/",         "part_of_speech": "noun",        "definition_en": "The combination of two companies into one",          "definition_vi": "Sáp nhập",                  "example_en": "The merger created a powerful company.",            "example_vi": "Vụ sáp nhập đã tạo ra một công ty mạnh.",            "level": "TOEIC"},
    {"text": "overhead",       "phonetic": "/ˈoʊvərhed/",         "part_of_speech": "noun",        "definition_en": "The ongoing business expenses not related to production","definition_vi": "Chi phí chung",           "example_en": "We need to reduce our overhead costs.",             "example_vi": "Chúng ta cần giảm chi phí chung.",                   "level": "TOEIC"},
    {"text": "quarterly",      "phonetic": "/ˈkwɔːrtərli/",       "part_of_speech": "adjective",   "definition_en": "Happening four times a year",                       "definition_vi": "Hàng quý",                  "example_en": "The quarterly report looks positive.",              "example_vi": "Báo cáo hàng quý trông tích cực.",                   "level": "TOEIC"},
    {"text": "workforce",      "phonetic": "/ˈwɜːrkfɔːrs/",       "part_of_speech": "noun",        "definition_en": "The people engaged in or available for work",        "definition_vi": "Lực lượng lao động",        "example_en": "They are expanding their workforce.",               "example_vi": "Họ đang mở rộng lực lượng lao động.",                "level": "TOEIC"},
    {"text": "liability",      "phonetic": "/ˌlaɪəˈbɪlɪti/",      "part_of_speech": "noun",        "definition_en": "The state of being responsible for something",       "definition_vi": "Trách nhiệm pháp lý / nợ", "example_en": "The company has significant liabilities.",          "example_vi": "Công ty có trách nhiệm pháp lý đáng kể.",            "level": "TOEIC"},

    # ── C1 (20 từ) ─────────────────────────────────────────────────────────────
    {"text": "ubiquitous",     "phonetic": "/juːˈbɪkwɪtəs/",    "part_of_speech": "adjective",   "definition_en": "Present, appearing, or found everywhere",           "definition_vi": "Có mặt khắp nơi",           "example_en": "Smartphones are now ubiquitous.",                   "example_vi": "Điện thoại thông minh hiện nay có mặt khắp nơi.",   "level": "C1"},
    {"text": "eloquent",       "phonetic": "/ˈeləkwənt/",        "part_of_speech": "adjective",   "definition_en": "Fluent or persuasive in speaking or writing",        "definition_vi": "Hùng hồn / lưu loát",      "example_en": "She gave an eloquent speech.",                      "example_vi": "Cô ấy đã có một bài phát biểu hùng hồn.",            "level": "C1"},
    {"text": "paradigm",       "phonetic": "/ˈpærədaɪm/",        "part_of_speech": "noun",        "definition_en": "A typical example or pattern of something",         "definition_vi": "Mô hình / khuôn mẫu",      "example_en": "This is a new paradigm in science.",                "example_vi": "Đây là một mô hình mới trong khoa học.",              "level": "C1"},
    {"text": "pragmatic",      "phonetic": "/præɡˈmætɪk/",       "part_of_speech": "adjective",   "definition_en": "Dealing with things sensibly and realistically",    "definition_vi": "Thực dụng",                 "example_en": "We need a pragmatic approach.",                     "example_vi": "Chúng ta cần cách tiếp cận thực dụng.",              "level": "C1"},
    {"text": "scrutinise",     "phonetic": "/ˈskruːtɪnaɪz/",     "part_of_speech": "verb",        "definition_en": "To examine or investigate closely",                 "definition_vi": "Xem xét kỹ lưỡng",         "example_en": "The report was scrutinised carefully.",             "example_vi": "Báo cáo được xem xét kỹ lưỡng.",                     "level": "C1"},
    {"text": "albeit",         "phonetic": "/ɔːlˈbiːɪt/",        "part_of_speech": "conjunction", "definition_en": "Although; even though",                             "definition_vi": "Mặc dù",                    "example_en": "It was an interesting, albeit long, meeting.",       "example_vi": "Đó là một cuộc họp thú vị, mặc dù dài.",             "level": "C1"},
    {"text": "coherent",       "phonetic": "/koʊˈhɪərənt/",      "part_of_speech": "adjective",   "definition_en": "Logical and consistent",                            "definition_vi": "Mạch lạc / nhất quán",     "example_en": "The plan is coherent and well structured.",         "example_vi": "Kế hoạch mạch lạc và có cấu trúc tốt.",              "level": "C1"},
    {"text": "mitigate",       "phonetic": "/ˈmɪtɪɡeɪt/",        "part_of_speech": "verb",        "definition_en": "To make something less severe or serious",          "definition_vi": "Giảm nhẹ / giảm thiểu",    "example_en": "We can mitigate the risks by planning.",            "example_vi": "Chúng ta có thể giảm thiểu rủi ro bằng cách lập kế.", "level": "C1"},
    {"text": "nuance",         "phonetic": "/ˈnjuːɑːns/",        "part_of_speech": "noun",        "definition_en": "A subtle difference in meaning or expression",       "definition_vi": "Sắc thái / chi tiết tinh tế","example_en": "The poem is full of nuance.",                       "example_vi": "Bài thơ đầy sắc thái.",                              "level": "C1"},
    {"text": "inherent",       "phonetic": "/ɪnˈhɪərənt/",       "part_of_speech": "adjective",   "definition_en": "Existing as a natural or basic part of something",  "definition_vi": "Vốn có / cố hữu",          "example_en": "There are inherent risks in every business.",       "example_vi": "Mọi doanh nghiệp đều có rủi ro vốn có.",             "level": "C1"},
    {"text": "rhetoric",       "phonetic": "/ˈretərɪk/",         "part_of_speech": "noun",        "definition_en": "Language designed to have a persuasive effect",     "definition_vi": "Lời lẽ hoa mỹ / tu từ",   "example_en": "His speech was full of empty rhetoric.",            "example_vi": "Bài phát biểu của anh ấy đầy lời lẽ sáo rỗng.",    "level": "C1"},
    {"text": "unprecedented",  "phonetic": "/ʌnˈpresɪdentɪd/",   "part_of_speech": "adjective",   "definition_en": "Never done or known before",                        "definition_vi": "Chưa từng có tiền lệ",     "example_en": "The pandemic caused unprecedented disruption.",     "example_vi": "Đại dịch gây ra sự gián đoạn chưa từng có.",        "level": "C1"},
    {"text": "plausible",      "phonetic": "/ˈplɔːzɪbəl/",       "part_of_speech": "adjective",   "definition_en": "Seeming reasonable or probable",                    "definition_vi": "Có thể chấp nhận được / có lý", "example_en": "That is a plausible explanation.",              "example_vi": "Đó là một giải thích có lý.",                         "level": "C1"},
    {"text": "ambivalent",     "phonetic": "/æmˈbɪvələnt/",       "part_of_speech": "adjective",   "definition_en": "Having mixed feelings about something",             "definition_vi": "Lưỡng lự / có cảm xúc trái chiều", "example_en": "She felt ambivalent about the decision.",  "example_vi": "Cô ấy cảm thấy lưỡng lự về quyết định.",           "level": "C1"},
    {"text": "catalyst",       "phonetic": "/ˈkætəlɪst/",        "part_of_speech": "noun",        "definition_en": "Something that causes change or events",            "definition_vi": "Chất xúc tác / nguyên nhân thúc đẩy", "example_en": "Education is a catalyst for development.", "example_vi": "Giáo dục là chất xúc tác cho sự phát triển.",    "level": "C1"},
    {"text": "obsolete",       "phonetic": "/ˌɒbsəˈliːt/",       "part_of_speech": "adjective",   "definition_en": "No longer produced or used; out of date",           "definition_vi": "Lỗi thời / cũ kỹ",         "example_en": "That technology is now obsolete.",                  "example_vi": "Công nghệ đó giờ đã lỗi thời.",                      "level": "C1"},
    {"text": "resilient",      "phonetic": "/rɪˈzɪliənt/",       "part_of_speech": "adjective",   "definition_en": "Able to recover quickly from difficulty",           "definition_vi": "Bền bỉ / phục hồi nhanh",  "example_en": "Resilient communities recover faster.",             "example_vi": "Cộng đồng bền bỉ phục hồi nhanh hơn.",              "level": "C1"},
    {"text": "fluctuate",      "phonetic": "/ˈflʌktʃueɪt/",      "part_of_speech": "verb",        "definition_en": "To rise and fall irregularly",                      "definition_vi": "Biến động / dao động",      "example_en": "Prices fluctuate with supply and demand.",          "example_vi": "Giá cả biến động theo cung và cầu.",                 "level": "C1"},
    {"text": "autonomy",       "phonetic": "/ɔːˈtɒnəmi/",        "part_of_speech": "noun",        "definition_en": "The right to govern oneself",                       "definition_vi": "Quyền tự chủ",              "example_en": "Workers want more autonomy.",                       "example_vi": "Người lao động muốn có nhiều quyền tự chủ hơn.",    "level": "C1"},
    {"text": "profound",       "phonetic": "/prəˈfaʊnd/",         "part_of_speech": "adjective",   "definition_en": "Very great or intense",                             "definition_vi": "Sâu sắc",                   "example_en": "It had a profound effect on me.",                   "example_vi": "Nó có ảnh hưởng sâu sắc đến tôi.",                  "level": "C1"},
]

WORDSETS = [
    {"name": "Từ vựng A1 – Căn bản", "description": "Các từ vựng cơ bản nhất cho người mới bắt đầu học tiếng Anh.", "level": "A1",
     "word_texts": ["hello", "goodbye", "book", "water", "eat", "sleep", "house", "family", "school", "friend", "cat", "dog", "apple", "milk", "sun", "chair", "table", "happy", "big", "small"]},
    {"name": "Từ vựng A2 – Sơ cấp", "description": "Từ vựng giao tiếp hàng ngày cho trình độ sơ cấp.", "level": "A2",
     "word_texts": ["travel", "weather", "shopping", "hospital", "doctor", "market", "restaurant", "holiday", "telephone", "money", "question", "answer", "city", "country", "music", "sport", "colour", "week", "birthday", "teacher"]},
    {"name": "Từ vựng B1 – Trung cấp", "description": "Mở rộng vốn từ cho giao tiếp trung cấp.", "level": "B1",
     "word_texts": ["environment", "opportunity", "society", "culture", "technology", "education", "experience", "communicate", "achievement", "challenge", "government", "economy", "health", "pollution", "solution", "decision", "information", "develop", "improve", "explain"]},
    {"name": "Từ vựng B2 – Trung cao cấp", "description": "Từ vựng học thuật và trình bày ý kiến.", "level": "B2",
     "word_texts": ["innovation", "sustainable", "globalization", "perspective", "consequence", "significant", "hypothesis", "collaboration", "entrepreneurship", "phenomenon", "comprehensive", "evaluate", "analyse", "priority", "impact", "diversity", "justify", "ambiguous", "infrastructure", "bias"]},
    {"name": "TOEIC – Kinh doanh", "description": "Từ vựng thường gặp trong bài thi TOEIC và môi trường công sở.", "level": "TOEIC",
     "word_texts": ["negotiate", "revenue", "deadline", "headquarters", "agenda", "invoice", "contract", "client", "supplier", "profit", "budget", "strategy", "implement", "proposal", "schedule", "productivity", "efficient", "colleague", "feedback", "distribution"]},
    {"name": "C1 – Nâng cao", "description": "Từ vựng học thuật nâng cao cho trình độ C1.", "level": "C1",
     "word_texts": ["ubiquitous", "eloquent", "paradigm", "pragmatic", "coherent", "mitigate", "nuance", "inherent", "rhetoric", "unprecedented", "plausible", "resilient", "fluctuate", "autonomy", "profound", "catalyst", "obsolete", "ambivalent", "scrutinise", "albeit"]},
]

LESSONS = [
    {"title": "Bài 1 – Chào hỏi và giới thiệu", "description": "Học cách chào hỏi và giới thiệu bản thân bằng tiếng Anh.", "level": "A1", "order_index": 1,
     "word_texts": ["hello", "goodbye", "friend", "family", "mother", "father", "happy", "yes", "no", "school"]},
    {"title": "Bài 2 – Cuộc sống hàng ngày", "description": "Từ vựng về các hoạt động sinh hoạt hàng ngày.", "level": "A1", "order_index": 2,
     "word_texts": ["eat", "sleep", "house", "book", "water", "run", "walk", "open", "close", "food"]},
    {"title": "Bài 3 – Vật dụng và màu sắc", "description": "Từ vựng mô tả đồ vật và màu sắc xung quanh.", "level": "A1", "order_index": 3,
     "word_texts": ["chair", "table", "pen", "bag", "hat", "car", "bus", "red", "blue", "big"]},
    {"title": "Bài 4 – Nơi chốn và di chuyển", "description": "Từ vựng về địa điểm và phương tiện di chuyển.", "level": "A2", "order_index": 4,
     "word_texts": ["hospital", "market", "restaurant", "airport", "hotel", "beach", "mountain", "river", "city", "ticket"]},
    {"title": "Bài 5 – Sinh hoạt và bữa ăn", "description": "Từ vựng về thói quen ăn uống và sinh hoạt gia đình.", "level": "A2", "order_index": 5,
     "word_texts": ["breakfast", "lunch", "dinner", "kitchen", "bedroom", "garden", "shopping", "holiday", "birthday", "exercise"]},
    {"title": "Bài 6 – Thông tin và truyền thông", "description": "Từ vựng về công nghệ, truyền thông và thông tin.", "level": "A2", "order_index": 6,
     "word_texts": ["computer", "internet", "language", "newspaper", "map", "telephone", "music", "sport", "question", "answer"]},
    {"title": "Bài 7 – Xã hội và con người", "description": "Từ vựng mô tả xã hội, giáo dục và nghề nghiệp.", "level": "B1", "order_index": 7,
     "word_texts": ["society", "education", "culture", "government", "economy", "health", "opportunity", "relationship", "opinion", "traditional"]},
    {"title": "Bài 8 – Kỹ năng giao tiếp", "description": "Từ vựng dùng trong giao tiếp và diễn đạt ý kiến.", "level": "B1", "order_index": 8,
     "word_texts": ["communicate", "describe", "discuss", "explain", "develop", "improve", "decision", "information", "advantage", "disadvantage"]},
    {"title": "Bài 9 – Môi trường và phát triển", "description": "Từ vựng về môi trường, ô nhiễm và phát triển bền vững.", "level": "B1", "order_index": 9,
     "word_texts": ["environment", "pollution", "solution", "natural", "modern", "traditional", "local", "popular", "necessary", "succeed"]},
    {"title": "Bài 10 – Khoa học và công nghệ", "description": "Từ vựng học thuật về công nghệ và đổi mới.", "level": "B2", "order_index": 10,
     "word_texts": ["technology", "innovation", "hypothesis", "phenomenon", "sustainable", "significant", "comprehensive", "analyse", "evaluate", "impact"]},
    {"title": "Bài 11 – Tư duy phân tích", "description": "Từ vựng diễn đạt quan điểm và phân tích vấn đề.", "level": "B2", "order_index": 11,
     "word_texts": ["perspective", "consequence", "assumption", "bias", "contradiction", "implication", "priority", "diversity", "justify", "ambiguous"]},
    {"title": "Bài 12 – Kinh doanh quốc tế", "description": "Từ vựng TOEIC cho môi trường kinh doanh và văn phòng.", "level": "TOEIC", "order_index": 12,
     "word_texts": ["negotiate", "contract", "client", "supplier", "revenue", "profit", "budget", "invoice", "strategy", "proposal"]},
    {"title": "Bài 13 – Quản lý và vận hành", "description": "Từ vựng về quản lý nhân sự, lịch trình và vận hành.", "level": "TOEIC", "order_index": 13,
     "word_texts": ["schedule", "deadline", "implement", "productivity", "efficient", "colleague", "feedback", "promotion", "complaint", "headquarters"]},
    {"title": "Bài 14 – Tiếng Anh học thuật C1", "description": "Từ vựng nâng cao dành cho văn viết và học thuật.", "level": "C1", "order_index": 14,
     "word_texts": ["ubiquitous", "eloquent", "paradigm", "pragmatic", "coherent", "mitigate", "nuance", "inherent", "plausible", "unprecedented"]},
]


class Command(BaseCommand):
    help = "Đẩy dữ liệu mẫu vào database (development only)"

    def add_arguments(self, parser):
        parser.add_argument("--clear", action="store_true", help="Xóa dữ liệu cũ trước khi seed")

    def handle(self, *args, **options):
        if options["clear"]:
            self.stdout.write("Đang xóa dữ liệu cũ...")
            WordSetWord.objects.all().delete()
            LessonWord.objects.all().delete()
            WordSet.objects.all().delete()
            Lesson.objects.all().delete()
            Word.objects.all().delete()
            User.objects.filter(is_superuser=False).delete()
            self.stdout.write(self.style.WARNING("Đã xóa dữ liệu cũ."))

        with transaction.atomic():
            admin = self._seed_users()
            words = self._seed_words(admin)
            self._seed_wordsets(admin, words)
            self._seed_lessons(admin, words)

        self.stdout.write(self.style.SUCCESS(
            f"\n✅ Seed hoàn tất!"
            f"\n   Admin:    admin@mnm.com  /  Admin@123456"
            f"\n   Teacher:  teacher@mnm.com  /  Teacher@123456"
            f"\n   Student:  student@mnm.com  /  Student@123456"
            f"\n   Từ vựng:  {len(WORDS)} từ"
            f"\n   Bộ từ:    {len(WORDSETS)} bộ"
            f"\n   Bài học:  {len(LESSONS)} bài"
        ))

    def _seed_users(self):
        self.stdout.write("Đang tạo users...")
        users_data = [
            {"email": "admin@mnm.com",   "username": "admin",   "full_name": "Quản trị viên", "password": "Admin@123456",   "role": "admin",   "is_staff": True,  "is_superuser": True},
            {"email": "teacher@mnm.com", "username": "teacher", "full_name": "Giáo viên Lan", "password": "Teacher@123456", "role": "teacher", "is_staff": False, "is_superuser": False},
            {"email": "student@mnm.com", "username": "student", "full_name": "Học sinh Nam",  "password": "Student@123456", "role": "user",    "is_staff": False, "is_superuser": False},
        ]
        admin = None
        for data in users_data:
            user, created = User.objects.get_or_create(
                email=data["email"],
                defaults={
                    "username":       data["username"],
                    "full_name":      data["full_name"],
                    "role":           data["role"],
                    "is_active":      True,
                    "email_verified": True,
                    "is_staff":       data["is_staff"],
                    "is_superuser":   data["is_superuser"],
                },
            )
            if created:
                user.set_password(data["password"])
                user.save()
                self.stdout.write(f"   + Tạo user: {user.email}")
            else:
                self.stdout.write(f"   ~ Đã tồn tại: {user.email}")
            if data["role"] == "admin":
                admin = user
        return admin

    def _seed_words(self, admin):
        self.stdout.write("Đang tạo từ vựng...")
        word_map = {}
        for data in WORDS:
            # Bỏ qua từ trùng lặp (text + level giống nhau)
            word, created = Word.objects.get_or_create(
                text=data["text"],
                level=data["level"],
                defaults={**data, "created_by": admin},
            )
            word_map[data["text"]] = word
            if created:
                self.stdout.write(f"   + {word.text} [{word.level}]")
        return word_map

    def _seed_wordsets(self, admin, word_map):
        self.stdout.write("Đang tạo bộ từ...")
        for data in WORDSETS:
            ws, created = WordSet.objects.get_or_create(
                name=data["name"],
                defaults={"description": data["description"], "level": data["level"], "created_by": admin},
            )
            if created:
                for i, text in enumerate(data["word_texts"]):
                    if text in word_map:
                        WordSetWord.objects.get_or_create(wordset=ws, word=word_map[text], defaults={"order_index": i})
                self.stdout.write(f"   + Bộ từ: {ws.name}")

    def _seed_lessons(self, admin, word_map):
        self.stdout.write("Đang tạo bài học...")
        for data in LESSONS:
            lesson, created = Lesson.objects.get_or_create(
                title=data["title"],
                defaults={
                    "description":  data["description"],
                    "level":        data["level"],
                    "order_index":  data["order_index"],
                    "is_published": True,
                    "created_by":   admin,
                },
            )
            if created:
                for i, text in enumerate(data["word_texts"]):
                    if text in word_map:
                        LessonWord.objects.get_or_create(lesson=lesson, word=word_map[text], defaults={"order_index": i})
                self.stdout.write(f"   + Bài học: {lesson.title}")
