# Generated by Django 4.2.13 on 2026-06-04 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_emailverificationtoken_token_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emailverificationtoken',
            options={'verbose_name': 'Token xac thuc email', 'verbose_name_plural': 'Token xac thuc email'},
        ),
        migrations.AlterModelOptions(
            name='passwordresettoken',
            options={'verbose_name': 'Token reset mat khau', 'verbose_name_plural': 'Token reset mat khau'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Nguoi dung', 'verbose_name_plural': 'Nguoi dung'},
        ),
        migrations.AlterField(
            model_name='emailverificationtoken',
            name='expires_at',
            field=models.DateTimeField(verbose_name='Het han luc'),
        ),
        migrations.AlterField(
            model_name='passwordresettoken',
            name='expires_at',
            field=models.DateTimeField(verbose_name='Het han luc'),
        ),
        migrations.AlterField(
            model_name='passwordresettoken',
            name='is_used',
            field=models.BooleanField(default=False, verbose_name='Da dung'),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar_url',
            field=models.CharField(blank=True, max_length=500, verbose_name='Anh dai dien'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email_verified',
            field=models.BooleanField(default=False, verbose_name='Email da xac thuc'),
        ),
        migrations.AlterField(
            model_name='user',
            name='full_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Ho va ten'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Hoat dong'),
        ),
        migrations.AlterField(
            model_name='user',
            name='level',
            field=models.IntegerField(default=1, verbose_name='Cap do'),
        ),
        migrations.AlterField(
            model_name='user',
            name='notification_enabled',
            field=models.BooleanField(default=True, verbose_name='Bat thong bao'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('user', 'Hoc sinh'), ('admin', 'Quan tri vien')], default='user', max_length=10, verbose_name='Vai tro'),
        ),
        migrations.AlterField(
            model_name='user',
            name='xp',
            field=models.IntegerField(default=0, verbose_name='Diem kinh nghiem'),
        ),
    ]
