# Generated by Django 4.2.13 on 2026-06-06 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_emailverificationtoken_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='timezone',
            field=models.CharField(default='Asia/Ho_Chi_Minh', max_length=64, verbose_name='Mui gio'),
        ),
    ]
